### ISSUE TITLE
NPE Princess.calculateFiringTurn

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/megamek#1047]
### Environment
MegaMek v0.44.0
Java version 1.8.0_171
Platform Windows 8.1 6.3 (amd64)

### Description
Had two princess bots fighting each other and noticed that Outworlds Alliance became stuck and will not advanced through the firing phase.  Saved and reloaded the game, replaced both bots, and finally received an NPE in my log.

Line 1060:
> java.lang.NullPointerException
> 	at megamek.client.bot.princess.Princess.calculateFiringTurn(Princess.java:461)
> 	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:464)
> 	at megamek.client.bot.BotClient.access$000(BotClient.java:83)
> 	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:104)

![github](https://user-images.githubusercontent.com/16950832/42671143-46f02a50-8624-11e8-9678-7421ebb600dc.png)

### Files
[CvsOA.sav.gz](https://github.com/MegaMek/megamek/files/2191183/CvsOA.sav.gz)
BLOODWOLF
Comstar
Outworlds Alliance
[megameklog.txt](https://github.com/MegaMek/megamek/files/2191184/megameklog.txt)

**Comment by BLOODWOLF333** [comment]
Just ran into this error again.

> java.lang.NullPointerException
> 	at megamek.client.bot.princess.Princess.calculateFiringTurn(Princess.java:461)
> 	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:464)
> 	at megamek.client.bot.BotClient.access$000(BotClient.java:83)
> 	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:104)

![image](https://user-images.githubusercontent.com/16950832/42793931-09754df6-8942-11e8-95c1-26477a541833.png)

**Comment by Dirk-c-Walter** [comment]
The problem is the bot is tryign to plan for a 'null' mek, and checkign as a federated commonwealth player... the next unit button is broken, and princess bot uses the same logic. I'm looking at the save-game to see if I can figure out where your gamestate went so wrong, but most likely it happened earlier in the turn somehow. There might be an exception giving some details before you reload, so if you have it happen again send that log too?

**Comment by BLOODWOLF333** [comment]
well FS and FC are both princess players (am just working through my tournament we are running in #findagame) so I wasnt quite paying attention to what she was doing, goes awful fast.  If I hit this bug again I could post the game log as well but, I dont know how helpful that thing will be.

**Comment by BLOODWOLF333** [comment]
But looked through the log once the thing froze on me and I never get the NPE until after I reload, the last lines in the load before reloading are just her calculating firing phase logging.

Example:

> BotClient calculated turns, Federated Suns phase PHASE_FIRING 1/1
> BotClient calculated turns, Federated Commonwealth phase PHASE_FIRING 3/3
> 22:22:33,559 INFO [megamek.server.Server] {Connection 2}

**Comment by Dirk-c-Walter** [comment]
Yeah the game state is messed up, and I am trying to figure out how it got into that bad state. I was hoping there was an earlier exception before the save and reload that would indicate the problem. Basicly the game thinks it;s still FC's turn to fire, and it also thinks it has nothing left to fire.  Not sure how to get to such a state, something somewhere messed up before this save. But that is searching for a needle in a haystack.

**Comment by BLOODWOLF333** [comment]
Alright game is frozen
![image](https://user-images.githubusercontent.com/16950832/43113409-e5c26690-8ebf-11e8-9000-8a3dcf776f35.png)

[Before reload]
[Freeze.sav.gz](https://github.com/MegaMek/megamek/files/2221723/Freeze.sav.gz)
BLOODWOLF (I'm an observer)
Federated Commonwealth (bot)
Lyran Alliance (bot)
[megameklog.txt](https://github.com/MegaMek/megamek/files/2221727/megameklog.txt)

[After reload]
[megameklog.txt](https://github.com/MegaMek/megamek/files/2221733/megameklog.txt)

**Comment by BLOODWOLF333** [comment]
I tried loading the save and then replacing both bots with debug verbosities but, didnt help much.
[megameklog.txt](https://github.com/MegaMek/megamek/files/2221889/megameklog.txt)
