### ISSUE TITLE
Bot Hangs During Movement Phase 0.45.0 snapshot

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1120]
Was playing a Clan vs. Clan game with all simultaneous options on (movement, deployment, attacks, etc).  

Autosave file should be the start of the phase when the error occurs.

Game was moving along fine until the bot stopped moving.  Game save and log file attached.
[megameklog.txt](https://github.com/MegaMek/megamek/files/2343851/megameklog.txt)
[savegame.sav.gz](https://github.com/MegaMek/megamek/files/2343852/savegame.sav.gz)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/2343853/autosave.sav.gz)

**Comment by sixlettervariables** [comment]
Two issues I saw in the log:
```
07:54:06,237 ERROR [megamek.server.Server] {Packet Pump} 
error: server got invalid movement packet from connection 1, Entity: Rifleman IIC (Standard)
BotClient calculated turns, Princess phase PHASE_PHYSICAL 1/11
```
And earlier (likely unrelated):
```
java.lang.NullPointerException
	at megamek.client.ui.swing.Ruler.buildAttackInfo(Ruler.java:436)
	at megamek.client.ui.swing.Ruler.setText(Ruler.java:382)
	at megamek.client.ui.swing.Ruler.checkBoxSelectionChanged(Ruler.java:508)
	at megamek.client.ui.swing.Ruler$4.itemStateChanged(Ruler.java:173)
	at 
...snipped...
```

**Comment by NickAragua** [comment]
The main issue here is the bit about simultaneous movement. Support for it is still a bit wonky.

**Comment by BLR-IIC** [comment]
Since simultaneous movement is no longer in MegaMek, I'm closing this issue since it's no longer relevant.
