### ISSUE TITLE
Units not applying Camo

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/megamek#1127]
![image](https://user-images.githubusercontent.com/19868605/45255732-19bbcf00-b359-11e8-880c-8aa94245bdbf.png)

And trying to apply individual camo is not working either. 45.1

**Comment by neoancient** [comment]
Unable to reproduce. MegaMek is applying camo to entire force and individually. While it may be possible that there are some game settings affecting this, the user did not provide the requested game save or log file, so there is nothing to be done here.

**Comment by VampireSeraphin** [comment]
![image](https://user-images.githubusercontent.com/19868605/45512354-87a73280-b76d-11e8-9661-d98185f7cfc1.png)

[megameklog.txt](https://github.com/MegaMek/megamek/files/2380801/megameklog.txt)

Log attached now.

**Comment by HammerGS** [comment]
Error from Log
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Row index out of range
	at javax.swing.JTable.boundRow(Unknown Source)
	at javax.swing.JTable.setRowSelectionInterval(Unknown Source)
	at megamek.client.ui.swing.CamoChoiceDialog.setEntity(CamoChoiceDialog.java:422)
	at megamek.client.ui.swing.ChatLounge.mechCamo(ChatLounge.java:2431)
	at megamek.client.ui.swing.ChatLounge$MekTableMouseAdapter.actionPerformed(ChatLounge.java:3577)
```

**Comment by HammerGS** [comment]
Per a contributor request, who wants to look more closely at this
