### ISSUE TITLE
[Dev Master] NPE when using dropships 

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#1169]
Simply click 'done' until end of turn, then when you click 'done' to finally end the turn, the client will freeze and the server will bomb with the following exception.

Exception in thread "Packet Pump" java.lang.ArrayIndexOutOfBoundsException: 4
	at megamek.common.Dropship.getASEWAffected(Dropship.java:58)
	at megamek.server.Server.decrementASEWTurns(Server.java:1898)
	at megamek.server.Server.endCurrentPhase(Server.java:3262)
	at megamek.server.Server.changePhase(Server.java:2485)
	at megamek.server.Server.endCurrentPhase(Server.java:3163)
	at megamek.server.Server.changePhase(Server.java:2485)
	at megamek.server.Server.endCurrentPhase(Server.java:3142)
	at megamek.server.Server.checkReady(Server.java:2255)
	at megamek.server.Server.handle(Server.java:32241)
	at megamek.server.Server$PacketPump.run(Server.java:368)

[preasewcrash.sav.gz](https://github.com/MegaMek/megamek/files/2457186/preasewcrash.sav.gz)

**Comment by neoancient** [comment]
I think I probably broke this.
