### ISSUE TITLE
45.2 : Could not find squad size

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#1224]
When I go into the lobby, megamek complains that it could not find the squad size for two infantry units : 

 Looking in zip file data\mechfiles\unsupported.zip...
    Loading from zip file >> infantry/Clan Infantry/Clan Motorized Combat Engineers.blk
      Unable to load file: megamek.common.loaders.EntityLoadingException: Could not find squad size.
	at megamek.common.MechFileParser.<init>(MechFileParser.java:123)
	at megamek.common.MechSummaryCache.loadMechsFromZipFile(MechSummaryCache.java:681)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:581)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:252)
	at megamek.common.MechSummaryCache$1.run(MechSummaryCache.java:101)
	at java.lang.Thread.run(Unknown Source)

    Loading from zip file >> infantry/Inner Sphere Infantry/Motorized Combat Engineers.blk
      Unable to load file: megamek.common.loaders.EntityLoadingException: Could not find squad size.
	at megamek.common.MechFileParser.<init>(MechFileParser.java:123)
	at megamek.common.MechSummaryCache.loadMechsFromZipFile(MechSummaryCache.java:681)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:581)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:252)
	at megamek.common.MechSummaryCache$1.run(MechSummaryCache.java:101)
	at java.lang.Thread.run(Unknown Source)
[megameklog.txt](https://github.com/MegaMek/megamek/files/2727215/megameklog.txt)

**Comment by HammerGS** [comment]
These units would were removed here - https://github.com/MegaMek/megamek/commit/515de9b9b21791174941c1a908aee960415fa3ed
