### ISSUE TITLE
[0.45.1] Ubuntu version problems launching

### ISSUE THREAD

**Issue by NooneAtAll** [MegaMek/megamek#1394]
Downloaded linux version of Megamek 0.45.1 from [here](https://megamek.github.io/downloads.html)  
Extracted to the desktop, opened the folder in terminal, used the code from the same page  
> java -jar MegaMek.jar &

Result:

> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at megamek.MegaMek.<clinit>(MegaMek.java:80)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

Is this a problem on my end or on program's end?

------

Ubuntu 18.04, updated java and ubuntu to latest version, I think

**Comment by neoancient** [comment]
As of Java 9, some libraries are no longer loaded by default and require a command line switch to force loading. Details are here: https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds. As of version 0.45.2 those libraries are explicitly included and it works with Java 9+ out of the box.

The site where you got the link is a work in progress and does not contain links to the latest version, which is 0.45.4. The official website is still here: http://megamek.org
