### ISSUE TITLE
Maps not Loading

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#1475]
From this forum post.

https://forum.megamek.org/showthread.php?tid=2644

The logs where emailed and not sure what to make of the error:

From the Megamek bill:
```
05:28:21,246 ERROR [mekhq.preferences.MekHqPreferences] {main} 
No MekHQ user preferences file found: mmconf/mekhq.preferences
java.io.FileNotFoundException: mmconf\mekhq.preferences (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at mekhq.preferences.MekHqPreferences.loadFromFile(MekHqPreferences.java:54)
	at mekhq.MekHQ.startup(MekHQ.java:285)
	at mekhq.MekHQ.main(MekHQ.java:357)
```
From the MekHQ log
```
This is one is over and over
boardview1: loading images for board
Trying to load image for a non-existant file! Path: data\images\units\mechs\Phoenixhawk.gif
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at megamek.common.util.ImageUtil.createAcceleratedImage(ImageUtil.java:72)
	at megamek.common.util.ImageUtil$AWTImageLoader.loadImage(ImageUtil.java:196)
	at megamek.common.util.ImageUtil.loadImageFromFile(ImageUtil.java:154)
	at megamek.client.ui.swing.MechTileset$MechEntry.loadImage(MechTileset.java:542)
	at megamek.client.ui.swing.MechTileset.imageFor(MechTileset.java:217)
	at megamek.client.ui.swing.TilesetManager.loadImage(TilesetManager.java:594)
	at megamek.client.ui.swing.TilesetManager.loadNeededImages(TilesetManager.java:407)
	at megamek.client.ui.swing.boardview.BoardView1.paintComponent(BoardView1.java:1206)

```
and at the end of the log
```
boardview1: loading images for board
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source)
	at megamek.common.util.ImageUtil.createAcceleratedImage(ImageUtil.java:89)
	at megamek.client.ui.swing.TilesetManager$EntityImage.loadFacings(TilesetManager.java:703)
	at megamek.client.ui.swing.TilesetManager.loadImage(TilesetManager.java:623)
	at megamek.client.ui.swing.TilesetManager.loadNeededImages(TilesetManager.java:407)
	at megamek.client.ui.swing.boardview.BoardView1.paintComponent(BoardView1.java:1206)
```
followed by
```
boardview1: loading images for board
Exception in thread "D3D Screen Updater" Exception in thread "TimerSingleton Timer" Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space
Exception in thread "AWT-EventQueue-0" 
```

**Comment by sixlettervariables** [comment]
The prefs exception can be ignored. The other three indicate that the graphics engine could not allocate enough space, likely leading to the maps failing to load.

**Comment by PMG068** [comment]
Thanks for looking is there anything that can be done to overcome this problem? I have downloaded the latest version but hav not used it yet.

**Comment by sixlettervariables** [comment]
Our Wiki details how to increase the memory limit. Are you using 32-bit or 64-bit Java instance?

https://github.com/MegaMek/megamek/wiki/Known-Issues-and-Workarounds

**Comment by PMG068** [comment]
Just tested, using 64-bit

**Comment by PMG068** [comment]
Anymore solutions on this matter?

**Comment by sixlettervariables** [comment]
Did you increase the memory limit for MegaMek?

**Comment by PMG068** [comment]
no as im not real confident in playing with java etc

**Comment by PMG068** [comment]
did a bit of looking and worked it out was only running 1024m so upped it to 4000 going heaps faster so far, thanks again for pushing me in the right direction

**Comment by NickAragua** [comment]
Good to hear. Closing as issue appears to be resolved.

**Comment by PMG068** [comment]
well it was working lol but same issue will try different numbers

**Comment by HammerGS** [comment]
Received this via PM

> Hi Hammer I had the problems with the map not loading https://github.com/MegaMek/megamek/issues/1475 unfortunately the problem still exists i even bumped the runtime
> 
> -Xmx12000m up as you see from 3000, for all the I14j.ini. Should i reinstall 46.0 again?
> 
> Regards PMG068

**Comment by Windchild292** [comment]
There have been significant changes in maps since this time, and this is likely resolved.
