### ISSUE TITLE
Selecting the Adelante Train throws IndexOutOfBounds Exception

### ISSUE THREAD

**Issue by blah2355** [MegaMek/megamek#1481]
### Environment
MegaMek v0.46.0
Windows
Java version 1.8.0_221

### Description
Selecting the "Adelante Train" under "IS TW non-box set" in lobby causes the game to freeze up and is unresponsive to any button inputs. See log for error.

### Files
[adelante_megameklog.txt](https://github.com/MegaMek/megamek/files/3592338/adelante_megameklog.txt)

**Comment by HammerGS** [comment]
From the log
```
Missing i18n entry: MovementType.Rail
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: can't find an image for that mech
	at megamek.client.ui.swing.MechTileset.genericFor(MechTileset.java:414)
	at megamek.client.ui.swing.MechTileset.entryFor(MechTileset.java:251)
	at megamek.client.ui.swing.MechTileset.imageFor(MechTileset.java:204)
	at megamek.client.ui.swing.TilesetManager.loadPreviewImage(TilesetManager.java:510)
	at megamek.client.ui.swing.ClientGUI.loadPreviewImage(ClientGUI.java:1742)
	at megamek.client.ui.swing.UnitSelectorDialog.refreshUnitView(UnitSelectorDialog.java:718)
	at megamek.client.ui.swing.UnitSelectorDialog$1.valueChanged(UnitSelectorDialog.java:278)
```

**Comment by neoancient** [comment]
This is because MM doesn't have a default rail icon and the fault recovery of the sprite lookup system leaves much to be desired. I fixed this in the support vehicle construction branch that I'm working on, which should be included in the next dev snapshot. But this is serious enouh that I'll need to hunt down that commit and bring it into the stable branch as well for the next bugfix release.

**Comment by neoancient** [comment]
I decided on a fix that would address the poor fault recovery instead.
