### ISSUE TITLE
offboard artillery - designate hex phase skipped when artillery comes from mekhq

### ISSUE THREAD

**Issue by db984** [MegaMek/megamek#1539]
An artillery unit is attached to a force in mekhq, is brought into megamek via the start button in the 'briefing room', is configured in megamek to deploy offboard. Megamek does not prompt to designate hexes at the start of the game.

### Environment
0.46.0, launching megamek from mekhq

### Description
Steps to reproduce:
1) Load CPNX file in mekhq 0.46.0.
-- In the TO&E SDF/Lance2 there is a Thumper.
-- In the Briefing room, the current mission is a stand up fight, involving SFD/Lance2.
2) Click "Start"

3) Right click on the Thumper, configure, and set the deploy option to 'offboard'.
4) Click "I'm done."
-- The game starts, skips the designate hex step, and proceeds to deployment.

Note:
It DOES prompt to designate hexes in this scenario.
Follow steps 1 & 2 above.
Then delete the thumper unit. (right click "Delete...")
Then manually add a thumper unit (via the "Add a Combat Unit"); and continue steps 3-4 above.
The game now does prompt to designate hexes.

### Files
CPNX file attached (zipped)
[DaveGreg30260324--bugreport.zip](https://github.com/MegaMek/megamek/files/3827884/DaveGreg30260324--bugreport.zip)

**Comment by HammerGS** [comment]
We also need any log files (megameklog.txt. mekhqlog.txt) for the above steps

**Comment by db984** [comment]
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/3828086/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/megamek/files/3828087/megameklog.txt)

Logs attached.

**Comment by HammerGS** [comment]
This is in the MekHQ log, not sure if it's related.

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at mekhq.gui.model.ScenarioTableModel.getScenario(ScenarioTableModel.java:106)
	at mekhq.gui.BriefingTab.refreshScenarioView(BriefingTab.java:851)
	at mekhq.gui.ActionScheduler.lambda$new$0(ActionScheduler.java:46)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by db984** [comment]
Pretty sure its not related. I just tried it in a clean 0.47.0. (no log files)
Loaded the campaign, started the fight, configured the thumper deployment, ... and confirmed it didn't prompt to designate hexes.

Log files attached. No exceptions were thrown.


[megameklog.txt](https://github.com/MegaMek/megamek/files/3833808/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/3833809/mekhqlog.txt)
[gamelog.html.txt](https://github.com/MegaMek/megamek/files/3833810/gamelog.html.txt)

**Comment by neoancient** [comment]
I'm still working on narrowing this down, but I've learned that it has nothing to do with transferring from MekHQ. This occurs when Princess is involved.

**Comment by neoancient** [comment]
Nevermind. It happened once, but now it's working fine with Princess involved.
