### ISSUE TITLE
Repeat Portraits with Random Generation - NPE in Log (megamek.client.ui.swing.PortraitChoiceDialog.generateIcon)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#1554]
From Slack post.

### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek r HQ's MegaMek.  47.2

### Description
when loading an OPFOR unit into Megamek I have random portrait generation checked and it loads a repeat of whatever portrait I select
![Screen Shot 11-24-19 at 06 47 PM 001](https://user-images.githubusercontent.com/13752452/69505442-37863d00-0ee7-11ea-9fac-00c3ef947701.PNG)
![Screen Shot 11-24-19 at 06 47 PM](https://user-images.githubusercontent.com/13752452/69505443-37863d00-0ee7-11ea-86aa-bea110631ae6.PNG)
![Screen Shot 11-24-19 at 06 43 PM](https://user-images.githubusercontent.com/13752452/69505444-381ed380-0ee7-11ea-9d52-a2535eaead15.PNG)
![Screen Shot 11-24-19 at 06 46 PM](https://user-images.githubusercontent.com/13752452/69505445-381ed380-0ee7-11ea-8323-6f9dc305a539.PNG)

### Files
NPE from Log
```
java.lang.NullPointerException
	at megamek.client.ui.swing.PortraitChoiceDialog.generateIcon(PortraitChoiceDialog.java:278)
	at megamek.client.ui.swing.PortraitChoiceDialog.setPilot(PortraitChoiceDialog.java:213)
	at megamek.client.ui.swing.CustomPilotView.<init>(CustomPilotView.java:108)
	at megamek.client.ui.swing.CustomMechDialog.<init>(CustomMechDialog.java:324)
	at megamek.client.ui.swing.ChatLounge.customizeMech(ChatLounge.java:2357)
	at megamek.client.ui.swing.ChatLounge$MekTableMouseAdapter.actionPerformed(ChatLounge.java:3580)

```

**Comment by Windchild292** [comment]
The dialog in question no longer exists, and MegaMek does not include a random portrait generator.

Further, the code in this region has been almost entirely rewritten, so this can be closed.
