### ISSUE TITLE
Critical Hit on Protomech Near Miss 0.47.2

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#1562]
> Weapons fire for UrbanMech UM-R60 #3 (Princess)
>     AC/10 at Urbanmech IIC PM UM-PM-IIC (Harold); needs 8, rolls 9 : hits  a near miss
>         Critical hit on [Reporting Error: see megameklog.txt for details].

megameklog.txt attached.
[megameklog.txt](https://github.com/MegaMek/megamek/files/3930129/megameklog.txt)

**Comment by HammerGS** [comment]
One error on the log. Repeated a few times.
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at megamek.common.pathfinder.InfantryPathFinder.run(InfantryPathFinder.java:74)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:267)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)
BotClient calculated turns, Princess phase PHASE_PHYSICAL 1/4
Error: Report#getText --> Array Index out of Bounds Exception (index: 0) for a report with ID 6305.  Maybe Report#add wasn't called enough times for the amount of tags in the message?
```
