### ISSUE TITLE
[47.5-Snapshot] Helepolis HEP-1H TRO and summary fail to render

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#1778]
When clicking 'Add a Combat Unit' and selecting the Helepolis HEP-1H, neither the TRO nor the summary render. Likely culprit is this exception: 

java.lang.ArrayIndexOutOfBoundsException: -1
	at megamek.common.Entity.getArmorType(Entity.java:10490)
	at megamek.common.templates.TROView.addEquipment(TROView.java:428)
	at megamek.common.templates.TROView.addEquipment(TROView.java:406)
	at megamek.common.templates.MechTROView.initModel(MechTROView.java:52)
	at megamek.common.templates.TROView.createView(TROView.java:115)
	at megamek.client.ui.swing.UnitSelectorDialog.refreshUnitView(UnitSelectorDialog.java:697)
	at megamek.client.ui.swing.UnitSelectorDialog.lambda$0(UnitSelectorDialog.java:272)

**Comment by mhjacks** [comment]
I confirm that on the snapshot; I see exactly the same issue with the Grand Titan T-IT-N14R "Vengeance"

**Comment by neoancient** [comment]
Fixed by #1868
