### ISSUE TITLE
Princessbot freezes w/ Infantry vs Apocalypse World Rover (ClassCastException)

### ISSUE THREAD

**Issue by snuhgit** [MegaMek/megamek#1797]
I was just messing around with a Mad Max-esque scenario with technicals, jeeps, and motorized infantry and apparently Princessbot didn't like it.

### Environment
MekHQ's MegaMek
MegaMek v0.46.1 ...
	Compiled on Mon Mar 09 15:11:45 PDT 2020
	Today is Fri Mar 27 18:16:15 PDT 2020
	Java vendor Oracle Corporation
	Java version 1.8.0_241
	Platform Windows 10 10.0 (x86)
	Total memory available to MegaMek: 1,013,632 kB

### Description
Princessbot is consistently freezing around Round 2-6 when using a Apocalypse World Rover (player) against an Infantry Mechanized Hover Platoon (bot). Unable to skip.

**Steps to reproduce:**
1. Load attached save game
2. Advance turn
3. Game should hang on Princessbot's turn. (If it doesn't, try advancing a few more turns. In all my tests it consistently freezes, just not on the same turn.)

I've run several battles with infantry on different maps and gotten the same results.

### Files
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/4396554/mekhqlog.txt)
[Marauders_b1_hanging_r6.sav.gz](https://github.com/MegaMek/megamek/files/4396556/Marauders_b1_hanging_r6.sav.gz)

Player Name: Marauders

**Comment by HammerGS** [comment]
From the Log
java.lang.ClassCastException: megamek.common.SupportTank cannot be cast to megamek.common.Infantry
	at megamek.client.bot.princess.InfantryFireControl.getMaxDamageAtRange(InfantryFireControl.java:78)
	at megamek.client.bot.princess.InfantryPathRanker.getMaxDamageAtRange(InfantryPathRanker.java:187)
	at megamek.client.bot.princess.InfantryPathRanker.evaluateUnmovedEnemy(InfantryPathRanker.java:164)
	at megamek.client.bot.princess.InfantryPathRanker.rankPath(InfantryPathRanker.java:70)
	at megamek.client.bot.princess.PathRanker.rankPaths(PathRanker.java:110)
	at megamek.client.bot.princess.Princess.continueMovementFor(Princess.java:1294)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:474)
	at megamek.client.bot.BotClient.access$000(BotClient.java:83)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:104)
	at java.lang.Thread.run(Unknown Source)
