### ISSUE TITLE
TurnTimer::timerShouldStart NPE's on Turn End

### ISSUE THREAD

**Issue by Windchild292** [MegaMek/megamek#1924]
This was reported on Discord. They were unable to complete their turn due to the NPE, and they did not have the turn timer enabled.
[Files.zip](https://github.com/MegaMek/megamek/files/4600676/Files.zip)

**Comment by HammerGS** [comment]
A few different things in the log

```
java.lang.ArrayIndexOutOfBoundsException: 15
	at megamek.common.Aero.calculateBattleValue(Aero.java:2521)
	at megamek.common.Aero.calculateBattleValue(Aero.java:1328)
	at megamek.client.bot.princess.MoralUtil.calcBvRatioMod(MoralUtil.java:177)
	at megamek.client.bot.princess.MoralUtil.checkMoral(MoralUtil.java:65)
	at megamek.client.bot.princess.Princess.checkMoral(Princess.java:1839)
	at megamek.client.bot.princess.Princess.initMovement(Princess.java:1554)
	at megamek.client.bot.BotClient.changePhase(BotClient.java:415)
	at megamek.client.Client.handlePacket(Client.java:1301)
	at megamek.client.bot.princess.Princess.handlePacket(Princess.java:1884)
	at megamek.client.Client$1$2.run(Client.java:218)
```

Also

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ui.swing.util.TurnTimer.timerShouldStart(TurnTimer.java:120)
	at megamek.client.ui.swing.util.TurnTimer.init(TurnTimer.java:102)
	at megamek.client.ui.swing.MovementDisplay.beginMyTurn(MovementDisplay.java:1026)
	at megamek.client.ui.swing.MovementDisplay.gameTurnChange(MovementDisplay.java:4391)
	at megamek.common.event.GameTurnChangeEvent.fireEvent(GameTurnChangeEvent.java:51)
	at megamek.common.Game.processGameEvent(Game.java:3153)
	at megamek.common.Game.setTurnIndex(Game.java:744)
	at megamek.client.Client.changeTurnIndex(Client.java:562)
	at megamek.client.Client.handlePacket(Client.java:1304)
	at megamek.client.Client$1$2.run(Client.java:218)
```

and

```
java.lang.IllegalArgumentException: Entity invalid. ID 19
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:491)
	at megamek.common.MovePath.addStep(MovePath.java:487)
	at megamek.common.MovePath.addStep(MovePath.java:257)
	at megamek.common.MovePath.addStep(MovePath.java:169)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:386)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:319)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:274)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)

```

**Comment by Windchild292** [comment]
Another log from a test where the option for the TurnTimer was specifically added to their options file. It did not resolve the issue, and raised another exception:
[megameklog (1).txt](https://github.com/MegaMek/megamek/files/4600850/megameklog.1.txt)

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ui.swing.AccessibilityWindow$1.gameNewAction(AccessibilityWindow.java:82)
	at megamek.common.event.GameNewActionEvent.fireEvent(GameNewActionEvent.java:52)
	at megamek.common.Game.processGameEvent(Game.java:3153)
	at megamek.common.Game.addAction(Game.java:2367)
	at megamek.client.Client.receiveAttack(Client.java:1109)
	at megamek.client.Client.handlePacket(Client.java:1357)
	at megamek.client.Client$1$2.run(Client.java:218)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by neoancient** [comment]
The ArrayIndexOutOfBoundsException in Aero relates to bombs.
The NPE in TurnTimer is likely from loading an options file from a previous version. We really should initialize all the options to their default values before loading a file. If we already do that, then I don't know what the cause is.
Is suspect that the final NPE is related to the IllegalArgumentException thrown by Compute#isPilotingSkillNeeded, both caused by a non-existent Entity.

**Comment by sixlettervariables** [comment]
I've fixed the accessibility window issue in #2025.
