### ISSUE TITLE
Start of Game Stuck at Transmitting Game Data Packet Pump Null Pointer Exception (Generated Map Settings)

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/megamek#1974]
### Environment
0.46.1 MekHQ Install, but running MegaMek solo.
Starting MegaMek v0.46.1 ...
	Compiled on Fri Apr 17 20:09:23 CDT 2020
	Today is Sun May 24 11:05:30 CDT 2020
	Java vendor Oracle Corporation
	Java version 1.8.0_251
	Platform Windows 10 10.0 (amd64)
	Total memory available to MegaMek: 932,352 kB

### Description
Start. 
Add 1 Bot.
Add 1 Mech to User
Add 1 Mech to Bot
Select "Select Map"
Select Generated Map Settings.
Change size to 10X30
Change City to Metro
Change Road to High
Click Okay
Click I'm Done.
Stuck at Transmitting Data.

### Files

[megameklog.txt](https://github.com/MegaMek/megamek/files/4673905/megameklog.txt)

**Comment by HammerGS** [comment]
From the log
```
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.server.Server.applyBoardSettings(Server.java:3685)
	at megamek.server.Server.executePhase(Server.java:2904)
	at megamek.server.Server.changePhase(Server.java:2506)
	at megamek.server.Server.endCurrentPhase(Server.java:3049)
	at megamek.server.Server.checkReady(Server.java:2278)
	at megamek.server.Server.handle(Server.java:32808)
	at megamek.server.Server$PacketPump.run(Server.java:369)
```

**Comment by sixlettervariables** [comment]
Since `Server.java` is too big to show, I pulled it local. Looks like a selected board didn't have a name?
```java
    /**
     * Applies board settings. This loads and combines all the boards that were
     * specified into one mega-board and sets that board as current.
     */
    public void applyBoardSettings() {
        mapSettings.replaceBoardWithRandom(MapSettings.BOARD_RANDOM);
        mapSettings.replaceBoardWithRandom(MapSettings.BOARD_SURPRISE);
        IBoard[] sheetBoards = new IBoard[mapSettings.getMapWidth()
                * mapSettings.getMapHeight()];
        List<Boolean> rotateBoard = new ArrayList<>();
        for (int i = 0; i < (mapSettings.getMapWidth() * mapSettings
                .getMapHeight()); i++) {
            sheetBoards[i] = new Board();
            String name = mapSettings.getBoardsSelectedVector().get(i);
            boolean isRotated = false;
            if (name.startsWith(Board.BOARD_REQUEST_ROTATION)) { // LINE 3685
                // only rotate boards with an even width
                if ((mapSettings.getBoardWidth() % 2) == 0) {
                    isRotated = true;
                }
                name = name.substring(Board.BOARD_REQUEST_ROTATION.length());
            }
            if (name.startsWith(MapSettings.BOARD_GENERATED)
                    || (mapSettings.getMedium() == MapSettings.MEDIUM_SPACE)) {
                sheetBoards[i] = BoardUtilities.generateRandom(mapSettings);
            } else {
                sheetBoards[i].load(new MegaMekFile(Configuration.boardsDir(), name
                        + ".board").getFile());
                BoardUtilities.flip(sheetBoards[i], isRotated, isRotated);
            }
            rotateBoard.add(isRotated);
        }
        IBoard newBoard = BoardUtilities.combine(mapSettings.getBoardWidth(),
                mapSettings.getBoardHeight(), mapSettings.getMapWidth(),
                mapSettings.getMapHeight(), sheetBoards, rotateBoard,
                mapSettings.getMedium());
        if (game.getOptions().getOption(OptionsConstants.BASE_BRIDGECF).intValue() > 0) {
            newBoard.setBridgeCF(game.getOptions().getOption(OptionsConstants.BASE_BRIDGECF)
                    .intValue());
        }
        if (!game.getOptions().booleanOption(OptionsConstants.BASE_RANDOM_BASEMENTS)) {
            newBoard.setRandomBasementsOff();
        }
        if (game.getPlanetaryConditions().isTerrainAffected()) {
            BoardUtilities.addWeatherConditions(newBoard, game
                    .getPlanetaryConditions().getWeather(), game
                    .getPlanetaryConditions().getWindStrength());
        }
        game.setBoard(newBoard);
    }
```
