### ISSUE TITLE
NPE on indirect artillery fire

### ISSUE THREAD

**Issue by AaronGullickson** [MegaMek/megamek#2008]
### Environment
Megamek 0.47.6 bundled with MekHQ, MacOSX, Java 8
What operating system are you using?  Windows, Mac, ##or Linux?

### Description

Game stalled, refusing to advance from indirect firing resolution with the following NPE in the log:

```java
Exception in thread "Packet Pump" java.lang.NullPointerException
        at megamek.common.weapons.ArtilleryWeaponIndirectFireHandler.handle(ArtilleryWeaponIndirectFireHandler.java:158)
        at megamek.server.Server.handleAttacks(Server.java:35820)
        at megamek.server.Server.handleAttacks(Server.java:35749)
        at megamek.server.Server.endCurrentPhase(Server.java:2994)
        at megamek.server.Server.changeToNextTurn(Server.java:3246)
        at megamek.server.Server.endCurrentTurn(Server.java:2255)
        at megamek.server.Server.receiveAttack(Server.java:13459)
        at megamek.server.Server.handle(Server.java:31699)
        at megamek.server.Server$PacketPump.run(Server.java:263)

```

I was using a combination of Arrow IV homing and basic sniper rounds. I don't know which caused the problem. 

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/4783353/autosave.sav.gz)

**Comment by sixlettervariables** [comment]
Line in question https://github.com/MegaMek/megamek/blob/78d410fe5e5c9d7787d6bbd0e4b53771853855fd/megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectFireHandler.java#L157-L162

Seems like `ammoCarrier` is missing. This code is the same in master.

**Comment by NickAragua** [comment]
I'll add it to my list.
