### ISSUE TITLE
ArrayIndexOutOfBoundsException: -1 in Configure unit

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2015]
When have a bunch of units in the lobby and you use the next to move between them, when you get to the bottom of the list the next instead of taking you to the top of the list. Freezes the window and you have to use the X to close it.

### Environment
What version of MegaMek does your issue apply to?  47.7 running from the Repo
What operating system are you using?  Windows,

### Description
```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at megamek.client.ui.swing.EquipChoicePanel$WeaponAmmoChoicePanel.applyChoice(EquipChoicePanel.java:1423)
	at megamek.client.ui.swing.EquipChoicePanel.applyChoices(EquipChoicePanel.java:401)
	at megamek.client.ui.swing.CustomMechDialog.actionPerformed(CustomMechDialog.java:1266)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
```

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/4805522/megameklog.txt)

**Comment by sixlettervariables** [comment]
Closed by #2016.
