### ISSUE TITLE
Watchdog ECM Bunker - Empty TRO card

### ISSUE THREAD

**Issue by MGM175** [MegaMek/megamek#2022]
### Environment
- MegaMek 0.47.7
- Java:
openjdk version "11.0.7.2" 2020-04-26
OpenJDK Runtime Environment (Alibaba Dragonwell) (build 11.0.7.2+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell) (build 11.0.7.2+9, mixed mode)
(I don't think that Java was a matter; all other things were OK).
- OS: Linux (Ubuntu 20.04 Focal Fossa)

### Description
So I've selected the Watchdog ECM Bunker, and TRO card was empty, like on the picture.

### Files
Provided screenshot
![bug](https://user-images.githubusercontent.com/20325180/85434737-cabf4800-b586-11ea-9bec-fa2587d07d2d.png)

Now the question is - is it intended or not?

**Comment by NickAragua** [comment]
Looks like there's an error rendering the summary and TRO view for pretty much every gun emplacement, so, no, not intended.

**Comment by sixlettervariables** [comment]
Exception from the log:
```
java.lang.ArrayIndexOutOfBoundsException: 1
	at megamek.common.Entity.getArmorTechLevel(Entity.java:10589)
	at megamek.common.Entity.isClanArmor(Entity.java:1375)
	at megamek.common.verifier.TestTank.getArmor(TestTank.java:66)
	at megamek.common.verifier.TestTank.<init>(TestTank.java:44)
	at megamek.common.templates.VehicleTROView.initModel(VehicleTROView.java:72)
	at megamek.common.templates.TROView.createView(TROView.java:115)
	at megamek.client.ui.swing.UnitSelectorDialog.refreshUnitView(UnitSelectorDialog.java:700)
	at megamek.client.ui.swing.UnitSelectorDialog.lambda$initComponents$0(UnitSelectorDialog.java:275)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
...
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at megamek.client.ui.swing.UnitSelectorDialog.setVisible(UnitSelectorDialog.java:855)
	at megamek.client.ui.swing.ChatLounge.loadMech(ChatLounge.java:2511)
	at megamek.client.ui.swing.ChatLounge.actionPerformed(ChatLounge.java:2671)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
...
```

**Comment by NickAragua** [comment]
I looked at it a little bit, and the problem is that gun emplacements don't have any armor. Having "getArmor()" return an new empty array allows the status view to show, but the TRO view is still broken because it's serializing using some kind of "free view template" or something and I have no way of telling which property it's calling and failing on.
