### ISSUE TITLE
47.0-dev error loading board

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#2063]
Attempting to load or preview this saved board errors out with the following exception (log from preview):

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -60
	at megamek.common.Board.load(Board.java:881)
	at megamek.common.Board.load(Board.java:826)
	at megamek.common.Board.load(Board.java:813)
	at megamek.client.ui.swing.ChatLounge.previewMapsheet(ChatLounge.java:1113)
	at megamek.client.ui.swing.ChatLounge.valueChanged(ChatLounge.java:3072)

[c28m4commsfacility.zip](https://github.com/MegaMek/megamek/files/4920106/c28m4commsfacility.zip)

To create this board, I generated a 70x100 map using the "city-dense" map generator preset, then did a 'save board'.

**Comment by SJuliez** [comment]
Vertical size > 99 doesnt load currently.

**Comment by NickAragua** [comment]
Right, forgot about that.

**Comment by NickAragua** [comment]
Duplicate of #1898
