### ISSUE TITLE
41.17 : Bot refuses to deploy because of NPE

### ISSUE THREAD

**Issue by Question2** [MegaMek/megamek#207]
Specifically the clan jade falcon bot won't deploy.

`java.lang.NullPointerException
	at megamek.common.pathfinder.ShortestPathFinder.getLevelDiff(ShortestPathFinder.java:397)
	at megamek.common.pathfinder.ShortestPathFinder$MovePathAStarComparator.compare(ShortestPathFinder.java:212)
	at megamek.common.pathfinder.ShortestPathFinder$MovePathAStarComparator.compare(ShortestPathFinder.java:167)
	at java.util.PriorityQueue.siftUpUsingComparator(Unknown Source)
	at java.util.PriorityQueue.siftUp(Unknown Source)
	at java.util.PriorityQueue.offer(Unknown Source)
	at java.util.PriorityQueue.add(Unknown Source)
	at java.util.AbstractQueue.addAll(Unknown Source)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:298)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:325)
	at megamek.client.bot.BotClient.hasPathToCenter(BotClient.java:778)
	at megamek.client.bot.BotClient.getStartingCoordsArray(BotClient.java:724)
	at megamek.client.bot.princess.Princess.calculateDeployment(Princess.java:247)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:397)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:99)
	at java.lang.Thread.run(Unknown Source)`

[#battletech.zip](https://github.com/MegaMek/megamek/files/272347/battletech.zip)

**Comment by pheonixstorm** [comment]
Is this the same as issue #33 ?

**Comment by dericpage** [comment]
Related, but not the same no.  In the previous case, the current hex was NULL.  In this case it's the destination.

**Comment by pheonixstorm** [comment]
Ah, ok.

**Comment by arlith** [comment]
With the last referenced commit, the only way I could see this happening has been removed.  I can't verify that this fixes the bug, but we also added logging code that may help work this issue out if it does happen.  I am going to close this ticket for now, and if it crops up again, open a new ticket and we can reference this one.

**Comment by pheonixstorm** [comment]
Will this resolve issue 33 as well or will that require another fix?
