### ISSUE TITLE
MM 47.9 Princess locking up during pathfinding - IllegalArgumentException

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2142]
Standalone MegaMek 47.9
Windows10
Java 1.8.0_261

Princess locked up as player 'Mi' with Missile Boat configuration while selecting move. Resolved by kick-and-replace.

> Exception in thread "Princess-precognition (Mi)" java.lang.IllegalArgumentException: Entity invalid. ID 8
> 	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:491)
> 	at megamek.common.MovePath.addStep(MovePath.java:497)
> 	at megamek.common.MovePath.addStep(MovePath.java:267)
> 	at megamek.common.MovePath.addStep(MovePath.java:179)
> 	at megamek.common.BulldozerMovePath.addStep(BulldozerMovePath.java:80)
> 	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.generateChildNodes(DestructionAwareDestinationPathfinder.java:171)
> 	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:114)
> 	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:55)
> 	at megamek.client.bot.princess.PathEnumerator.updateLongRangePaths(PathEnumerator.java:380)
> 	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:317)
> 	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)

[megameklog20200813-0304.zip](https://github.com/MegaMek/megamek/files/5066798/megameklog20200813-0304.zip)

**Comment by gsparks3** [comment]
Just got a similar lockup/exception: 

```
Exception in thread "Princess-precognition (Lyran Commonwealth)" java.lang.IllegalArgumentException: Entity invalid. ID 82
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:491)
	at megamek.common.MovePath.addStep(MovePath.java:497)
	at megamek.common.MovePath.addStep(MovePath.java:267)
	at megamek.common.MovePath.addStep(MovePath.java:179)
	at megamek.common.BulldozerMovePath.addStep(BulldozerMovePath.java:80)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:86)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:55)
	at megamek.client.bot.princess.PathEnumerator.updateLongRangePaths(PathEnumerator.java:380)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:317)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)
```
