### ISSUE TITLE
Princess seems to stop with an error when abandoning a vehicle

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#2150]
### Environment
What version of MegaMek does your issue apply to?  Latest Megamek Master branch (0.47.10-SNAPSHOT 553f6b6a13)
What operating system are you using?  Windows, Mac, or Linux? Linux (Fedora)
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file.
Java 11

### Description
Princess stops when some vehicles are abandoned.  This makes it hard to use the abandon when immobile option.
My test case uses hawk moth 2's with Inferno MMLs to maximize crit potential

The relevant error in the log seems to be:
`Ejecting crew size: 3
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at megamek.client.Client.getTargetImage(Client.java:1192)
        at megamek.client.Client.cacheImgTag(Client.java:1167)
        at megamek.client.Client.receiveEntityRemove(Client.java:993)
        at megamek.client.Client.handlePacket(Client.java:1322)
        at megamek.client.bot.princess.Princess.handlePacket(Princess.java:2014)
        at megamek.client.Client$1$2.run(Client.java:192)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue`

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/5079961/megameklog.txt)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/5079962/autosave.sav.gz)

**Comment by NickAragua** [comment]
Looks like a problem with PR #2135  @Krashner

**Comment by Krashner** [comment]
I'll take a look at it today.

**Comment by Windchild292** [comment]
Fixed in #2156
