### ISSUE TITLE
0.47.9: Princess Error

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#2160]
Attached are the customs, MHQ campaign file and MM file. When loading the MM game, after the crippled units eject the error happens and the match won't progress.

Ejecting crew size: 1
Ejecting crew size: 1
Exception in thread "Princess-precognition (Federated Suns)" java.lang.IllegalArgumentException: Entity invalid. ID 37
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:491)
	at megamek.common.MovePath.addStep(MovePath.java:497)
	at megamek.common.MovePath.addStep(MovePath.java:267)
	at megamek.common.MovePath.addStep(MovePath.java:179)
	at megamek.common.BulldozerMovePath.addStep(BulldozerMovePath.java:80)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:86)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:55)
	at megamek.client.bot.princess.PathEnumerator.updateLongRangePaths(PathEnumerator.java:380)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:317)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)

[bug.zip](https://github.com/MegaMek/megamek/files/5092407/bug.zip)

**Comment by NickAragua** [comment]
Probably fixed (in band-aid fashion) by #2148.
