### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2190]
From Casual Jokers stream testing 47.10 Snapshot. Can't say what the cause is but posting per @sixlettervariables 

### Environment
What version of MegaMek does your issue apply to?  Megamek from MekHQ
What operating system are you using?  Windows

### Description
```
Loading atlas: data\images\units\wrecks\wrecks_atlas.png
Exception in thread "AWT-EventQueue-0" java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.AbstractStringBuilder.substring(Unknown Source)
	at java.lang.StringBuffer.substring(Unknown Source)
	at megamek.common.Report.getText(Report.java:492)
	at megamek.client.Client.receiveReport(Client.java:1112)
	at megamek.client.Client.handlePacket(Client.java:1386)
	at megamek.client.Client$1$2.run(Client.java:192)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

### Files
[mekhqlog CJ.txt](https://github.com/MegaMek/megamek/files/5147964/mekhqlog.CJ.txt)
[megameklog CJ.txt](https://github.com/MegaMek/megamek/files/5147965/megameklog.CJ.txt)

Versions of MekHQ used based off these versions
https://www.dropbox.com/sh/8wqq067dtuy0ml1/AAAP83QHHM5Dk1YRsajCMbLDa?dl=0

**Comment by Windchild292** [comment]
Closing a likely fixed in #2202, but will reopen if this is found to not be the case.
