### ISSUE TITLE
RasterFormatException: y lies outside raster

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2215]
Playing around with SNAPSHOT built Sept 11th.

### Environment
What version of MegaMek does your issue apply to?  Megamek
What operating system are you using?  Windows, 

### Description
Load a game, grab a couple of mechs and change the map to Beginner Box Desert 1. 

Let the fun begin

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/5213400/megameklog.txt)

From the log
```
boardview1: loading images for board
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\saxarba\theme_mars\theme_mars_atlas.png
Loading atlas: data\images\hexes\hexes_atlas.png
Loading atlas: data\images\hexes\transparent\transparent_atlas.png
Loading atlas: data\images\hexes\transparent\transparent_atlas.png
Loading atlas: data\images\hexes\hexes_atlas.png
Loading atlas: data\images\hexes\hexes_atlas.png
Loading atlas: data\images\hexes\hexes_atlas.png
Exception in thread "AWT-EventQueue-0" java.awt.image.RasterFormatException: y lies outside raster
	at java.desktop/sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:460)
	at java.desktop/java.awt.image.BufferedImage.getSubimage(BufferedImage.java:1202)
	at megamek.client.ui.swing.boardview.BoardView1.paintComponent(BoardView1.java:1262)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedFPScales(RepaintManager.java:1707)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1616)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
```

**Comment by NickAragua** [comment]
Can't reproduce it with the current release. Is it still happening?

**Comment by HammerGS** [comment]
Just tested and I can't duplicate it. Must have been something specific to that moment.

**Comment by HammerGS** [comment]
Going to re-open with a save.
[Graphic.sav.gz](https://github.com/MegaMek/megamek/files/5289130/Graphic.sav.gz)

Player Name - Harriers

No customs.  

Graphically the Ribbon disappears and you have to hover over it to get the buttons to return, or min the play are and expand it.

**Comment by NickAragua** [comment]
This error happens when drawing the "board view background image". So it's got to be something to do with the skin, maybe something missing from the atlas.
