### ISSUE TITLE
Premature End of File Error when attempting to load unit list on Megamek (also is an issue for MekHQ)

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/megamek#2282]
0.47.10

When attempting to load this file for a MegaMek game for a custom scenario, the list does not load.  Based on the log that was obtained, a Fatal Error Premature End of File error was posted on the log, and shows as follows.

[Fatal Error] :1:1: Premature end of file.
Premature end of file.
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at megamek.common.MULParser.parse(MULParser.java:313)
	at megamek.common.EntityListFile.loadFrom(EntityListFile.java:1500)
	at megamek.client.ui.swing.ClientGUI.loadListFile(ClientGUI.java:1617)
	at megamek.client.ui.swing.ClientGUI.loadListFile(ClientGUI.java:1562)
	at megamek.client.ui.swing.ChatLounge.actionPerformed(ChatLounge.java:2765)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source
[Bugged MUL file.zip](https://github.com/MegaMek/megamek/files/5312811/Bugged.MUL.file.zip)

**Comment by Windchild292** [comment]
Did you modify any units in the lobby?

**Comment by Windchild292** [comment]
Empty mul file, likely due to the portrait issue fixed in the next release.

**Comment by CrimsonThunderSB** [comment]
as terms of the units themselves, I have modified edge, and special abilities of the pilots, as well as portraits, just stock units.

**Comment by Windchild292** [comment]
Issue with editing the unit in MegaMek, fixed in next release
