### ISSUE TITLE
0.47.10 - Sprites not displaying on combat outcome log

### ISSUE THREAD

**Issue by SimonLandmine** [MegaMek/megamek#2291]
0.47.10 standalone
Windows 10
Java 11.0.8

Sprites were not displaying on the combat outcome log. (Previously this was a Java issue on my machine, but have now updated Java from 8 to 11.) Display set to "true" in Advanced Settings tab.

(Also appeared to be an error displaying wreck sprites on main board for shredded Harassers, but those then showed up later. Don't know if that is connected.)

[megameklog.txt](https://github.com/MegaMek/megamek/files/5320986/megameklog.txt)

[20201003-0401.sav.gz](https://github.com/MegaMek/megamek/files/5320987/20201003-0401.sav.gz)
Player name: SimonLandmine
Bots are named for the assigned behaviour (e.g. St = Striker).

**Comment by HammerGS** [comment]
Seems to be lots of these in the log. 

`
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.base/java.io.Writer.write(Writer.java:249)
	at megamek.common.EntityListFile.writePilotAttributes(EntityListFile.java:1231)
	at megamek.common.EntityListFile.writeEntityList(EntityListFile.java:876)
	at megamek.common.EntityListFile.saveTo(EntityListFile.java:523)
	at megamek.client.ui.swing.ClientGUI.saveListFile(ClientGUI.java:1738)
	at megamek.client.ui.swing.ChatLounge.actionPerformed(ChatLounge.java:2775)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/`

**Comment by SimonLandmine** [comment]
(Yeah, I did a quick CTRL+F on "Exception", and did wonder if they were related.)

**Comment by Windchild292** [comment]
They are not likely to be related, as that is the portrait issue Juliez fixed.

**Comment by SimonLandmine** [comment]
And that would be (among the reasons) why I'm not a dev. :-)

**Comment by SimonLandmine** [comment]
That's weird ... continuing the same battle, and a sprite has just appeared on the log ... but only one (next to "Ammo explosion damages nearby units")

![image](https://user-images.githubusercontent.com/26851644/95003883-1ba9f800-05dc-11eb-923d-28b9fb6985fe.png)

[megameklog.txt](https://github.com/MegaMek/megamek/files/5322448/megameklog.txt)

**Comment by Windchild292** [comment]
Not likely the cause, but it looks like there might be an issue for Wreck Sprites:

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ui.swing.boardview.AbstractWreckSprite.prepare(AbstractWreckSprite.java:79)
	at megamek.client.ui.swing.boardview.BoardView1.preferenceChange(BoardView1.java:1115)
	at megamek.common.preference.PreferenceStore.firePropertyChangeEvent(PreferenceStore.java:284)
	at megamek.common.preference.PreferenceStore.setValue(PreferenceStore.java:223)
	at megamek.common.preference.PreferenceStoreProxy.setValue(PreferenceStoreProxy.java:98)
	at megamek.client.ui.swing.boardview.BoardView1$12.performAction(BoardView1.java:1021)
	at megamek.client.ui.swing.util.MegaMekController.dispatchKeyEvent(MegaMekController.java:140)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1133)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4892)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by Windchild292** [comment]
@NickAragua (forgot to tag)

**Comment by SimonLandmine** [comment]
Oddly, the sprites have shown up (very nicely) on the _Victory!_ screen. All present and correct. (Even if it does remind me that my _Marauder_ was technically killed by a _Vedette_ - even if it was a kill-steal from a _Grasshopper_.)

**Comment by servo01** [comment]
I'm having the same issue with sprites not appearing, either in the round report or on the victory screen. Issue was present for  both 47.10 and now with 47.11

I just tried a quick test battle with a clean install of 47.11 and the sprites were shown during the round report, but are gone once I load my saved MegaMek ruleset.

**Comment by HammerGS** [comment]
> I'm having the same issue with sprites not appearing, either in the round report or on the victory screen. Issue was present for both 47.10 and now with 47.11
> 
> I just tried a quick test battle with a clean install of 47.11 and the sprites were shown during the round report, but are gone once I load my saved MegaMek ruleset.

What version of Java?

**Comment by servo01** [comment]
11.0.8

**Comment by servo01** [comment]
I was able to isolate the issue: 
Using a clean install of 47.11 (no alterations or changes to the boot-up rules)

Turning on: TacOps Double Blind causes the sprites to disappear from the round report.

**Comment by SimonLandmine** [comment]
Yep, l was using Double Blind - so it looks like there's something about DB that hides the sprites from the Round Report as well ...

**Comment by SimonLandmine** [comment]
Quick test on 0.47.13 standalone - sprites shown on reports when 'Double Blind' is switched off, but disappear from reports when 'Double Blind' is on.

**Comment by SimonLandmine** [comment]
Issue still extant for Double Blind play in standalone 0.47.15.
(Oddly, if you reload a saved game, the sprites show up in the reports for previous turns - they're just not generated during play!)

**Comment by kuronekochomusuke** [comment]
corrected by #4383
