### ISSUE TITLE
NPE in do NuclearExplosion and setTurnIndex.  Plus other stuff in the log.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2537]
Watching the Casual Joker game last night they had a hard crash. From the log.  This is the stream from a couple of minutes before the crash - https://www.twitch.tv/videos/851044772?t=3h21m10s

It would match up to the 23:34 time stamps in the logs.

```
21:06:46,854 INFO [megamek.server.Server] {Connection 2} 
disconnected(), line 1121 : s: removed player Krrast "First Casualty"
Contents of Send Queue: 
s:Contents of Send Queue: 
java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.write(Unknown Source)
	at java.io.DataOutputStream.write(Unknown Source)
	at java.io.FilterOutputStream.write(Unknown Source)
	at megamek.common.net.DataStreamConnection.sendNetworkPacket(DataStreamConnection.java:114)
	at megamek.common.net.AbstractConnection.sendNow(AbstractConnection.java:281)
	at megamek.common.net.AbstractConnection.processPacket(AbstractConnection.java:517)
	at megamek.common.net.AbstractConnection.flush(AbstractConnection.java:480)
	at megamek.common.net.DataStreamConnection.flush(DataStreamConnection.java:124)
	at megamek.common.net.AbstractConnection.send(AbstractConnection.java:273)
	at megamek.server.Server.send(Server.java:31178)
	at megamek.server.Server.sendSaveGame(Server.java:1217)
	at megamek.server.commands.LocalSaveGameCommand.run(LocalSaveGameCommand.java:59)
	at megamek.server.Server.processCommand(Server.java:31212)
	at megamek.server.Server.handle(Server.java:31292)
	at megamek.server.Server$1.packetReceived(Server.java:397)
	at megamek.common.net.AbstractConnection.processConnectionEvent(AbstractConnection.java:603)
	at megamek.common.net.AbstractConnection.processPacket(AbstractConnection.java:508)
	at megamek.common.net.AbstractConnection.update(AbstractConnection.java:453)
	at megamek.server.ConnectionHandler.run(ConnectionHandler.java:49)

```

Later on.
```
23:34:15,944 INFO [megamek.server.Server] {Packet Pump} 
prepareForPhase(), line 2290 : Round 11 memory usage: 646,536 kB
Time to prepare the shadow map: 36.7311 ms
Loading atlas: data\images\hexes\saxarba\misc\misc_atlas.png
Time to prepare the shadow map: 88.8065 ms
Loading atlas: data\images\units\defaults\defaults_atlas.png
Loading atlas: data\images\units\wrecks\wrecks_atlas.png
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.server.Server.doNuclearExplosion(Server.java:24427)
	at megamek.server.Server.doNuclearExplosion(Server.java:24253)
	at megamek.common.weapons.ArtilleryWeaponIndirectFireHandler.handle(ArtilleryWeaponIndirectFireHandler.java:352)
	at megamek.server.Server.handleAttacks(Server.java:35454)
	at megamek.server.Server.handleAttacks(Server.java:35383)
	at megamek.server.Server.endCurrentPhase(Server.java:2940)
	at megamek.server.Server.changePhase(Server.java:2229)
	at megamek.server.Server.endCurrentPhase(Server.java:2850)
	at megamek.server.Server.checkReady(Server.java:2012)
	at megamek.server.Server.handle(Server.java:31280)
	at megamek.server.Server$PacketPump.run(Server.java:254)
```

Then later on.
```
23:39:10,584 INFO [megamek.client.ui.swing.tileset.TilesetManager] {AWT-EventQueue-0} 
getFromCache(), line 363 : Loading image on the fly: Pilot Harry Balsonya
Loading atlas: data\images\units\wrecks\wrecks_atlas.png
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.common.Game.setTurnIndex(Game.java:751)
	at megamek.client.Client.changeTurnIndex(Client.java:539)
	at megamek.client.Client.handlePacket(Client.java:1372)
	at megamek.client.Client$1$2.run(Client.java:193)

```
### Environment
What version of MegaMek does your issue apply to?  47.15
What operating system are you using?  Windows
What java version are you using?  Java 8

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.
(Delete the above lines)

### Files
[1st CJ twitch.sav.gz](https://github.com/MegaMek/megamek/files/5744806/1st.CJ.twitch.sav.gz)
[2nd CJ twitch.sav.gz](https://github.com/MegaMek/megamek/files/5744807/2nd.CJ.twitch.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/5744808/megameklog.txt)
[gamelog.zip](https://github.com/MegaMek/megamek/files/5744809/gamelog.zip)

**Comment by NickAragua** [comment]
How did the nuke happen exactly?
