### ISSUE TITLE
Princess AI cant deploy or move units in custom map.

### ISSUE THREAD

**Issue by BiggestBoss1** [MegaMek/megamek#2609]
[Stand alone megamek dev version 47.16, Windows 64bit ,Java version 1.8.0_271, player name BiggestBoss]

On a custom lunar tileset 40x40 map i have experianced an issue with the princess ai not deploying units except turrets on building and wall tiles.
I then tried connecting as the second player myself and deployed by hand,then disconnected and replaced my second instance of the game with the ai in hopes that it was just a deploy issue but then it turned out that even with the units deployed the ai would not make any moves.I will provide the megameklog document as well as the map and save in hopes that the issue can be found.

[bug log.txt](https://github.com/MegaMek/megamek/files/5888809/bug.log.txt)
[bug.sav.gz](https://github.com/MegaMek/megamek/files/5888813/bug.sav.gz)
[Lunar port base.zip](https://github.com/MegaMek/megamek/files/5888832/Lunar.port.base.zip)

**Comment by sixlettervariables** [comment]
Exception from log:
```
18:05:47,107 ERROR [megamek.client.bot.BotClient] {Princess Turn 0 Calc Thread} 
calculateMyTurnWorker(), line 591 : null
java.lang.NullPointerException
	at megamek.common.pathfinder.BoardClusterTracker.buildingPlowThroughRequired(BoardClusterTracker.java:368)
	at megamek.common.pathfinder.BoardClusterTracker.generateClusters(BoardClusterTracker.java:272)
	at megamek.common.pathfinder.BoardClusterTracker.updateMovableAreas(BoardClusterTracker.java:221)
	at 
```

**Comment by Windchild292** [comment]
```
18:05:44,554 ERROR [megamek.client.bot.BotClient] {Princess Turn 0 Calc Thread} 
calculateMyTurnWorker(), line 591 : null
java.lang.NullPointerException
	at megamek.common.pathfinder.BoardClusterTracker.buildingPlowThroughRequired(BoardClusterTracker.java:368)
	at megamek.common.pathfinder.BoardClusterTracker.generateClusters(BoardClusterTracker.java:272)
	at megamek.common.pathfinder.BoardClusterTracker.updateMovableAreas(BoardClusterTracker.java:221)
	at megamek.common.pathfinder.BoardClusterTracker.getDestinationCoords(BoardClusterTracker.java:170)
	at megamek.client.bot.BotClient.calculateEdgeAccessFitness(BotClient.java:966)
	at megamek.client.bot.BotClient.getStartingCoordsArray(BotClient.java:924)
	at megamek.client.bot.princess.Princess.calculateDeployment(Princess.java:458)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:571)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:516)
	at megamek.client.bot.BotClient.access$000(BotClient.java:85)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:109)
	at java.lang.Thread.run(Unknown Source)
```
