### ISSUE TITLE
47.16 Odd NPE freeze?

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2687]
### Environment
Standalone Megamek 47.16
Java 11.0.10

### Description
Not quite sure what happened, but during a multiplayer MM game my client (which was hosting) locked up. Log file showed an odd error; log is attached below. Save file from another player (who was able to manually save while my client was frozen) is also provided, although I'm not sure if it will help - loading from the save fixed the error. 

### Files
[fug.sav.gz](https://github.com/MegaMek/megamek/files/6055879/fug.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/6055877/megameklog.txt)

**Comment by HammerGS** [comment]
```
java.io.FileNotFoundException: savegames\2\27.sav.gz (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:126)
	at megamek.server.Server.saveGame(Server.java:1263)
	at megamek.server.Server.saveGame(Server.java:1283)
	at megamek.server.commands.SaveGameCommand.run(SaveGameCommand.java:47)
	at megamek.server.Server.processCommand(Server.java:31225)
	at megamek.server.Server.handle(Server.java:31305)
	at megamek.server.Server$1.packetReceived(Server.java:397)
	at megamek.common.net.AbstractConnection.processConnectionEvent(AbstractConnection.java:603)
	at megamek.common.net.AbstractConnection.processPacket(AbstractConnection.java:508)
	at megamek.common.net.AbstractConnection.update(AbstractConnection.java:453)
	at megamek.server.ConnectionHandler.run(ConnectionHandler.java:49)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
