### ISSUE TITLE
Skipped firing Phase

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#2719]
During Casual Jokers Stream the game skipped the firing phase. You can see it in the stream. The save is from after the skipped phase. They have had this in the past.

### Environment
What version of MegaMek does your issue apply to?  0.48.0
What operating system are you using?  Windows
What java version are you using?  Java version 1.8.0_261

### Description
See stream here - https://www.twitch.tv/videos/948556859?t=3h45m1s

### Files
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/6137511/mekhqlog.txt)
[megameklog (2).txt](https://github.com/MegaMek/megamek/files/6137512/megameklog.2.txt)
[hammer.sav.gz](https://github.com/MegaMek/megamek/files/6137513/hammer.sav.gz)

**Comment by HammerGS** [comment]
From the Log

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.bot.princess.Princess.calcAmmoConservation(Princess.java:760)
	at megamek.client.bot.princess.Princess.calculatePointBlankShot(Princess.java:825)
	at megamek.client.bot.BotClient$1.gameClientFeedbackRequest(BotClient.java:201)
	at megamek.common.event.GameCFREvent.fireEvent(GameCFREvent.java:92)
	at megamek.common.Game.processGameEvent(Game.java:3164)
	at megamek.client.Client.handlePacket(Client.java:1534)
	at megamek.client.bot.princess.Princess.handlePacket(Princess.java:1909)
	at megamek.client.Client$1$2.run(Client.java:193)
```

I think around the same time these errors started appearing.
```
22:50:07,785 INFO [megamek.server.Server] {Packet Pump} 
prepareForPhase(), line 2297 : Round 2 memory usage: 1,692,618 kB

22:51:51,472 ERROR [megamek.server.Server] {Packet Pump} 
processPointblankShotCFR(), line 9881 : Expected a COMMAND_CFR_HIDDEN_PBS CFR packet from player  11 but instead it came from player 12

22:51:51,472 ERROR [megamek.server.Server] {Packet Pump} 
processPointblankShotCFR(), line 9881 : Expected a COMMAND_CFR_HIDDEN_PBS CFR packet from player  11 but instead it came from player 3

22:51:51,472 ERROR [megamek.server.Server] {Packet Pump} 
processPointblankShotCFR(), line 9881 : Expected a COMMAND_CFR_HIDDEN_PBS CFR packet from player  11 but instead it came from player 2

22:51:51,472 ERROR [megamek.server.Server] {Packet Pump} 
processPointblankShotCFR(), line 9881 : Expected a COMMAND_CFR_HIDDEN_PBS CFR packet from player  11 but instead it came from player 1

22:57:51,030 INFO [megamek.server.Server] {Packet Pump} 
prepareForPhase(), line 2297 : Round 3 memory usage: 2,035,450 kB

23:00:19,897 ERROR [megamek.server.Server] {Packet Pump} 
processPointblankShotCFR(), line 9881 : Expected a COMMAND_CFR_HIDDEN_PBS CFR packet from player  11 but instead it came from player 12

23:00:19,897 ERROR [megamek.server.Server] {Packet Pump} 
processPointblankShotCFR(), line 9881 : Expected a COMMAND_CFR_HIDDEN_PBS CFR packet from player  11 but instead it came from player 3

23:00:19,897 ERROR [megamek.server.Server] {Packet Pump} 
processPointblankShotCFR(), line 9881 : Expected a COMMAND_CFR_HIDDEN_PBS CFR packet from player  11 but instead it came from player 2

23:00:19,897
 ERROR [megamek.server.Server] {Packet Pump} 
processPointblankShotCFR(), line 9881 : Expected a COMMAND_CFR_HIDDEN_PBS CFR packet from player  11 but instead it came from player 1
```
