### ISSUE TITLE
Weird hangup bug encountered during play

### ISSUE THREAD

**Issue by K007** [MegaMek/megamek#2851]
MegaMek HQ branch on .49

Melee phase hanged up as shown in image after hitting done for a unit that couldn't engage anything and then it locked its self into the shown state
![image](https://user-images.githubusercontent.com/8080619/117683105-50bba000-b1e6-11eb-8df9-e6f974ff07b4.png)

.sav and logfile
[megameklog.txt](https://github.com/MegaMek/megamek/files/6453168/megameklog.txt)
[savegame.sav.gz](https://github.com/MegaMek/megamek/files/6453169/savegame.sav.gz)

**Comment by HammerGS** [comment]
Just to confirm you tried a DFA?

This in the logs
23:03:55,512 ERROR [megamek.server.Server] {Packet Pump} 
processMovement(), line 7511 : Illegal DFA by Vulcan VL-2T (Maru Rangers) against non-existent entity at null

**Comment by lunaticpathos** [comment]
I'm having the same or similar issue in 0.48.0. I've now had two games lock up after declaring physical attacks instead of resolving them. The issue persists when reloading, or reloading the autosave and playing back up to the same physical attack phase
[TPSakhalinBugged2.sav.gz](https:
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/7296521/autosave.sav.gz)
//github.com/MegaMek/megamek/files/7296517/TPSakhalinBugged2.sav.gz)
.
Here's the bottom of my log:Loading atlas: data\images\units\wrecks\bottomdecals\bottomdecals_atlas.png
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.common.Entity.getBadCriticals(Entity.java:4726)
	at megamek.common.actions.ClubAttackAction.toHit(ClubAttackAction.java:426)
	at megamek.common.actions.ClubAttackAction.toHit(ClubAttackAction.java:252)
	at megamek.server.Server.preTreatPhysicalAttack(Server.java:33177)
	at megamek.server.Server.resolvePhysicalAttacks(Server.java:15209)
	at megamek.server.Server.endCurrentPhase(Server.java:2893)
	at megamek.server.Server.changeToNextTurn(Server.java:3202)
	at megamek.server.Server.endCurrentTurn(Server.java:2212)
	at megamek.server.Server.receiveAttack(Server.java:13429)
	at megamek.server.Server.handle(Server.java:31381)
	at megamek.server.Server$PacketPump.run(Server.java:254)

**Comment by kuronekochomusuke** [comment]
this may be fixed by #3964
