### ISSUE TITLE
Blank Phase Reports 0.49.0

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#2859]
![image](https://user-images.githubusercontent.com/18338059/118208897-902bfb80-b435-11eb-8ab2-a27b11ee0899.png)

This is an ATB game through MekHQ, using artillery, structures, and turrets.  Oracle Java version 15.0.2.  Text started appearing at the conclusion of the 2nd turn.

[megameklog.txt](https://github.com/MegaMek/megamek/files/6476335/megameklog.txt)

**Comment by HammerGS** [comment]
Do you have a save game and cpnx files for this?



One of the Errors 

```
21:43:10,488 ERROR [megamek.client.bot.BotClient] {Outworlds Alliance Primary Opfor Turn 1 Calc Thread} 
calculateMyTurnWorker(), line 591 : null
java.util.ConcurrentModificationException
	at java.base/java.util.Vector$Itr.checkForComodification(Vector.java:1292)
	at java.base/java.util.Vector$Itr.next(Vector.java:1248)
	at megamek.common.EquipmentType.hasModeType(EquipmentType.java:549)
	at megamek.client.bot.princess.FireControl.entityCanIndirectFireMissile(FireControl.java:2280)
	at megamek.client.bot.princess.Princess.initFiringEntities(Princess.java:995)
	at megamek.client.bot.princess.Princess.getEntityToFire(Princess.java:967)
	at megamek.client.bot.princess.Princess.calculateFiringTurn(Princess.java:631)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:559)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:516)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:109)
```

```
22:03:04,337 ERROR [megamek.common.Game] {Federated Suns Allied Force Turn 0 Calc Thread} 
getTarget(), line 1245 : The coordinates, 1614, do not contain a building.
java.lang.IllegalArgumentException: The coordinates, 1614, do not contain a building.
	at megamek.common.BuildingTarget.init(BuildingTarget.java:86)
	at megamek.common.BuildingTarget.<init>(BuildingTarget.java:138)
	at megamek.common.Game.getTarget(Game.java:1236)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:296)
	at megamek.client.bot.princess.WeaponFireInfo.calcRealToHit(WeaponFireInfo.java:287)
	at megamek.client.bot.princess.WeaponFireInfo.initDamage(WeaponFireInfo.java:518)
	at megamek.client.bot.princess.WeaponFireInfo.<init>(WeaponFireInfo.java:179)
	at megamek.client.bot.princess.WeaponFireInfo.<init>(WeaponFireInfo.java:91)
	at megamek.client.bot.princess.FireControl.buildWeaponFireInfo(FireControl.java:1587)
	at megamek.client.bot.princess.FireControl.getFullFiringPlan(FireControl.java:1857)
	at megamek.client.bot.princess.FireControl.getBestFiringPlan(FireControl.java:2075)
	at megamek.client.bot.princess.FireControl.determineBestFiringPlan(FireControl.java:2210)
	at megamek.client.bot.princess.FireControl.getBestFiringPlan(FireControl.java:2442)
	at megamek.client.bot.princess.Princess.calculateFiringTurn(Princess.java:671)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:559)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:516)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:109)
```
```
22:03:04,339 ERROR [megamek.client.bot.BotClient] {Federated Suns Allied Force Turn 0 Calc Thread} 
calculateMyTurnWorker(), line 591 : Cannot invoke "megamek.common.Targetable.getTargetType()" because "target" is null
java.lang.NullPointerException: Cannot invoke "megamek.common.Targetable.getTargetType()" because "target" is null
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:354)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:296)
	at megamek.client.bot.princess.WeaponFireInfo.calcRealToHit(WeaponFireInfo.java:287)
	at megamek.client.bot.princess.WeaponFireInfo.initDamage(WeaponFireInfo.java:518)
	at megamek.client.bot.princess.WeaponFireInfo.<init>(WeaponFireInfo.java:179)
	at megamek.client.bot.princess.WeaponFireInfo.<init>(WeaponFireInfo.java:91)
	at megamek.client.bot.princess.FireControl.buildWeaponFireInfo(FireControl.java:1587)
	at megamek.client.bot.princess.FireControl.getFullFiringPlan(FireControl.java:1857)
	at megamek.client.bot.princess.FireControl.getBestFiringPlan(FireControl.java:2075)
	at megamek.client.bot.princess.FireControl.determineBestFiringPlan(FireControl.java:2210)
	at megamek.client.bot.princess.FireControl.getBestFiringPlan(FireControl.java:2442)
	at megamek.client.bot.princess.Princess.calculateFiringTurn(Princess.java:671)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:559)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:516)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:109)
```
The two above are repeated along with lots of these:

```
22:05:56,080 ERROR [megamek.common.Board] {AWT-EventQueue-0} 
updateBuildings(), line 1548 : Could not find a match for Hardened Standard Building #150013 to update.

```
```

22:45:39,205 ERROR [megamek.client.ui.swing.boardview.BoardView1] {AWT-EventQueue-0} 
paintComponent(), line 1253 : Error drawing background image. Raster Bounds: 0.00, 0.00, width:447.00, height:447.00, Attempted Draw Coordinates: 158, -1, width:289, height:448
```

Plus a few Stratcon ones:

```
23:21:19,681 ERROR [mekhq.campaign.stratcon.StratconRulesManager] {AWT-EventQueue-0} 
applyGlobalModifiers(), line 647 : Modifier OverwhelmingReinforcementsGround.xml not found; ignoring
```

**Comment by BLR-IIC** [comment]
The campaign file was overwritten at the completion of the mission, as were the savegames.  I'll see if I can reproduce it.

**Comment by NickAragua** [comment]
The errors in the log are all bot errors (other than the raster thing which doesn't actually do anything and the reinforcements thing which is a minor MekHQ issue), and so they shouldn't impact turn reporting or anything like that - they'll just make the specific bot that encountered them crash, which should be repairable by kicking/replacing it. So there's probably something else going on there.

**Comment by BLR-IIC** [comment]
I haven't encountered this bug at all in my extensive play of 0.50.10, so I think it was probably resolved at some point.
