### ISSUE TITLE
48.0 NPE on designating a hex with TAG for incoming Homing Arrow IV

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2920]
### Environment
Standalone Megamek 48.0
Windows 10
Java 11.0.10

### Description
During a campaign game, we encountered a game-stall-inducing NPE on designating a hex with TAG with an incoming Homing Arrow IV round. Log files and a save that allows reproduction are provided.

Steps to reproduce:
1. Start the saved game as player "sprero"
2. Target a ground hex within 8 hexes of the nearby marker for the incoming Homing AIV round and hit "Done".
3. Observe the game stall and NPE in the log.

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/6612160/megameklog.txt)
[homingAIVtagCrash.sav.gz](https://github.com/MegaMek/megamek/files/6612161/homingAIVtagCrash.sav.gz)

**Comment by HammerGS** [comment]
`megamek.common.HexTarget cannot be cast to class megamek.common.Entity (megamek.common.HexTarget and megamek.common.Entity are in unnamed module of loader 'app')
	at megamek.common.weapons.WeaponHandler.calcCounterAV(WeaponHandler.java:249)
	at megamek.common.weapons.ArtilleryWeaponIndirectHomingHandler.handleAMS(ArtilleryWeaponIndirectHomingHandler.java:472)
	at megamek.common.weapons.ArtilleryWeaponIndirectHomingHandler.handle(ArtilleryWeaponIndirectHomingHandler.java:207)
	at megamek.server.Server.handleAttacks(Server.java:35528)
	at megamek.server.Server.handleAttacks(Server.java:35457)
	at megamek.server.Server.endCurrentPhase(Server.java:2947)
	at megamek.server.Server.changeToNextTurn(Server.java:3202)
	at megamek.server.Server.endCurrentTurn(Server.java:2212)
	at megamek.server.Server.receiveAttack(Server.java:13429)
	at megamek.server.Server.handle(Server.java:31381)
	at megamek.server.Server$PacketPump.run(Server.java:254)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by sixlettervariables** [comment]
It looks like we might could just exclude non-entities here:
https://github.com/MegaMek/megamek/blob/1dba1857840ca38b176ae747f360c46cf09634de/megamek/src/megamek/common/weapons/WeaponHandler.java#L242-L249

Not familiar enough with that code block to suggest it though.

**Comment by sixlettervariables** [comment]
Proximate cause is the base `checkPDConditions` excludes non-entities, but `ArtilleryWeaponIndirectHomingHandler` overrides and does not:
https://github.com/MegaMek/megamek/blob/1dba1857840ca38b176ae747f360c46cf09634de/megamek/src/megamek/common/weapons/ArtilleryWeaponIndirectHomingHandler.java#L424-L434
