### ISSUE TITLE
Loading units onto dropship in the lobby causes problems 0.49.1

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#2947]
Oracle JDK 15.0.2
Windows 10 64-bit

I used the force generator to add an aerospace wing as an opfor for my game.  The wing included a Triumph dropship.  When I tried to load three 13-ton mechanized bridge infantry platoon onto the dropship, the game threw an error seen in the attached log.  Subsequently, I couldn't unload the platoon from the dropship, or load Manticore tanks onto the dropship.  I also couldn't delete any of the platoons from the unit list even though the lobby gave me a confirmation prompt that I wanted to delete them and I confirmed it.
[megameklog.zip](https://github.com/MegaMek/megamek/files/6666798/megameklog.zip)

**Comment by Windchild292** [comment]
```
Exception in thread "Packet Pump" java.lang.IllegalArgumentException: Triumph (2593) can not load Mechanized Tracked Platoon (Bridging) #2
	at megamek.common.Entity.load(Entity.java:8173)
	at megamek.common.Entity.load(Entity.java:8177)
	at megamek.server.Server.loadUnit(Server.java:4126)
	at megamek.server.Server.receiveEntityLoad(Server.java:30138)
	at megamek.server.Server.handle(Server.java:31371)
	at megamek.server.Server$PacketPump.run(Server.java:183)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by NickAragua** [comment]
Looks like there's some logic issues with loading "heavier" infantry into foot platoon infantry bays.

**Comment by SJuliez** [comment]
Unable to reproduce this issue. I could load a 12t bridging unit onto the Triumph.
