### ISSUE TITLE
48.0 "Done" button grayed out during firing phase despite not being done firing - NPE(s) in log

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2984]
### Environment
48.0 standalone Megamek
Windows 10
Java 11.0.10

### Description
Error as in title - Done button becomes grayed out during firing phase, despite unit not actually being done firing, with a NPE found in the log. Possibly related to sensors in space map battle?

### Files
Log: 
[megameklog.txt](https://github.com/MegaMek/megamek/files/6745296/megameklog.txt)
Post-bug save (reproduces bugged state, at least on my machine):
[firingPhasePostNPE.sav.gz](https://github.com/MegaMek/megamek/files/6745303/firingPhasePostNPE.sav.gz)
Playername: Mishra

**Comment by HammerGS** [comment]
From the log

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ui.swing.unitDisplay.ExtraPanel.refreshSensorChoices(ExtraPanel.java:648)
	at megamek.client.ui.swing.unitDisplay.ExtraPanel.displayMech(ExtraPanel.java:615)
	at megamek.client.ui.swing.unitDisplay.UnitDisplay.displayEntity(UnitDisplay.java:316)
	at megamek.client.ui.swing.MovementDisplay.selectEntity(MovementDisplay.java:776)
	at megamek.client.ui.swing.MovementDisplay.beginMyTurn(MovementDisplay.java:1014)
	at megamek.client.ui.swing.MovementDisplay.gameTurnChange(MovementDisplay.java:4381)
	at megamek.common.event.GameTurnChangeEvent.fireEvent(GameTurnChangeEvent.java:51)
	at megamek.common.Game.processGameEvent(Game.java:3164)
	at megamek.common.Game.setTurnIndex(Game.java:750)
	at megamek.client.Client.changeTurnIndex(Client.java:539)
	at megamek.client.Client.handlePacket(Client.java:1365)
	at megamek.client.Client$1$2.run(Client.java:193)
```
