### ISSUE TITLE
48.0 NPE, possibly related to space map squadrons and sensor rules?

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#2988]
### Description
Game reproducibly NPE's and stalls at the beginning of a phase in a large space-map game involving fighter squadrons, dropships, and warships. NPE log text implies it is related to squadrons and sensor rules? Restarting the game with SO Advanced Sensors and TO Sensor Rules disabled seemed to allow the game to progress normally. Note that TO Double Blind was already disabled when the bug was observed - technically I think this means that neither of the rules mentioned above should actually be used? Needs further investigation.

Reproduction steps:
1. Load the provided savegame, joining as "CJF Naval Star"
2. Hit "Done" and observe the game stall/NPE in the logs.

```
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.common.FighterSquadron.updateSensors(FighterSquadron.java:387)
	at megamek.common.FighterSquadron.newRound(FighterSquadron.java:368)
	at megamek.server.Server.resetEntityRound(Server.java:1506)
	at megamek.server.Server.prepareForPhase(Server.java:2266)
	at megamek.server.Server.changePhase(Server.java:2227)
	at megamek.server.Server.endCurrentPhase(Server.java:2801)
	at megamek.server.Server.changeToNextTurn(Server.java:3202)
	at megamek.server.Server.executePhase(Server.java:2642)
	at megamek.server.Server.changePhase(Server.java:2234)
	at megamek.server.Server.endCurrentPhase(Server.java:2823)
	at megamek.server.Server.checkReady(Server.java:2019)
	at megamek.server.Server.handle(Server.java:31323)
	at megamek.server.Server$PacketPump.run(Server.java:254)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Files
[startGame2.sav.gz](https://github.com/MegaMek/megamek/files/6759044/startGame2.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/6759042/megameklog.txt)

**Comment by NickAragua** [comment]
Looks like there's a whole bunch of issues with fighter squadrons that'll require a pretty significant update to the relevant code.
