### ISSUE TITLE
MegaMek lock up at end of game at "Save salvage?" dialog

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/megamek#3004]
Once in a rare while, at the end of a game spawned from MekHQ the "Save salvage to file?" dialog comes up as normal but then disappears.  Its not behind the main screen, but it otherwise inaccessible.  It may be offscreen - I've seen that happen with several other programs, except in this case the old trick of ALT-SPACE/M/ARROW to grab the dialog only gets the MegaMek host window.  The list of surviving/killed/fled units is still present and can be scrolled.  The command line accepts commands, and the menus still function, except after a few tries both MegaMek and MekHQ locks up/won't accept any more input.

The "Done" button is disabled and cannot be used to advance to scenario resolution and return to MekHQ.  The only option is to force-quit the Java application through Task Manager (this is using Win 10), which discards the results.

I've seen this happen back through 45.x series, up to now with 49.2.  It is difficult to replicate, as it happens at random.  It seems to happen more frequently if, when the "Save Salvage?" dialog pops up, "Yes" is selected or the MegaMek host window is clicked outside of the dialog, but that could be coincidence.

**Comment by HammerGS** [comment]
We would need logs to try and trouble shoot this.

**Comment by SuperStucco** [comment]
The logs don't seem to have anything obvious:

[megameklog.txt](https://github.com/MegaMek/megamek/files/6797448/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/6797450/mekhqlog.txt)

**Comment by Windchild292** [comment]
There's a bunch of exceptions in the MegaMekLog.txt file, albeit unrelated.
```
11:00:03,326 ERROR [megamek.common.actions.WeaponAttackAction] {Federated Commonwealth House Officer Turn 1 Calc Thread} 
toHit(), line 340 : 54Attempting to attack null target

11:00:03,326 ERROR [megamek.client.bot.BotClient] {Federated Commonwealth House Officer Turn 1 Calc Thread} 
calculateMyTurnWorker(), line 592 : null
java.lang.NullPointerException
	at megamek.common.Compute.getTargetTotalHP(Compute.java:2880)
	at megamek.client.bot.princess.FireControl.calcDamageAllocationUtility(FireControl.java:1402)
	at megamek.client.bot.princess.FireControl.calculateUtility(FireControl.java:1290)
	at megamek.client.bot.princess.FireControl.getFullFiringPlan(FireControl.java:1881)
	at megamek.client.bot.princess.FireControl.getBestFiringPlan(FireControl.java:2075)
	at megamek.client.bot.princess.FireControl.determineBestFiringPlan(FireControl.java:2210)
	at megamek.client.bot.princess.FireControl.getBestFiringPlan(FireControl.java:2439)
	at megamek.client.bot.princess.Princess.calculateFiringTurn(Princess.java:672)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:560)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:517)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:110)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
