### ISSUE TITLE
NPE in megamek.common.Entity.getLoadedTrailers and also megamek.common.weapons.infantry.InfantryWeapon.getCorrectHandler

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3052]
From Discord, player is have consistent crash. Logs show two different NPEs

### Environment
What operating system are you using?  Windows
What java version are you using?  Java 8

### Description
![image](https://user-images.githubusercontent.com/13752452/128380498-3941e2f7-3322-4cdf-8009-09c20003714d.png)

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.common.Entity.getLoadedTrailers(Entity.java:15818)
	at megamek.client.ui.swing.MovementDisplay.clear(MovementDisplay.java:1196)
	at megamek.client.ui.swing.MovementDisplay.selectEntity(MovementDisplay.java:768)
	at megamek.client.ui.swing.MovementDisplay.beginMyTurn(MovementDisplay.java:1014)
	at megamek.client.ui.swing.MovementDisplay.gameTurnChange(MovementDisplay.java:4381)
	at megamek.common.event.GameTurnChangeEvent.fireEvent(GameTurnChangeEvent.java:51)
	at megamek.common.Game.processGameEvent(Game.java:3164)
	at megamek.common.Game.setTurnIndex(Game.java:750)
	at megamek.client.Client.changeTurnIndex(Client.java:539)
	at megamek.client.Client.handlePacket(Client.java:1365)
	at megamek.client.Client$1$2.run(Client.java:193)
```
and

```
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.common.weapons.infantry.InfantryWeapon.getCorrectHandler(InfantryWeapon.java:256)
	at megamek.common.weapons.Weapon.fire(Weapon.java:103)
	at megamek.server.Server.resolveOnlyWeaponAttacks(Server.java:14522)
	at megamek.server.Server.endCurrentPhase(Server.java:2867)
	at megamek.server.Server.changeToNextTurn(Server.java:3202)
	at megamek.server.Server.endCurrentTurn(Server.java:2212)
	at megamek.server.Server.receiveAttack(Server.java:13429)
	at megamek.server.Server.handle(Server.java:31381)
	at megamek.server.Server$PacketPump.run(Server.java:254)
```

### Files
No Save game available but have asked player to provide. 

[megameklog.txt](https://github.com/MegaMek/megamek/files/6939957/megameklog.txt)

**Comment by HammerGS** [comment]
Adding some player provided info.
[New folder.zip](https://github.com/MegaMek/megamek/files/6940200/New.folder.zip)
