### ISSUE TITLE
ARRAY OOB error on civilian vehicle

### ISSUE THREAD

**Issue by Wunsche** [MegaMek/megamek#3065]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
49.2 HQ's MegaMek.
 Windows 10
Java version 11.0.10.
[CIV_ERROR.sav.gz](https://github.com/MegaMek/megamek/files/6951686/CIV_ERROR.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/6951687/megameklog.txt)

### Description
Out of bounds array error for civilian vehicles on a base defend mission

### Files
i have the save file at the turn it happened but not the turn before

Name I used on the game was 'STRATCON_MERC'

KG_Brandenburg

**Comment by HammerGS** [comment]
From the log

```
getTarget(), line 1246 : The coordinates, 3127, do not contain a building.
java.lang.IllegalArgumentException: The coordinates, 3127, do not contain a building.
	at megamek.common.BuildingTarget.init(BuildingTarget.java:86)
	at megamek.common.BuildingTarget.<init>(BuildingTarget.java:138)
	at megamek.common.Game.getTarget(Game.java:1237)
	at megamek.common.actions.SearchlightAttackAction.isPossible(SearchlightAttackAction.java:51)
	at megamek.common.actions.SearchlightAttackAction.willIlluminate(SearchlightAttackAction.java:176)
	at megamek.common.actions.AbstractAttackAction.nightModifiers(AbstractAttackAction.java:134)
	at megamek.common.actions.WeaponAttackAction.compileEnvironmentalToHitMods(WeaponAttackAction.java:2828)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:741)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:318)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:290)
	at megamek.client.ui.swing.boardview.AttackSprite.addWeapon(AttackSprite.java:260)
	at megamek.client.ui.swing.boardview.BoardView1.addAttack(BoardView1.java:4439)
	at megamek.client.ui.swing.boardview.BoardView1.refreshAttacks(BoardView1.java:4513)
	at megamek.client.ui.swing.boardview.BoardView1$16.gamePhaseChange(BoardView1.java:5344)
	at megamek.common.event.GamePhaseChangeEvent.fireEvent(GamePhaseChangeEvent.java:72)
	at megamek.common.Game.processGameEvent(Game.java:3169)
	at megamek.common.Game.setPhase(Game.java:824)
	at megamek.client.Client.changePhase(Client.java:426)
	at megamek.client.Client.handlePacket(Client.java:1488)
	at megamek.client.Client$1$2.run(Client.java:170)
```
