### ISSUE TITLE
48.0 NPE during post-movement indirect attack phase

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3156]
### Environment
Megamek 48.0
OpenJDK 11.0.10
Standalone Megamek

### Description
During a large multiplayer game, we encountered a NPE when attempting to move from the post-movement indirect attack phase to the firing phase. The cause is not 100% certain, but while the issue consistently reproduces when loading from an autosave at the beginning of said phase, we were able to avoid it by reloading from an earlier autosave (the beginning of the movement phase) and NOT having a vehicle crew abandon a vehicle that had made an indirect artillery attack that turn prior to the movement phase, so that may be related.

Reproduction steps:
1. Open the provided savegame. For ease of use, join as "The Bloody Revelation (WoB 18th Div)"
2. Hit Done on all TAG-equipped units. Use /skip to skip any remaining units. (Alternately, link a second client as "Soup" and similarly hit Done).
3. Observe the NPE in the logs.

```
java.lang.NullPointerException
	at megamek.common.weapons.ArtilleryWeaponIndirectFireHandler.handle(ArtilleryWeaponIndirectFireHandler.java:162)
	at megamek.server.Server.handleAttacks(Server.java:35528)
	at megamek.server.Server.handleAttacks(Server.java:35457)
	at megamek.server.Server.endCurrentPhase(Server.java:2947)
	at megamek.server.Server.changeToNextTurn(Server.java:3202)
	at megamek.server.Server.endCurrentTurn(Server.java:2212)
	at megamek.server.Server.skipCurrentTurn(Server.java:3280)
	at megamek.server.commands.SkipCommand.run(SkipCommand.java:53)
	at megamek.server.Server.processCommand(Server.java:31255)
	at megamek.server.Server.handle(Server.java:31335)
	at megamek.server.Server$1.packetReceived(Server.java:397)
	at megamek.common.net.AbstractConnection.processConnectionEvent(AbstractConnection.java:603)
	at megamek.common.net.AbstractConnection.processPacket(AbstractConnection.java:508)
	at megamek.common.net.AbstractConnection.update(AbstractConnection.java:453)
	at megamek.server.ConnectionHandler.run(ConnectionHandler.java:49)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Above is when using the /skip command to finish the turn. A different NPE is encountered when connecting an extra Megamek client and using Done to finish the last unit's turn.

```
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.common.weapons.ArtilleryWeaponIndirectFireHandler.handle(ArtilleryWeaponIndirectFireHandler.java:162)
	at megamek.server.Server.handleAttacks(Server.java:35528)
	at megamek.server.Server.handleAttacks(Server.java:35457)
	at megamek.server.Server.endCurrentPhase(Server.java:2947)
	at megamek.server.Server.changeToNextTurn(Server.java:3202)
	at megamek.server.Server.endCurrentTurn(Server.java:2212)
	at megamek.server.Server.receiveAttack(Server.java:13429)
	at megamek.server.Server.handle(Server.java:31381)
	at megamek.server.Server$PacketPump.run(Server.java:254)
```

### Files
The savegame and megameklog files of both types mentioned above are attached.
[autosave_2021-09-19_01-07-12.sav.gz](https://github.com/MegaMek/megamek/files/7193531/autosave_2021-09-19_01-07-12.sav.gz)
[megameklogDone.txt](https://github.com/MegaMek/megamek/files/7193533/megameklogDone.txt)
[megameklogSkip.txt](https://github.com/MegaMek/megamek/files/7193534/megameklogSkip.txt)

**Comment by NickAragua** [comment]
Did someone have a Sparrowhawk? And if so, was it mounting an arrow IV on an external pod?
