### ISSUE TITLE
Game freezes during aerospace battles 49.4 and 49.5 ( java.lang.IllegalArgumentException: bound must be positive)

### ISSUE THREAD

**Issue by StatSteiner** [MegaMek/megamek#3240]
### Environment
Megamek 49.4 and Megamek 49.5
Windows
Java vendor AdoptOpenJDK Java version 11.0.11

### Description
When playing space battles using aerospace assets specifically warships the game will freeze at the end of the firing phase but prior to showing the firing phase results. Issue occurs for both Megamek 49.4 and Megamek 49.5. Issue occurs in most games I have tested using aerospace assets. I noticed that the same issue occurs in the current stable release 48.0 as well.

### Files
Below is a saved game replicating the issue. The saved game is for Megamek 49.4. Player is named Test, opponent is named princess.
[Frozen.sav.gz](https://github.com/MegaMek/megamek/files/7501369/Frozen.sav.gz)

**Comment by NickAragua** [comment]
Could supply the log file next time you experience a freeze? I haven't been able to reproduce it so far.

**Comment by StatSteiner** [comment]
When i get the chance to play ill definitely supply the log

**Comment by StatSteiner** [comment]
I played about 4 test games and the freezing occurred again. Below I will attach the log and saved game file. This save has user as Jay and Princess as Princess. I used some custom warships in the final game but all 3 warships were considered valid and legal in MegamekLab. I can attach the custom units if you like too, just let me know. I appreciate the help!

[megameklog.txt](https://github.com/MegaMek/megamek/files/7526713/megameklog.txt)
[Frozen.sav.gz](https://github.com/MegaMek/megamek/files/7526720/Frozen.sav.gz)

**Comment by HammerGS** [comment]
We will need any custom units.

**Comment by StatSteiner** [comment]
Custom Units includes are:
Aegis Heavy Cruiser (ROS 3100) - Inner Sphere Unofficial 
Essex III Destroyer ROS (3090) - Inner Sphere Unofficial
Lola III Destroyer CLAN (3090) - Clan Unofficial
Sovetskii Soyuz Heavy Cruiser Clan 3100 - Clan Unofficial

[CustomWarshipFiles.zip](https://github.com/MegaMek/megamek/files/7531026/CustomWarshipFiles.zip)

**Comment by StatSteiner** [comment]
I figured I'd try and provide some more info on this strange issue. Here is a saved game using the custom units in included in the zip file above.

[Bugged.sav.gz](https://github.com/MegaMek/megamek/files/7674955/Bugged.sav.gz)

Player is Jay. Clan Falcon is Princess. Megamek version is 49.5. 
There is only 1 player unit left to fire, the Aegis heavy cruiser. If you split its available fire between the damaged Vincent Corvette #2 and Lola III destroyer #3 and then press done it should freeze the game prior to showing the fire results. It happened most times i reload the save. 

I hope this extra info helps.

**Comment by HammerGS** [comment]
From the Log
```
Exception in thread "Packet Pump" java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at megamek.common.MMRandom$CryptoRandom.randomInt(MMRandom.java:169)
	at megamek.common.MMRoll.<init>(MMRoll.java:70)
	at megamek.common.Compute.randomInt(Compute.java:251)
	at megamek.server.Server.applyAeroCritical(Server.java:25748)
	at megamek.server.Server.applyCriticalHit(Server.java:24558)
	at megamek.server.Server.criticalAero(Server.java:26891)
	at megamek.server.Server.checkAeroCrits(Server.java:26829)
	at megamek.server.Server.damageEntity(Server.java:23338)
	at megamek.common.weapons.WeaponHandler.handleEntityDamage(WeaponHandler.java:1575)
	at megamek.common.weapons.WeaponHandler.handle(WeaponHandler.java:1148)
	at megamek.common.weapons.BayWeaponHandler.handle(BayWeaponHandler.java:147)
	at megamek.server.Server.handleAttacks(Server.java:35493)
	at megamek.server.Server.handleAttacks(Server.java:35422)
	at megamek.server.Server.endCurrentPhase(Server.java:2727)
	at megamek.server.Server.changeToNextTurn(Server.java:3061)
	at megamek.server.Server.endCurrentTurn(Server.java:2130)
	at megamek.server.Server.receiveAttack(Server.java:13300)
	at megamek.server.Server.handle(Server.java:31295)
	at megamek.server.Server$PacketPump.run(Server.java:150)
```

**Comment by Windchild292** [comment]
Fix is now open. The first two issues were mistakenly linked, from a different issues I was looking at.
