### ISSUE TITLE
Null when saving MUL. (NullPointerException at megamek.common.EntityListFile.formatSlot(EntityListFile.java:111)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3336]
When saving a MUL file with the TSEMP file it won't save the MUL and pops up a "NULL" box in MegaMek. 

### Environment
What version of MegaMek does your issue apply to? 0.49.6-Dev December 27th Nightly
What operating system are you using?  Windows running from IDE as well.
What java version are you using?  Java 11

### Description
![image](https://user-images.githubusercontent.com/13752452/147613987-955c74c1-a36c-46d2-94be-fb10cce33815.png)

### Files
Use the Celerity CLR-04-R and try to save and you'll get the error. 

### Error in Log
```
16:15:27,437 ERROR [megamek.client.ui.swing.ClientGUI] {AWT-EventQueue-0}
megamek.client.ui.swing.ClientGUI.saveListFile(ClientGUI.java:1587) - 
java.lang.NullPointerException
	at megamek.common.EntityListFile.formatSlot(EntityListFile.java:111)
	at megamek.common.EntityListFile.getLocString(EntityListFile.java:379)
	at megamek.common.EntityListFile.writeEntityList(EntityListFile.java:955)
	at megamek.common.EntityListFile.saveTo(EntityListFile.java:521)
	at megamek.client.ui.swing.ClientGUI.saveListFile(ClientGUI.java:1585)
	at megamek.client.ui.swing.lobby.ChatLounge$3.actionPerformed(ChatLounge.java:1723)
```

**Comment by Windchild292** [comment]
It's just oneshot, not all TSEMP
