### ISSUE TITLE
[49.7] Uncaught exception detected (related to destruction of squadron?)

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/megamek#3576]
### Environment
Standalone Megamek
Windows 10
Java 11.0.13

### Description
Game stalled with uncaught exception detected at the end of the Firing Phase in a space combat game. Screen snip as of game stall (note Battery Squadron stuck partway through processing its destruction):
![image](https://user-images.githubusercontent.com/59574316/163698922-c301466c-1d1c-400b-8dd1-58ea67da6a18.png)

Error in logs:
```
16:30:36,821 ERROR [megamek.MegaMek] {Packet Pump}
megamek.MegaMek.lambda$main$0(MegaMek.java:59) - Uncaught Exception Detected
java.lang.IllegalArgumentException: bound must be positive
    at java.base/java.util.Random.nextInt(Random.java:388)
    at megamek.common.MMRandom$CryptoRandom.randomInt(MMRandom.java:159)
    at megamek.common.MMRoll.<init>(MMRoll.java:63)
    at megamek.common.Compute.randomInt(Compute.java:231)
    at megamek.server.Server.creditKill(Server.java:32819)
    at megamek.common.weapons.WeaponHandler.handle(WeaponHandler.java:1135)
    at megamek.server.Server.handleAttacks(Server.java:35180)
    at megamek.server.Server.handleAttacks(Server.java:35116)
    at megamek.server.Server.endCurrentPhase(Server.java:2708)
    at megamek.server.Server.changeToNextTurn(Server.java:3042)
    at megamek.server.Server.endCurrentTurn(Server.java:2110)
    at megamek.server.Server.receiveAttack(Server.java:13264)
    at megamek.server.Server.handle(Server.java:31059)
    at megamek.server.Server$PacketPump.run(Server.java:151)
    at java.base/java.lang.Thread.run(Thread.java:829)
```
Issue could be avoided by reloading from the start-of-firing-phase autosave and not shooting "Battery Squadron", which had a single fighter remaining at the start of the firing phase. Issue reproduced when some (but not all?) of the other squadrons were destroyed as well. Autosave from start of firing phase is provided for testing purposes.

### Files
[logsandsaves.zip](https://github.com/MegaMek/megamek/files/8500937/logsandsaves.zip)

**Comment by Windchild292** [comment]
This occurs when an aerospace squadron gets a kill the same turn it is destroyed, when it looks like the code meant for it to not assign it as a kill.

**Comment by binaryspica** [comment]
I have similar problems some hour ago(although with normal ASF, not squadron) but it seems that you got the point.

**Comment by Windchild292** [comment]
This one is unique to squadrons. The various unhandled exceptions will be showing up for the next little bit as they reveal otherwise missed issues dating back years... which can then be fixed.
