### ISSUE TITLE
[0.49.7] NPE at round end...

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/megamek#3582]
### Environment
Starting MekHQ v0.49.7
	Release Date: 2022-02-18
	Today: 2022-04-19
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.13
	Platform: Windows 10 10.0 (amd64)

### Description
Unexpected null pointer exception when clicking 'done' during combat. This was multiple rounds into a battle launched from MekHQ.

```
15:23:57,876 ERROR [mekhq.MekHQ] {Packet Pump}
mekhq.MekHQ.lambda$main$0(MekHQ.java:269) - Uncaught Exception Detected
java.lang.IllegalStateException: Entity #150 does not know its position.
	at megamek.common.Entity.getElevation(Entity.java:2119)
	at megamek.common.Entity.relHeight(Entity.java:2407)
	at megamek.common.actions.PunchAttackAction.toHitIsImpossible(PunchAttackAction.java:116)
	at megamek.common.actions.PunchAttackAction.toHit(PunchAttackAction.java:190)
	at megamek.common.Compute.canPhysicalTarget(Compute.java:5707)
	at megamek.common.Entity.isEligibleForPhysical(Entity.java:10001)
	at megamek.common.Entity.isEligibleFor(Entity.java:9780)
	at megamek.server.Server.setIneligible(Server.java:3911)
	at megamek.server.Server.prepareForPhase(Server.java:2279)
	at megamek.server.Server.changePhase(Server.java:2125)
	at megamek.server.Server.endCurrentPhase(Server.java:2728)
	at megamek.server.Server.checkReady(Server.java:1911)
	at megamek.server.Server.handle(Server.java:30993)
	at megamek.server.Server$PacketPump.run(Server.java:151)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/8515993/megamek.log)
[gamelog.html.txt](https://github.com/MegaMek/megamek/files/8515994/gamelog.html.txt)
[legacy.log](https://github.com/MegaMek/megamek/files/8515990/legacy.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/8515991/mekhq.log)

Custom mechs in userdata.zip
autosav.sav.gz is the last autosave from MegaMek
Autosave-1-Star League Reborn is the latest campaign save from MekHQ

[userdata.zip](https://github.com/MegaMek/megamek/files/8515997/userdata.zip)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/8516006/autosave.sav.gz)
[Autosave-1-Star League Reborn-30170914.cpnx.gz](https://github.com/MegaMek/megamek/files/8516009/Autosave-1-Star.League.Reborn-30170914.cpnx.gz)

**Comment by mjbroekman** [comment]
Loaded the game, added bot players for all missing players, and it threw an NPE at the end of the weapons firing phase again

**Comment by mjbroekman** [comment]
If I save the game at the point of the NPE, I am able to load that save to continue the battle to the next round, when it NPEs again, so I _am_ able to move on through the rounds of combat... but it occurs when attempting to move from the weapon fire phase to melee phase

**Comment by Windchild292** [comment]
Marta Krzywicki was picked up by the Hunchback, but was never cleared from the units... so she correctly has no location but shouldn't be being processed.
