### ISSUE TITLE
Princess freezes on Movement Phase with Vacumm Atmosphere. (java.lang.StackOverflowError)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3595]
### Environment
What version of MegaMek does your issue apply to? .48
What operating system are you using?  Windows
What java version are you using?  Java 11

### Description
From this forum post and I've duplicated the issue. 
https://bg.battletech.com/forums/megamek-games/bots-in-vacuum/

### Files
```
16:38:19,993 INFO [megamek.server.Server] {Packet Pump} 
prepareForPhase(), line 2297 : Round 1 memory usage: 400,485 kB
Time to prepare the shadow map: 79.1801 ms
BotClient calculated turns, Princess phase PHASE_TARGETING 0/1
Exception in thread "Princess-precognition (Princess)" java.lang.StackOverflowError
	at megamek.common.Crew.isActive(Crew.java:770)
	at megamek.common.Crew.isUnconscious(Crew.java:662)
	at megamek.common.Aero.isOutControlTotal(Aero.java:431)
	at megamek.common.MoveStep.compileIllegal(MoveStep.java:2021)
	at megamek.common.MoveStep.compile(MoveStep.java:1145)
	at megamek.common.MovePath.addStep(MovePath.java:310)
	at megamek.common.MovePath.addStep(MovePath.java:267)
	at megamek.common.MovePath.addStep(MovePath.java:179)
	at megamek.common.pathfinder.AeroGroundPathFinder.generateSidePaths(AeroGroundPathFinder.java:312)
	at megamek.common.pathfinder.AeroGroundPathFinder.generateSidePaths(AeroGroundPathFinder.java:321)
	at megamek.common.pathfinder.AeroGroundPathFinder.generateSidePaths(AeroGroundPathFinder.java:321)
	at megamek.common.pathfinder.AeroGroundPathFinder.generateSidePaths(AeroGroundPathFinder.java:321)
```

**Comment by VictorMorson** [comment]
Just confirming this issue persists in the current build.

**Comment by Sleet01** [comment]
Updated link to original issue report on forums: https://bg.battletech.com/forums/index.php?topic=77341.msg1827860#msg1827860
