### ISSUE TITLE
[49.8] Testing Branch Out of Memory Error at end of ASF Firing Phase

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#3648]
18:53:00,241 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.8-SNAPSHOT
	Build Date: 2022-05-16T01:41:50.033873500
	Release Date: 2022-02-18
	Today: 2022-05-18
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.15
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB

Low Atmo escort dropship mission.  Got this error at end of one of the firing phases at start of phase where you have control roll.  Only thing of note is that my House officer lost control and crashed.

Also - maybe unrelated, but my conventional pilots had a base gunnery penalty for some reason.  There may be a rules reason for this but Aero is not my specialty.  e.g. a 4/5 pilot flying a conventional fighter showed 7 as her base gunnery skill in the shooting calculation window, before other penalties.  I forgot to screenshot it.  Sorry.

![Screenshot 2022-05-18 232113](https://user-images.githubusercontent.com/23645569/169206422-95f5b32c-acdc-4148-a35b-d4d35935b021.png)
[megamek.log](https://github.com/MegaMek/megamek/files/8723941/megamek.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/8723942/mekhq.log)
[OoM.sav.gz](https://github.com/MegaMek/megamek/files/8723944/OoM.sav.gz)
[The Bluecoats30640914B.cpnx.gz](https://github.com/MegaMek/megamek/files/8723946/The.Bluecoats30640914B.cpnx.gz)

**Comment by Windchild292** [comment]
```
20:33:31,276 ERROR [mekhq.MekHQ] {Packet Pump}
mekhq.MekHQ.lambda$main$0(MekHQ.java:234) - Uncaught Exception Detected
java.util.ConcurrentModificationException
	at java.base/java.util.Vector$VectorSpliterator.forEachRemaining(Vector.java:1494)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at megamek.server.Server.send(Server.java:30869)
	at megamek.server.Server.prepareForPhase(Server.java:2542)
	at megamek.server.Server.changePhase(Server.java:2233)
	at megamek.server.Server.endCurrentPhase(Server.java:2971)
	at megamek.server.Server.checkReady(Server.java:2019)
	at megamek.server.Server.handle(Server.java:31000)
	at megamek.server.Server$PacketPump.run(Server.java:173)
	at java.base/java.lang.Thread.run(Thread.java:829)

20:36:04,996 INFO  [mekhq.gui.CampaignGUI] {AWT-EventQueue-0}
mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1348) - Saving campaign...

20:36:07,176 INFO  [mekhq.gui.CampaignGUI] {AWT-EventQueue-0}
mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1397) - Campaign saved to C:\Users\Daniel\Desktop\MHQ\Games\mekhq-windows-0.49.8-SNAPSHOT\campaigns\Bluecoats\The Bluecoats30640913.cpnx.gz

22:07:54,837 INFO  [mekhq.gui.CampaignGUI] {AWT-EventQueue-0}
mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1348) - Saving campaign...

22:09:10,341 INFO  [mekhq.gui.CampaignGUI] {AWT-EventQueue-0}
mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1348) - Saving campaign...

22:09:12,170 INFO  [mekhq.gui.CampaignGUI] {AWT-EventQueue-0}
mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1397) - Campaign saved to C:\Users\Daniel\Desktop\MHQ\Games\mekhq-windows-0.49.8-SNAPSHOT\campaigns\Bluecoats\The Bluecoats30640914.cpnx.gz

22:12:29,014 WARN  [mekhq.AtBGameThread] {The Bluecoats}
mekhq.AtBGameThread.run(AtBGameThread.java:99) - Client has not finished initialization, and is currently in an unknown phase.

22:12:29,078 WARN  [mekhq.AtBGameThread] {The Bluecoats}
mekhq.AtBGameThread.run(AtBGameThread.java:99) - Client has not finished initialization, and is currently in an unknown phase.

22:12:29,142 WARN  [mekhq.AtBGameThread] {The Bluecoats}
mekhq.AtBGameThread.run(AtBGameThread.java:99) - Client has not finished initialization, and is currently in an unknown phase.

22:12:29,142 INFO  [mekhq.AtBGameThread] {The Bluecoats}
mekhq.AtBGameThread.run(AtBGameThread.java:103) - Thread in lounge

23:20:42,635 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:234) - Uncaught Exception Detected
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.desktop/java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:186)
	at megamek.client.ui.swing.boardview.BoardView.updateShadowMap(BoardView.java:1428)
	at megamek.client.ui.swing.boardview.BoardView.paintComponent(BoardView.java:1087)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1643)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1618)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1556)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1323)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5203)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5013)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:848)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:848)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:823)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:772)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1890)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
```

**Comment by Thom293** [comment]
I was unaware that conventional and Aerospace pilots used different skills, so that is why my ASF pilots had penalties in the conventional aircraft.  I edited OP to remove that issue.
