### ISSUE TITLE
Capital scale Vessels softlock the game

### ISSUE THREAD

**Issue by insanebotv21** [MegaMek/megamek#3670]
version 0.49.2 
As far as i can tell the issue is caused by the structural health going into the negatives instead of a vessel dying, resulting in Princess getting hung up telling me that it is their turn  to fire just after the damage turn.

**Comment by insanebotv21** [comment]
i'll provide a file and error messages if i can get them.

**Comment by insanebotv21** [comment]
I encountered the bug again it's not clear what actually causes it but almost invariably the game will hang

**Comment by insanebotv21** [comment]
[megameklog.txt](https://github.com/MegaMek/megamek/files/8836092/megameklog.txt)
the game itself didn't seem to offer any cues whatsoever but it happens quite frequently

**Comment by HammerGS** [comment]
From the log:

```
Loading atlas: data\images\hexes\hexes_atlas.png
Exception in thread "Packet Pump" java.lang.IllegalArgumentException: bound must be positive
	at java.base/java.util.Random.nextInt(Random.java:388)
	at megamek.common.MMRandom$CryptoRandom.randomInt(MMRandom.java:169)
	at megamek.common.MMRoll.<init>(MMRoll.java:70)
	at megamek.common.Compute.randomInt(Compute.java:250)
	at megamek.server.Server.applyAeroCritical(Server.java:25817)
	at megamek.server.Server.applyCriticalHit(Server.java:24627)
	at megamek.server.Server.criticalAero(Server.java:26960)
	at megamek.server.Server.checkAeroCrits(Server.java:26910)
	at megamek.server.Server.damageEntity(Server.java:23407)
	at megamek.common.weapons.WeaponHandler.handleEntityDamage(WeaponHandler.java:1574)
	at megamek.common.weapons.WeaponHandler.handle(WeaponHandler.java:1147)
	at megamek.common.weapons.BayWeaponHandler.handle(BayWeaponHandler.java:146)
	at megamek.server.Server.handleAttacks(Server.java:35504)
	at megamek.server.Server.handleAttacks(Server.java:35433)
	at megamek.server.Server.endCurrentPhase(Server.java:2835)
	at megamek.server.Server.changeToNextTurn(Server.java:3168)
	at megamek.server.Server.endCurrentTurn(Server.java:2173)
	at megamek.server.Server.receiveAttack(Server.java:13368)
	at megamek.server.Server.handle(Server.java:31306)
	at megamek.server.Server$PacketPump.run(Server.java:183)
	at java.base/java.lang.Thread.run(Thread.java:829)
c:Contents of Send Queue: 
c:Contents of Send Queue: 
s:Contents of Send Queue: 
client: died
```

**Comment by repligator** [comment]
I've played dozens of capital scale games since this issue was opened without encountering this error. It's possible that it was fixed without the issue being closed, or was fixed as a side effect of other changes. Closing as resolved. If you feel this has been closed erroneously, please feel free to reopen.
