### ISSUE TITLE
NPE when using VGL on map edge

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/megamek#3753]
This particular bug goes back a ways as far I can can tell, at least back to .47 if not farther. This bug happens when you move a unit with a VGL such as the Estevez to the edge of the map board.
![tank_good](https://user-images.githubusercontent.com/1787879/176822732-1878d1eb-e51c-4895-969d-e1f541bf07be.png)
![tank_npe](https://user-images.githubusercontent.com/1787879/176822749-f97b60ff-f5da-479a-ab74-c10afdf43113.png)

[megamek.log](https://github.com/MegaMek/megamek/files/9025058/megamek.log)
[VGL_bug.sav.gz](https://github.com/MegaMek/megamek/files/9025052/VGL_bug.sav.gz)

**Comment by HammerGS** [comment]
```
00:24:14,832 ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$0(MegaMek.java:61) - Uncaught Exception Detected
java.lang.NullPointerException
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:459)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:263)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:255)
	at megamek.client.ui.swing.FiringDisplay.updateTarget(FiringDisplay.java:1885)
	at megamek.client.ui.swing.FiringDisplay.target(FiringDisplay.java:1833)
	at megamek.client.ui.swing.unitDisplay.WeaponPanel.valueChanged(WeaponPanel.java:2498)
```

**Comment by NickAragua** [comment]
Fixing the immediate error exposes an additional problem, which is that the Estevez in question technically *should* be able to fire its right-side grenade launcher, since one of the affected hexes is on the board, but currently cannot.
