### ISSUE TITLE
[0.49.7] Offboard artillery vehicle crew 'move' causes NPE

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/megamek#3772]
### Environment
	MegaMek v0.49.7
	Release Date: 2022-02-18
	Today: 2022-07-05
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.13
	Platform: Windows 10 10.0 (amd64)

### Description
Vehicle crews from destroyed offboard artillery can't plot paths to flee

```
22:05:32,225 ERROR [megamek.client.bot.princess.PathEnumerator] {Lyran Commonwealth Allied Artillery Turn 0 Calc Thread}
megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:304) - 
java.lang.NullPointerException
	at megamek.common.util.BoardUtilities.getClosestEdge(BoardUtilities.java:1582)
	at megamek.client.bot.princess.Princess.getHomeEdge(Princess.java:1766)
	at megamek.client.bot.princess.UnitBehavior.calculateUnitBehavior(UnitBehavior.java:35)
	at megamek.client.bot.princess.UnitBehavior.getBehaviorType(UnitBehavior.java:61)
	at megamek.client.bot.princess.PathEnumerator.updateLongRangePaths(PathEnumerator.java:327)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:232)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:128)
	at megamek.client.bot.princess.Precognition.ensureUpToDate(Precognition.java:335)
	at megamek.client.bot.princess.Princess.continueMovementFor(Princess.java:1204)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:505)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:473)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)

22:05:33,084 ERROR [megamek.client.bot.BotClient] {Lyran Commonwealth Allied Artillery Turn 0 Calc Thread}
megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:548) - 
java.lang.NullPointerException
	at megamek.common.util.BoardUtilities.getClosestEdge(BoardUtilities.java:1582)
	at megamek.client.bot.princess.Princess.getHomeEdge(Princess.java:1766)
	at megamek.client.bot.princess.UnitBehavior.calculateUnitBehavior(UnitBehavior.java:35)
	at megamek.client.bot.princess.UnitBehavior.getBehaviorType(UnitBehavior.java:61)
	at megamek.client.bot.princess.Princess.getMovePathsAndSetNecessaryTargets(Princess.java:1371)
	at megamek.client.bot.princess.Princess.continueMovementFor(Princess.java:1235)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:505)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:473)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Files
MegaMek log: [megamek.log](https://github.com/MegaMek/megamek/files/9050911/megamek.log)
Autosave prior to the turn it occurs in: [autosave.sav.gz](https://github.com/MegaMek/megamek/files/9050913/autosave.sav.gz)
Custom Units: [userdata.zip](https://github.com/MegaMek/megamek/files/9050915/userdata.zip)

**Comment by Dark-Hobbit** [comment]
Having a very similar bug in 0.50.02. An offboard artillery unit gets destroyed by a counter-battery fire, for some reason spawns a crew unit (also offboard) and breaks the game in movement phase by generating NPEs that don't allow you to do anything with that crew's move.

MegaMek log: [megamek.log](https://github.com/user-attachments/files/18306360/megamek.log)
Autosave in the turn after artillery unit got destroyed: [autosave.sav.gz](https://github.com/user-attachments/files/18306359/autosave.sav.gz)
Custom units: [customs.zip](https://github.com/user-attachments/files/18306361/customs.zip)
