### ISSUE TITLE
NPE in RAT Generator Editor

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3841]
Was working on adding Salvage data to the Escorpion Imperio and when I click to add the Hanseatic League (which was already on the list and I missed it). Got the following NPE

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.utilities.RATGeneratorEditor$SalvageEditorTableModel.getValueAt(RATGeneratorEditor.java:1418)
	at java.desktop/javax.swing.JTable.getValueAt(JTable.java:2706)
```

### Environment
What version of MegaMek does your issue apply to?  49.9MegaMek or HQ's MegaMek.
What operating system are you using?  Windows,

**Comment by SJuliez** [comment]
Can you reproduce that? I just tried and couldn't produce an NPE. It doesn't do anything when trying to add another HL line to the Escropio
