### ISSUE TITLE
StringIndexOutOfBoundsException - Possible related to the changes to the mutator short names

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#3885]
Reported from Discord

I get a java exception error during the initial firing phase in MegaMek.  I thought at first it might have been because I deployed too much infantry......but maybe it's something else? 

### Environment
What version of MegaMek does your issue apply to?  49.9
What operating system are you using?  Windows

### Files
No log only this snip of one. 

```
22:12:41,752 ERROR [mekhq.MekHQ] {Packet Pump}
mekhq.MekHQ.lambda$main$0(MekHQ.java:239) - Uncaught Exception Detected
java.lang.StringIndexOutOfBoundsException: begin 7, end 22, length 14
    at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
    at java.base/java.lang.String.substring(String.java:1874)
    at megamek.common.AmmoType.getSubMunitionName(AmmoType.java:13653)
    at megamek.common.weapons.MissileWeaponHandler.handle(MissileWeaponHandler.java:647)
    at megamek.server.GameManager.handleAttacks(GameManager.java:34050)
    at megamek.server.GameManager.handleAttacks(GameManager.java:33986)
    at megamek.server.GameManager.endCurrentPhase(GameManager.java:2203)
    at megamek.server.GameManager.changeToNextTurn(GameManager.java:2518)
    at megamek.server.GameManager.endCurrentTurn(GameManager.java:1593)
    at megamek.server.GameManager.receiveAttack(GameManager.java:12783)
    at megamek.server.GameManager.handlePacket(GameManager.java:773)
    at megamek.server.Server.handle(Server.java:1263)
    at megamek.server.Server$PacketPump.run(Server.java:110)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by HammerGS** [comment]
Might also be related to this - https://github.com/MegaMek/megamek/issues/3883
