### ISSUE TITLE
Empty Squadron Created in Lobby 0.49.9

### ISSUE THREAD

**Issue by BLR-IIC** [MegaMek/megamek#3889]
I successfully created five squadrons for my bot opponent.  However, when I created my first squadron, it came up empty as highlighted in the below image.  After that I successfully created two more squadrons.

Log file also attached.

![image](https://user-images.githubusercontent.com/18338059/189463500-e3e492c5-8e93-4d36-9399-1ed1222ab4e3.png)

[megamek.log](https://github.com/MegaMek/megamek/files/9539357/megamek.log)

**Comment by Gribbly1** [comment]
You can add fighters to squadrons in a similar way to loading transports

**Comment by BLR-IIC** [comment]
The problem here is that I _did_ add fighters, but MegaMek didn't.

**Comment by SJuliez** [comment]
There is nothing in the log. When you repeat the process, do you again get an empty squadron? It's unlikely we can do anything if we can't recreate the problem.

**Comment by BLR-IIC** [comment]
I'll see if I can reproduce it.  It happened after I created five enemy squadrons then this empty one happened.  When I tried to view it for kicks I got an error pop-up.  Although somewhat unrelated, did that show up in the log?  I noticed a bit of whitespace in the log file.

**Comment by SJuliez** [comment]
Oh, good point. I didn't notice that the log actually went on after all this white space. Strange. There's indeed an error in there. This is probably it.

21:23:39,353 ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$0(MegaMek.java:61) - Uncaught Exception Detected
java.lang.NullPointerException
	at megamek.common.templates.TROView.lambda$addMechVeeAeroFluff$0(TROView.java:217)
	at megamek.common.templates.TROView.formatSystemFluff(TROView.java:209)
	at megamek.common.templates.TROView.addMechVeeAeroFluff(TROView.java:216)
	at megamek.common.templates.AeroTROView.addFluff(AeroTROView.java:100)
	at megamek.common.templates.AeroTROView.initModel(AeroTROView.java:62)
	at megamek.common.templates.TROView.createView(TROView.java:87)
	at megamek.client.ui.panes.EntityViewPane.updateDisplayedEntity(EntityViewPane.java:93)
	at megamek.client.ui.panes.EntityViewPane.<init>(EntityViewPane.java:42)
	at megamek.client.ui.dialogs.EntityReadoutDialog.createCenterPane(EntityReadoutDialog.java:51)
	at megamek.client.ui.baseComponents.AbstractDialog.initialize(AbstractDialog.java:103)
	at megamek.client.ui.dialogs.EntityReadoutDialog.<init>(EntityReadoutDialog.java:46)
	at megamek.client.ui.dialogs.EntityReadoutDialog.<init>(EntityReadoutDialog.java:38)
	at megamek.client.ui.swing.lobby.ChatLounge.mechReadout(ChatLounge.java:1566)
	at megamek.client.ui.swing.lobby.ChatLounge.mechReadoutAction(ChatLounge.java:1557)
	at megamek.client.ui.swing.lobby.LobbyMekPopupActions.multiEntityAction(LobbyMekPopupActions.java:261)
	at megamek.client.ui.swing.lobby.LobbyMekPopupActions.actionPerformed(LobbyMekPopupActions.java:91)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by BLR-IIC** [comment]
This bug doesn't seem to be a problem in 0.50.10.  Closing ticket.
