### ISSUE TITLE
0.49.9 Megamek Freeze

### ISSUE THREAD

**Issue by wataru0042** [MegaMek/megamek#3900]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
Megamek 0.49.9 windows 10

### Description
Stop when the turn advances.

### Files
07:30:09,545 ERROR [mekhq.MekHQ] {Packet Pump}
mekhq.MekHQ.lambda$main$0(MekHQ.java:239) - Uncaught Exception Detected
java.lang.StringIndexOutOfBoundsException: begin 6, end 25, length 10
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at megamek.common.AmmoType.getSubMunitionName(AmmoType.java:13653)
	at megamek.common.weapons.MissileWeaponHandler.handle(MissileWeaponHandler.java:647)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34050)
	at megamek.server.GameManager.handleAttacks(GameManager.java:33986)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2203)
	at megamek.server.GameManager.changeToNextTurn(GameManager.java:2518)
	at megamek.server.GameManager.endCurrentTurn(GameManager.java:1593)
	at megamek.server.GameManager.receiveAttack(GameManager.java:12783)
	at megamek.server.GameManager.handlePacket(GameManager.java:773)
	at megamek.server.Server.handle(Server.java:1263)
	at megamek.server.Server$PacketPump.run(Server.java:110)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Windchild292** [comment]
This is fixed in 0.49.10. Please immediately update to that bugfix release.
