### ISSUE TITLE
NPE - MechFileParser

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#4043]
Running from the Repo - todays date. Getting a ton of the errors below in the log. MegaMek also fails to load a ton of units mostly Dropships.

![image](https://user-images.githubusercontent.com/13752452/207731810-e14e020f-9254-428b-ac47-64d1242cbfae.png)

### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure, it will state your java version at the top of the megamek.log file.
(Delete the above lines)

### Description
```
15:43:01,217 ERROR [megamek.common.MechFileParser] {Mech Cache Loader}
megamek.common.MechFileParser.<init>(MechFileParser.java:46) - 
java.lang.NullPointerException
	at megamek.common.weapons.autocannons.ACWeapon.getDamage(ACWeapon.java:111)
	at megamek.common.Entity.hasViableWeapons(Entity.java:872)
	at megamek.common.Entity.initMilitary(Entity.java:860)
	at megamek.common.MechFileParser.postLoadInit(MechFileParser.java:777)
	at megamek.common.MechFileParser.parse(MechFileParser.java:155)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:44)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:37)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:621)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:580)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:580)
	at megamek.common.MechSummaryCache.checkForChanges(MechSummaryCache.java:253)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:242)
	at megamek.common.MechSummaryCache.lambda$0(MechSummaryCache.java:82)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
and 

```
15:43:01,478 ERROR [megamek.common.MechFileParser] {Mech Cache Loader}
megamek.common.MechFileParser.<init>(MechFileParser.java:46) - 
java.lang.NullPointerException
	at megamek.common.weapons.lasers.ISERLaserLarge.getLongRange(ISERLaserLarge.java:66)
	at megamek.common.Entity.hasViableWeapons(Entity.java:886)
	at megamek.common.Entity.initMilitary(Entity.java:860)
	at megamek.common.MechFileParser.postLoadInit(MechFileParser.java:777)
	at megamek.common.MechFileParser.parse(MechFileParser.java:155)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:44)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:37)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:621)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:580)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:580)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:580)
	at megamek.common.MechSummaryCache.checkForChanges(MechSummaryCache.java:253)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:242)
	at megamek.common.MechSummaryCache.lambda$0(MechSummaryCache.java:82)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/10232242/megamek.log)
[legacy.log](https://github.com/MegaMek/megamek/files/10232243/legacy.log)

**Comment by kuronekochomusuke** [comment]
the git hub builds have been getting this error

> Task :megamek:equipmentList
Dec 14, 2022 4:25:31 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.

> Task :megamek:officialUnitList

Exception: java.awt.HeadlessException thrown from the UncaughtExceptionHandler in thread "Mech Cache Loader"
Error: The operation was canceled.

https://github.com/MegaMek/megamek/actions/runs/3693153810/jobs/6252809356#step:5:84


it maybe related, they also then hang for a few hours, before it is killed.

**Comment by kuronekochomusuke** [comment]
to reproduce you may need to reset the modified time on the data\mechfiles\units.cache file to something in the past.   to get it to process changes again.
