### ISSUE TITLE
NPE in WeaponAttackAction.toHit(WeaponAttackAction.java:329)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#4086]
Reported from Discord. Working on getting more details. 

### Environment
What version of MegaMek does your issue apply to?  0.48.0 MekHQ
What operating system are you using?  Windows
What java version are you using?  Java 11

### Description
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:329)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:316)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:309)
	at megamek.client.ui.swing.FiringDisplay.updateTarget(FiringDisplay.java:1884)
	at megamek.client.ui.swing.unitDisplay.WeaponPanel.valueChanged(WeaponPanel.java:2619)
```

### Files
[mekhqlog.txt](https://github.com/MegaMek/megamek/files/10346400/mekhqlog.txt)
[megameklog (1).txt](https://github.com/MegaMek/megamek/files/10346401/megameklog.1.txt)

**Comment by pheonixstorm** [comment]
If anyone else runs across this issue try to get a save file.

**Comment by Windchild292** [comment]
This has been resolved in latest.
