### ISSUE TITLE
[0.49.12] NPE During indirect phase with Arrow IV fired by aerospace that flew offboard

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4169]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
19:47:39,656 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:115) - Starting MegaMek v0.49.12-SNAPSHOT
	Build Date: 2023-02-06T01:24:33.625937
	Today: 2023-02-10
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.14.1
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
NPE error during Indirect phase (after movement). I believe it was caused by one of the enemy Conventional Fighters firing an Arrow IV missile but then flying off the map before the missile hit.

20:25:39,549 ERROR [mekhq.MekHQ] {Packet Pump}
mekhq.MekHQ.lambda$main$0(MekHQ.java:240) - Uncaught Exception Detected
java.lang.NullPointerException
	at megamek.common.IdealHex.get(IdealHex.java:112)
	at megamek.common.Coords.intervening(Coords.java:369)
	at megamek.common.Coords.intervening(Coords.java:348)
	at megamek.common.weapons.WeaponHandler.checkLI(WeaponHandler.java:1927)
	at megamek.common.weapons.WeaponHandler.handleEntityDamage(WeaponHandler.java:1511)
	at megamek.common.weapons.ArtilleryWeaponIndirectHomingHandler.handle(ArtilleryWeaponIndirectHomingHandler.java:250)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34018)
	at megamek.server.GameManager.handleAttacks(GameManager.java:33954)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2265)
	at megamek.server.GameManager.changeToNextTurn(GameManager.java:2502)
	at megamek.server.GameManager.endCurrentTurn(GameManager.java:1577)
	at megamek.server.GameManager.receiveAttack(GameManager.java:12782)
	at megamek.server.GameManager.handlePacket(GameManager.java:764)
	at megamek.server.Server.handle(Server.java:1257)
	at megamek.server.Server$PacketPump.run(Server.java:111)
	at java.base/java.lang.Thread.run(Unknown Source)

Save file and logs attached.
[Aero-launched Arrow IV error.zip](https://github.com/MegaMek/megamek/files/10712392/Aero-launched.Arrow.IV.error.zip)

**Comment by kuronekochomusuke** [comment]
may be relayed to #4161 
it was trying to fix an issue that involved a check for homing artillery and flying off the board

**Comment by kuronekochomusuke** [comment]
@Windchild292 

getting this error loading the save

com.thoughtworks.xstream.security.ForbiddenClassException: megamek.common.force.Force
	at com.thoughtworks.xstream.security.NoTypePermission.allows(NoTypePermission.java:26)
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)

**Comment by Thom293** [comment]
Perhaps related to this one too. 

https://github.com/MegaMek/megamek/issues/3568
