### ISSUE TITLE
NPE - Casual Joker Stream March 4th. Limited Info

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#4233]
We have a NPE from Casual Jokers Stream here - 

https://www.twitch.tv/videos/1755949775?t=03h38m0s

### Environment
What version of MegaMek does your issue apply to?  0.49.12
What operating system are you using?  Windows
What java version are you using? Java 11

### Description
Unknown cause but might we related to standing on a tank. 

### Files
[megamek (1).log](https://github.com/MegaMek/megamek/files/10933661/megamek.1.log)

This is a HTML file renamed to a text for posting.
[gamelog.txt](https://github.com/MegaMek/megamek/files/10933663/gamelog.txt)

(Delete the above lines)

**Comment by kuronekochomusuke** [comment]
there is a IllegalArgumentException error in the log like from the stream

```
21:19:42,289 ERROR [megamek.client.bot.princess.Precognition] {AWT-EventQueue-0}
megamek.client.bot.princess.Precognition.handlePacket(Precognition.java:271) - Attempted to parse unknown PacketCommand of SENDING_REPORTS_SPECIAL

21:19:43,217 ERROR [megamek.client.bot.princess.PathEnumerator] {Princess-precognition (Federated Suns Primary Opfor)}
megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:301) - 
java.lang.IllegalArgumentException: Entity invalid. ID 122
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:536)
	at megamek.common.MovePath.addStep(MovePath.java:371)
	at megamek.common.MovePath.addStep(MovePath.java:263)
	at megamek.common.MovePath.addStep(MovePath.java:175)
	at megamek.common.BulldozerMovePath.addStep(BulldozerMovePath.java:80)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.generateChildNodes(DestructionAwareDestinationPathfinder.java:163)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:105)
	at megamek.client.bot.princess.PathEnumerator.updateLongRangePaths(PathEnumerator.java:359)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:286)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:364)
	at java.base/java.lang.Thread.run(Thread.java:829)

21:23:55,724 ERROR [megamek.client.bot.princess.PathEnumerator] {Princess-precognition (Federated Suns Primary Opfor)}
megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:301) - 
java.lang.IllegalArgumentException: Entity invalid. ID 141
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:536)
	at megamek.common.MovePath.addStep(MovePath.java:371)
	at megamek.common.MovePath.addStep(MovePath.java:263)
	at megamek.common.MovePath.addStep(MovePath.java:175)
	at megamek.common.BulldozerMovePath.addStep(BulldozerMovePath.java:80)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.generateChildNodes(DestructionAwareDestinationPathfinder.java:163)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:105)
	at megamek.client.bot.princess.PathEnumerator.updateLongRangePaths(PathEnumerator.java:359)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:286)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:364)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by kuronekochomusuke** [comment]
this could be a timing issue.  at the start it checks if the entity is not null.   then calls recalculateMovesFor

```
    public void run() {
        try {
            // todo There's probably a better way to handle this than a loop that only exits on an error.
            while (!getDone().get()) {
                if (!getEventsToProcess().isEmpty()) {
                    processGameEvents();
                    ecmInfo = ComputeECM.computeAllEntitiesECMInfo(
                            getGame().getEntitiesVector());
                } else if (!getDirtyUnits().isEmpty()) {
                    Entity entity = getGame().getEntity(getDirtyUnits().pollFirst());
                    if ((entity != null) && isEntityOnMap(entity)) {
                        unPause();
                        LogManager.getLogger().debug("recalculating paths for " + entity.getDisplayName());
                        getPathEnumerator().recalculateMovesFor(entity);
                        LogManager.getLogger().debug("finished recalculating paths for " + entity.getDisplayName());
                    }
```

but by the time it gets to here it is no longer in game.getEntity, so it is null.

```
    public static boolean isPilotingSkillNeeded(Game game, int entityId,
            Coords src, Coords dest, EntityMovementType movementType,
            boolean isTurning, boolean prevStepIsOnPavement, int srcElevation,
            int destElevation, MoveStep moveStep) {
        final Entity entity = game.getEntity(entityId);
        final Hex srcHex = game.getBoard().getHex(src);
        final Hex destHex = game.getBoard().getHex(dest);
        final boolean isInfantry = (entity instanceof Infantry);
        int delta_alt = (destElevation + destHex.getLevel())
                        - (srcElevation + srcHex.getLevel());

        // arguments valid?
        if (entity == null) {
            throw new IllegalArgumentException("Entity invalid. ID " + entityId);
        }
        if (src.distance(dest) > 1) {
            throw new IllegalArgumentException("Coordinates must be adjacent.");
        }
```
