### ISSUE TITLE
49.12 Firing Phase VTOL Strafe Issue

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/megamek#4410]
### Environment
MegaMek battle within an MHQ AtB campaign
Windows
Version 11 Adoptium

### Description
Issue - Triggering VTOL Strafe attack popped up error. Error led to a weird glitched out view on all vehicle's weapon tabs as well as failing to complete the Strafing attack with more than 1 laser.
Step by Step of events
I had already complete the move phase for the turn. I had one of my VTOLs fly over in a strafing attack. During the firing phase I handed out all my firing orders to my units. When I got to the Warrior VTOL, I was able to fire its first weapon [Which thats a first, more on that in a bit] but when I clicked the fire button for the second time an error popped up. Unfortunately being the first time I have actually came across an issue and thought to upload it, I clicked through a few things and so I forgot the proper code on the pop up nor do I have a save for it [as I allowed the turn to move on]. 
To expand upon the bracket I mentioned earlier. Before when I have used VTOL strafes, I have not been able to actually click the fire button. I could still right click their path and click the fire option there and it would work. I believe that is because my VTOL's movement ended at the end of the strafe path, and since a unit can't target the space its in it was having issues. This time my VTOL's movement ended 1 space past the strafe route. Not sure if this may be having an impact on the issue or not.
I have also noticed there are two options that add in VTOL strafing, and at the time I did have them both on [not even realizing I did].

### Files
[megamek.log](https://github.com/MegaMek/megamek/files/11415971/megamek.log)
![Capture](https://user-images.githubusercontent.com/132851640/236702150-7d738f48-1f56-4ea6-a45d-b432461231e0.PNG)

[This is my first issue post. Please feel free to poke me if I messed something up]

**Comment by RaozSpaz** [comment]
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/11415998/autosave.sav.gz)

My name is the name of the campaign
Snowfall's Mercenaries
The save is from the turn immediately after the event. Not sure if itll help any but I figured Id give it none the less. Just had to find it.

**Comment by RaozSpaz** [comment]
I managed to recreate the bug. Attached is a proper auto-save with all 4 VTOLs performing the strafe action. In addition I took a screen clip of the actual error popup message [though you'll see it when you do things probably]. I also put the log again since it was during a different mission.

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/11416109/autosave.sav.gz)
![Capture2](https://user-images.githubusercontent.com/132851640/236705478-f5234760-5287-4515-ad00-206bcce9e22c.PNG)
[megamek.log](https://github.com/MegaMek/megamek/files/11416114/megamek.log)

**Comment by HammerGS** [comment]
```
17:25:33,917 ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$0(MegaMek.java:61) - Uncaught Exception Detected
java.lang.NullPointerException
	at megamek.common.Compute.isInArc(Compute.java:3874)
	at megamek.client.ui.swing.FiringDisplay.fire(FiringDisplay.java:1570)
	at megamek.client.ui.swing.FiringDisplay.actionPerformed(FiringDisplay.java:2252)
	at java.desktop/
```
