### ISSUE TITLE
0.49.14 - Uncaught Exception after Physical Attack phase

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4523]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:116) - Starting MegaMek v0.49.14-SNAPSHOT
	Build Date: 2023-06-09T01:44:24.498275400
	Today: 2023-06-12
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

### Description
Uncaught exception occurring after the Physical phase on turn 3 or 4. Attaching logs and savegames. Manual save taken as soon as I closed the exception popup, as well as the 3 autosaves previous.

Including custom units used in the battle in case it needs to be loaded up manually:
Uziel UZL-8S Mk IIC
Hammerhead (standard)
Hellhound II-P (Hellcat-P)
Mad Cat III C-Ph Mk III
DI Morgan Assault Tank C-Ph Mk V
Kinnol MBT C-Ph LRM Mk I
Zhukov Heavy Tank C-Ph Mk I
Marksman MBT C-Ph Mk I

### Files
[Physical Phase Uncaught Exception.zip](https://github.com/MegaMek/megamek/files/11738831/Physical.Phase.Uncaught.Exception.zip)

**Comment by PhoenixHeart512** [comment]
I may have attached the wrong log file. I got the error again (replaying the same mission) and the error appears to have been int he mekHQ log and not MM log, since the scenario was launched from mekHQ. New log attached:
10:47:50,700 ERROR [mekhq.MekHQ] {Packet Pump}
mekhq.MekHQ.lambda$main$0(MekHQ.java:240) - Uncaught Exception Detected
java.lang.IllegalStateException: Entity #117 does not know its position.
	at megamek.common.Entity.getElevation(Entity.java:2111)
	at megamek.client.ui.swing.tooltip.UnitToolTip.inGameValues(UnitToolTip.java:1113)
	at megamek.client.ui.swing.tooltip.UnitToolTip.getEntityTipTable(UnitToolTip.java:109)
	at megamek.client.ui.swing.tooltip.UnitToolTip.getEntityTipReport(UnitToolTip.java:84)
	at megamek.server.GameManager.entityStatusReport(GameManager.java:1797)
	at megamek.server.GameManager.prepareForPhase(GameManager.java:1992)
	at megamek.server.GameManager.changePhase(GameManager.java:1577)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2412)
	at megamek.server.GameManager.changeToNextTurn(GameManager.java:2686)
	at megamek.server.GameManager.endCurrentTurn(GameManager.java:1562)
	at megamek.server.GameManager.receiveAttack(GameManager.java:13009)
	at megamek.server.GameManager.handlePacket(GameManager.java:763)
	at megamek.server.Server.handle(Server.java:1265)
	at megamek.server.Server$PacketPump.run(Server.java:111)
	at java.base/java.lang.Thread.run(Unknown Source)


[mekhq.log](https://github.com/MegaMek/megamek/files/11747959/mekhq.log)

**Comment by PhoenixHeart512** [comment]
Actually it must be occurring sometime after the physical phase, because just now I saw it again but on the physical attack results screen
