### ISSUE TITLE
[0.49.14 Nightly] Princess Pathing Error With Offboard Artillery

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4558]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:116) - Starting MegaMek v0.49.14-SNAPSHOT
	Build Date: 2023-06-19T01:28:48.912615100
	Today: 2023-06-23
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
This will be several bug reports using the same logs and files as there are multiple errors showing in the log that should be tracked separately.

This error appears to be related to Princess pathing logic when using offboard artillery:

11:22:11,520 ERROR [megamek.common.pathfinder.LongestPathFinder.LongestPathRelaxer] {Princess-precognition (Draconis Combine Opfor Artillery)}
megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:170) - Top Move Path uses more MPs than Move Path Candidate.
java.lang.IllegalStateException
	at megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:170)
	at megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:125)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:266)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:295)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:242)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:364)
	at java.base/java.lang.Thread.run(Unknown Source)

### Files
[Log Errors and Long Turns.zip](https://github.com/MegaMek/megamek/files/11851142/Log.Errors.and.Long.Turns.zip)

**Comment by PhoenixHeart512** [comment]
@HammerGS I believe this can be closed, this was most likely resolved at some point since I have not run into it since, and none of the recent offboard artillery issues match this behavior either.

If it happens again we can submit a new/fresh bug for it.
