### ISSUE TITLE
[0.49.14 Nightly] Pathing Error "Top Move Path uses more MPs than Move Path Candidate."

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4559]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:116) - Starting MegaMek v0.49.14-SNAPSHOT
	Build Date: 2023-06-19T01:28:48.912615100
	Today: 2023-06-23
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
This will be several bug reports using the same logs and files as there are multiple errors showing in the log that should be tracked separately.

This one may be related to #4558 but I'm not sure, it appears to also be pathing related:

11:22:13,811 ERROR [megamek.common.pathfinder.LongestPathFinder.LongestPathRelaxer] {Draconis Combine Primary Opfor Turn 0 Calc Thread}
megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:170) - Top Move Path uses more MPs than Move Path Candidate.
java.lang.IllegalStateException
	at megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:170)
	at megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:125)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:266)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:295)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:242)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.ensureUpToDate(Precognition.java:341)
	at megamek.client.bot.princess.Princess.continueMovementFor(Princess.java:1193)
	at megamek.client.bot.princess.Princess.calculateMoveTurn(Princess.java:1025)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:520)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:483)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)

### Files
[Log Errors and Long Turns - Aero Battle.zip](https://github.com/MegaMek/megamek/files/11851174/Log.Errors.and.Long.Turns.-.Aero.Battle.zip)

**Comment by PhoenixHeart512** [comment]
This one can probably be closed, I haven't run into it in the last few versions so I assume it was fixed @HammerGS
