### ISSUE TITLE
[0.49.14 Nightly] megamek.log error - Failed to parse Packet command CHANGE_HEXES

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/megamek#4581]
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:116) - Starting MegaMek v0.49.14-SNAPSHOT
	Build Date: 2023-06-19T01:28:48.912615100
	Today: 2023-06-23
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

### Description
This will be several bug reports using the same logs and files as there are multiple errors showing in the log that should be tracked separately.

Not sure what this error is about:

11:44:18,530 ERROR [megamek.client.Client] {AWT-EventQueue-0}
megamek.client.Client.handlePacket(Client.java:1666) - Failed to parse Packet command CHANGE_HEXES
java.lang.IllegalStateException: setHexes received two collections differeing size!
	at megamek.common.Board.setHexes(Board.java:682)
	at megamek.client.Client.handlePacket(Client.java:1470)
	at megamek.client.bot.princess.Princess.handlePacket(Princess.java:1799)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:174)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

### Files
[Log Errors and Long Turns - Aero Battle.zip](https://github.com/MegaMek/mekhq/files/11851181/Log.Errors.and.Long.Turns.-.Aero.Battle.zip)

**Comment by PhoenixHeart512** [comment]
This one can also probably be closed, as I haven't run into it in the past few versions so it was probably fixed as well @HammerGS

**Comment by repligator** [comment]
I just ran into this in developmental.
[megamek.log](https://github.com/user-attachments/files/16127155/megamek.log)
[autosave.sav.gz](https://github.com/user-attachments/files/16127157/autosave.sav.gz)
[Round-21-autosave_2024-07-08_07-45-52.sav.gz](https://github.com/user-attachments/files/16127160/Round-21-autosave_2024-07-08_07-45-52.sav.gz)
[Round-22-autosave_2024-07-08_07-46-06.sav.gz](https://github.com/user-attachments/files/16127161/Round-22-autosave_2024-07-08_07-46-06.sav.gz)
[Round-23-autosave_2024-07-08_07-46-26.sav.gz](https://github.com/user-attachments/files/16127162/Round-23-autosave_2024-07-08_07-46-26.sav.gz)
