### ISSUE TITLE
49..14 - Unknown Freeze Near End of Game

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#4595]
13:59:49,902 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:116) - Starting MegaMek v0.49.13
	Build Date: 2023-05-23T14:36:10.295482500
	Today: 2023-07-03
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.7
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

Match with 2 dropships, friendy ASF, and Dueling Arty.

I was doing counterbattery fire at end of game.  Last turn before victory.  Got this NPE.  Reloaded and Skipped shooting arty in case it was related to counter battery fire, but got same NPE.  Id assume perhaps related to friendly ASF or Arty.  But not sure.

![image](https://github.com/MegaMek/megamek/assets/23645569/e120dc8a-7a49-461a-b751-7e954ae8a79f)
[megamek.log](https://github.com/MegaMek/megamek/files/11941036/megamek.log)

**Comment by kuronekochomusuke** [comment]
looks like 2 errors in the log

15:43:58,815 ERROR [megamek.client.Client] {AWT-EventQueue-0}
megamek.client.Client.handlePacket(Client.java:1666) - Failed to parse Packet command ENTITY_ATTACK
java.lang.NullPointerException: Cannot invoke "megamek.common.Targetable.getDisplayName()" because the return value of "megamek.common.actions.WeaponAttackAction.getTarget(megamek.common.Game)" is null
	at megamek.common.actions.WeaponAttackAction.toDisplayableString(WeaponAttackAction.java:5121)
	at megamek.client.ui.swing.AccessibilityWindow$1.gameNewAction(AccessibilityWindow.java:140)
	at megamek.common.event.GameNewActionEvent.fireEvent(GameNewActionEvent.java:52)
	at megamek.common.Game.processGameEvent(Game.java:2985)
	at megamek.common.Game.addAction(Game.java:2183)
	at megamek.client.Client.receiveAttack(Client.java:1190)
	at megamek.client.Client.handlePacket(Client.java:1536)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:174)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)



15:57:52,523 ERROR [megamek.common.net.connections.AbstractConnection] {Connection 7}
megamek.common.net.connections.AbstractConnection.update(AbstractConnection.java:366) - Server had an error receiving a packet
java.lang.NullPointerException: Cannot invoke "megamek.common.Hex.addTerrain(megamek.common.Terrain)" because "hex" is null
	at megamek.server.GameManager.deliverArtillerySmoke(GameManager.java:9933)
	at megamek.common.weapons.ArtilleryWeaponIndirectFireHandler.handle(ArtilleryWeaponIndirectFireHandler.java:337)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34253)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34189)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2419)
	at megamek.server.GameManager.sendCurrentInfo(GameManager.java:685)
	at megamek.server.Server.sendCurrentInfo(Server.java:744)
	at megamek.server.Server.receivePlayerName(Server.java:704)
	at megamek.server.Server.handle(Server.java:1221)
	at megamek.server.Server$1.packetReceived(Server.java:225)
	at megamek.common.net.connections.AbstractConnection.processConnectionEvent(AbstractConnection.java:491)
	at megamek.common.net.connections.AbstractConnection.processPacket(AbstractConnection.java:405)
	at megamek.common.net.connections.AbstractConnection.update(AbstractConnection.java:357)
	at megamek.server.ConnectionHandler.run(ConnectionHandler.java:47)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Thom293** [comment]
and I wasnt specific earlier because trying to talk on the phone and post at the same time.  Specifically - the freeze is right after the move phase, it freezes, gives the npe and says "Waiting on Start of FIring Phase".

Could also be related to #4553 ?

**Comment by neoancient** [comment]
I'm sure this is the same issue, fixed by #4617.
