### ISSUE TITLE
[Bug] NPE when using Aerospace Squadrons With Princess

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#4602]
MegaMek 49.13 (also present in 49.14 nightlies) 

A NPE is triggered at the beginning of the movement phase when using Princess and giving her a fighter squadron.

Relevant bit from the log seems to be this (full log is attached though): 

09:25:49,120 ERROR [megamek.MegaMek] {Packet Pump}
megamek.MegaMek.lambda$main$0(MegaMek.java:62) - Uncaught Exception Detected
java.lang.NullPointerException
	at megamek.common.IAero.getFuelUsed(IAero.java:772)
	at megamek.server.GameManager.processMovement(GameManager.java:8391)
	at megamek.server.GameManager.receiveMovement(GameManager.java:4365)
	at megamek.server.GameManager.handlePacket(GameManager.java:751)
	at megamek.server.Server.handle(Server.java:1265)
	at megamek.server.Server$PacketPump.run(Server.java:111)
	at java.base/java.lang.Thread.run(Unknown Source)

[megamek.log](https://github.com/MegaMek/megamek/files/11968687/megamek.log)

**Comment by neoancient** [comment]
This was fixed by #4570.
