### ISSUE TITLE
NullPointerException when Princess uses a Large Craft weapon requiring ammo

### ISSUE THREAD

**Issue by Logajam** [MegaMek/megamek#4703]
### Environment
Stand alone MM 49.14
Windows
Java 11.0.12

### Description
I'm at a loss.  Playing against the bot using custom units.
Princess has control of a custom Dropship, I'm using a force of custom units including fighter, mechs, and small craft with artillery.  Getting that error.

My immediate strategy is to fire artillery, and drop bombs on the dropship.  Mechs are advancing to shoot and kick the thing.  The bot is doing whatever the bot does.

Thunder (Me)
Princess (Bot)

### Files

[Crash1.zip](https://github.com/MegaMek/megamek/files/12326326/Crash1.zip)
[Crash2.zip](https://github.com/MegaMek/megamek/files/12326328/Crash2.zip)

**Comment by Logajam** [comment]
[custom units.zip](https://github.com/MegaMek/megamek/files/12326331/custom.units.zip)

**Comment by HammerGS** [comment]
From the Log #1 and 2

```
21:04:49,033 ERROR [megamek.MegaMek] {Packet Pump}
megamek.MegaMek.lambda$main$0(MegaMek.java:62) - Uncaught Exception Detected
java.lang.NullPointerException
	at megamek.common.weapons.ArtilleryCannonWeaponHandler.handle(ArtilleryCannonWeaponHandler.java:153)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34325)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34261)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2393)
	at megamek.server.GameManager.changeToNextTurn(GameManager.java:2708)
	at megamek.server.GameManager.endCurrentTurn(GameManager.java:1562)
	at megamek.server.GameManager.receiveAttack(GameManager.java:13045)
	at megamek.server.GameManager.handlePacket(GameManager.java:763)
	at megamek.server.Server.handle(Server.java:1265)
	at megamek.server.Server$PacketPump.run(Server.java:111)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
