### ISSUE TITLE
Unable to Load/Unload Battle Armour

### ISSUE THREAD

**Issue by wilkinswiki** [MegaMek/megamek#4750]
### Environment
Megamek 0.49.14
Windows 10
Java 11.0.11

### Description
Unable to load Battle Armour in the position selection stage. Can load BA in the lobby but unable to unload the BA in play. Error window pops up when load/unload button is clicked while it is selectable.

![Screenshot (117)](https://github.com/MegaMek/megamek/assets/67842850/67c753f3-61e2-4d67-bbf2-4af1b7d2cffa)

### Files
[unable_to_load_or_unload_ba.zip](https://github.com/MegaMek/megamek/files/12526349/unable_to_load_or_unload_ba.zip)

**Comment by HammerGS** [comment]
From the log
```

09:53:09,084 ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$0(MegaMek.java:62) - Uncaught Exception Detected
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key R10 Mechanized ICV (B) has the following unused space:
Troops - 0.0 tons (Fixed)
One battle armor squad
One trailer

Which unit do you want to unload?
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:558)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at megamek.client.ui.baseComponents.AbstractDialog.<init>(AbstractDialog.java:83)
	at megamek.client.ui.baseComponents.AbstractButtonDialog.<init>(AbstractButtonDialog.java:76)
	at megamek.client.ui.baseComponents.AbstractButtonDialog.<init>(AbstractButtonDialog.java:66)
	at megamek.client.ui.swing.AbstractChoiceDialog.<init>(AbstractChoiceDialog.java:55)
	at megamek.client.ui.swing.EntityChoiceDialog.<init>(EntityChoiceDialog.java:43)
	at megamek.client.ui.swing.EntityChoiceDialog.showSingleChoiceDialog(EntityChoiceDialog.java:70)
	at megamek.client.ui.swing.DeploymentDisplay.actionPerformed(DeploymentDisplay.java:767)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at megamek.client.ui.swing.widget.MegamekButton.processMouseEvent(MegamekButton.java:242)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
