### ISSUE TITLE
NPE with MechSetTest when run from within Eclipse.

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#478]
I use the MechSetTest to validate the sprites prior to committing them.  Lately its generating an error in the console.

This is what is printed:

Listing Errors for mechset.txt

Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:360)
	at megamek.test.MechSetTest.testImageName(MechSetTest.java:99)
	at megamek.test.MechSetTest.testFile(MechSetTest.java:83)
	at megamek.test.MechSetTest.main(MechSetTest.java:126)

**Comment by BLOODWOLF333** [comment]
I get it because were missing the umu.png in the defaults.
`Listing Errors for mechset.txt
Error with entry: exact default_umu : File not found! Entry Path: defaults/default_umu.png
Exception in thread "main" java.lang.NullPointerException
    at java.io.File.<init>(File.java:360)
    at megamek.test.MechSetTest.testImageName(MechSetTest.java:99)
    at megamek.test.MechSetTest.testFile(MechSetTest.java:83)
    at megamek.test.MechSetTest.main(MechSetTest.java:126)`

**Comment by HammerGS** [comment]
Fixed in 32379fa

Entering so Arlith doesn't have to :)
