### ISSUE TITLE
Null pointer exception when conducting counter-battery fire with Inferno-IVs

### ISSUE THREAD

**Issue by Saklad5** [MegaMek/megamek#4827]
### Environment
MegaMek Version: MekHQ v0.49.14 Development Snapshot
Operating System: Mac
Java Version: 20.0.1

### Description

I was using Inferno Arrow-IVs for counterbattery fire, reasoning that a direct hit would be likely to crit important components in the enemy artillery platform. Unfortunately, because the current implementation does not actually model the hex that off-board artillery resides in, this causes a null pointer exception to occur when the attack is resolved.

There are two ways this could be resolved: either skip setting fires with null hexes, which causes only the "Inferno SRM" effect of Inferno-IVs to be applied, or actually set fires on the off-board hexes, causing the artillery to remain on fire until it disengages.

Since the rules themselves aren't quite clear on this, I'm going to ask on the rules forum as well. In the interim, the first approach is probably sufficient to fix the issue for now.
```
java.lang.NullPointerException: Cannot invoke "megamek.common.Hex.terrainLevel(int)" because "h" is null
	at megamek.server.GameManager.deliverArtilleryInferno(GameManager.java:10064)
	at megamek.common.weapons.ArtilleryWeaponIndirectFireHandler.handle(ArtilleryWeaponIndirectFireHandler.java:330)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34325)
	at megamek.server.GameManager.handleAttacks(GameManager.java:34261)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2471)
	at megamek.server.GameManager.changeToNextTurn(GameManager.java:2708)
	at megamek.server.GameManager.endCurrentTurn(GameManager.java:1562)
	at megamek.server.GameManager.receiveAttack(GameManager.java:13045)
	at megamek.server.GameManager.handlePacket(GameManager.java:763)
	at megamek.server.Server.handle(Server.java:1265)
	at megamek.server.Server$PacketPump.run(Server.java:111)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by Saklad5** [comment]
I've submitted a [question](https://bg.battletech.com/forums/index.php/topic,82870.0.html) about this on the rules forum.

**Comment by Sleet01** [comment]
Is this fixed by the fix for #4803 ?

**Comment by Saklad5** [comment]
Seems probable, though that definitely doesn't address the question of Inferno fires. I notice Hammer immediately took up the question in their guise as forum moderator, so I say we keep this issue open until that's resolved.

**Comment by NickAragua** [comment]
Nah, 4803 won't help with this, it's a different method from looking at the stack trace.
