### ISSUE TITLE
[49.15]MegaMek hangs at end of battle and does not raise end of battle prompt in MekHQ

### ISSUE THREAD

**Issue by 9Epsilon9** [MegaMek/megamek#4850]
### Environment
This is HQ MegaMek:
MegaMek v0.49.15
	Build Date: 2023-10-21T10:18:43.323213200
	Today: 2023-10-25
	Origin Project: MekHQ
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.18
	Platform: Windows 7 6.1 (amd64)
	System Locale: en_AU
	Total memory available to MegaMek: 2 GB

### Description
Launch Scenario from MekHQ and play through battle. At the end of the battle, post saving the .MUL file, the game hangs and does not disconnect you from MegaMek so that you can finalize the battle in MekHQ.

I re-attempted multiple times including a restart of the PC and had exactly the same issue.

### Files
Screenshot of hanging screen attached
![screenshot](https://github.com/MegaMek/megamek/assets/135300945/12e70a3f-dd2d-44a8-986c-45db66b829c9)

The last six autosave files are attached.

[autosave_2023-10-25_07-36-36.sav.gz](https://github.com/MegaMek/megamek/files/13146922/autosave_2023-10-25_07-36-36.sav.gz)
[autosave_2023-10-25_07-37-56.sav.gz](https://github.com/MegaMek/megamek/files/13146684/autosave_2023-10-25_07-37-56.sav.gz)
[autosave_2023-10-25_07-35-55.sav.gz](https://github.com/MegaMek/megamek/files/13146907/autosave_2023-10-25_07-35-55.sav.gz)
[autosave_2023-10-25_07-35-13.sav.gz](https://github.com/MegaMek/megamek/files/13146911/autosave_2023-10-25_07-35-13.sav.gz)
[autosave_2023-10-25_07-34-31.sav.gz](https://github.com/MegaMek/megamek/files/13146915/autosave_2023-10-25_07-34-31.sav.gz)
[autosave_2023-10-25_07-37-20.sav.gz](https://github.com/MegaMek/megamek/files/13146918/autosave_2023-10-25_07-37-20.sav.gz)

Log files attached:
[megamek.log](https://github.com/MegaMek/megamek/files/13148936/megamek.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/13148982/mekhq.log)

**Comment by AfroSamurai34** [comment]
Same issue here.  I had to totally close out of the program and start it back up.  But it still recurs frequently

**Comment by kuronekochomusuke** [comment]
error from the log 

megamek.client.Client.handlePacket(Client.java:1709) - Failed to parse Packet command PHASE_CHANGE
java.lang.NullPointerException
	at megamek.client.Client.receiveReport(Client.java:1262)
	at megamek.client.ui.swing.MiniReportDisplay.addReportPages(MiniReportDisplay.java:316)
	at megamek.client.ui.swing.MiniReportDisplay$1.gamePhaseChange(MiniReportDisplay.java:376)
	at megamek.common.event.GamePhaseChangeEvent.fireEvent(GamePhaseChangeEvent.java:68)
	at megamek.common.Game.processGameEvent(Game.java:3011)
	at megamek.common.Game.setPhase(Game.java:717)
	at megamek.client.Client.changePhase(Client.java:417)
	at megamek.client.Client.handlePacket(Client.java:1522)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:176)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by kuronekochomusuke** [comment]
these may also be related 

#4846
#4847

**Comment by kuronekochomusuke** [comment]
to work around this issue until next release, you can hide the unit tooltip in the report log in game options.   this issue happens when it tries to display an pilot image in the report log, unit tooltip for a killed unit.

![image](https://github.com/MegaMek/megamek/assets/116095479/be8a64fd-054a-4a61-9cd0-19194efab669)

**Comment by 9Epsilon9** [comment]
Thanks for having a look.

It still hung in that same battle with that setting turned on. Other people are reporting similar problems with 49.15.

![screenshot2](https://github.com/MegaMek/megamek/assets/135300945/13a5c9b6-0ba6-4901-9e59-a1dab4c0c761)

**Comment by kuronekochomusuke** [comment]
did you restart the mission with the option turned on?

**Comment by 9Epsilon9** [comment]
I created a new gameoptions.xml file from MekHQ with this setting activated. Then I loaded the battle through MekHQ. Straight away I loaded the new gameoptions.xml file in MekHQ and double checked that it activated. I then proceeded to finish the battle.

**Comment by kuronekochomusuke** [comment]
you will need to completely restart the mission.    loading an existing megamek save uses the ordinal game options settings.

**Comment by 9Epsilon9** [comment]
Ok, might get it done today. Thanks for your help.
