### ISSUE TITLE
49.15 java.lang.NullPointerException

### ISSUE THREAD

**Issue by buzzzz2138** [MegaMek/megamek#4918]
### Environment
MekHQ MegaMek
Windows 10
Java 11.

### Description
Got this error message. Open the save and the error occurs. 

### Files
Customs file attached and campaign. 
Logs attached. 
[Error_2023_11_21.zip](https://github.com/MegaMek/megamek/files/13433634/Error_2023_11_21.zip)

**Comment by HammerGS** [comment]
Lots of NULL tags in the log and these in the MekHQ Log.

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 80
	at java.base/java.util.Vector.elementData(Vector.java:762)
	at java.base/java.util.Vector.get(Vector.java:783)
	at megamek.common.Game.getTurnForPlayer(Game.java:572)
	at megamek.server.GameManager.receiveAttack(GameManager.java:13094)
	at megamek.server.GameManager.handlePacket(GameManager.java:763)
	at megamek.server.Server.handle(Server.java:1265)
	at megamek.server.Server$PacketPump.run(Server.java:111)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

22:25:32,517 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:240) - Uncaught Exception Detected
```
java.lang.NullPointerException
	at megamek.client.ui.swing.FiringDisplay.setFireEnabled(FiringDisplay.java:2347)
	at megamek.client.ui.swing.FiringDisplay.disableButtons(FiringDisplay.java:978)
	at megamek.client.ui.swing.FiringDisplay.ready(FiringDisplay.java:1232)
	at megamek.client.ui.swing.util.TurnTimer$1.actionPerformed(TurnTimer.java:72)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by HammerGS** [comment]
Can you give details about what was happening when it happened?

**Comment by buzzzz2138** [comment]
We had someone disconnect and a different user connected. At this point megamek locked up and we were unable to do anything.  Closed everything then restarted Megamek from MekHQ.  Once we reconnected several people received the popup for Null Pointer Exception.  We were able to finish the game without most problems.  The Server (my system) would get updated to the report screen last.  Sometimes 10+ seconds after everyone else.

**Comment by SJuliez** [comment]
It is, unfortunately, unlikely that given the substantial changes to the code that have happened since then and the momentary circumstances of someone logging off and logging on again we're going to find the issue. And it's not going to get any better. Therefore closing this (and hoping this was a one-time hiccup)
