### ISSUE TITLE
[49.15] Indirect Fire Weapons Panel does not include Spotter bonus

### ISSUE THREAD

**Issue by ramrodofavalon** [MegaMek/megamek#4937]
### Environment
49.15 run MegaMek
macOS Sonoma 14.2
openjdk 11.0.18 2023-01-17

### Description
When using a Forward Observer and artillery, the Fire Weapons Panel does not update for Fire Adjust. However, the TN in Offboard Attack Phase is adjusted 

![image](https://github.com/MegaMek/megamek/assets/16293857/f143bd76-6829-4765-b4e7-8428bba94559)
![image](https://github.com/MegaMek/megamek/assets/16293857/d5848649-f9f4-46f6-8e52-1d91fe110b81)
![image](https://github.com/MegaMek/megamek/assets/16293857/2cee64a7-36a8-420d-9bc1-5c1e88b0382b)

### Files

megamek.log
Thjese are the only two entires in megemek.log, they repeat but I would assume not relevant
08:08:30,069 ERROR [megamek.client.ui.swing.boardview.FovHighlightingAndDarkening] {AWT-EventQueue-0}
megamek.client.ui.swing.boardview.FovHighlightingAndDarkening.getLosEffects(FovHighlightingAndDarkening.java:320) - Cannot process line of sight effects with a null source hex.

08:09:33,952 ERROR [megamek.client.ui.swing.minimap.Minimap] {AWT-EventQueue-0}
megamek.client.ui.swing.minimap.Minimap.getMinimapImage(Minimap.java:214) - 
java.lang.NullPointerException
	at megamek.client.ui.swing.minimap.Minimap.paintAttack(Minimap.java:869)
	at megamek.client.ui.swing.minimap.Minimap.drawMap(Minimap.java:555)
	at megamek.client.ui.swing.minimap.Minimap.getMinimapImage(Minimap.java:211)
	at megamek.client.ui.swing.minimap.Minimap$4.gamePhaseChange(Minimap.java:1427)
	at megamek.common.event.GamePhaseChangeEvent.fireEvent(GamePhaseChangeEvent.java:68)
	at megamek.common.Game.processGameEvent(Game.java:3011)
	at megamek.common.Game.setPhase(Game.java:717)
	at megamek.client.Client.changePhase(Client.java:417)
	at megamek.client.Client.handlePacket(Client.java:1522)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:176)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ramrodofavalon** [comment]
This may be an oddly intermittent issue 
![image](https://github.com/MegaMek/megamek/assets/16293857/3f76a32b-3e4a-4752-bef1-b955b19bdf57)
