### ISSUE TITLE
[0.49.17] Closing unit selector in MML without selecting a unit causes an error message

### ISSUE THREAD

**Issue by dxz6228** [MegaMek/megamek#4991]
### Environment
Running Megamek 0.49.17.
Java version is 11.0.19, from Oracle.
Running on Windows.

### Description
Closing the from-cache unit selector in MML without actually choosing a unit produces an error message. Logs complain about a null pointer from what I can see, or something like that?
![изображение](https://github.com/MegaMek/megamek/assets/38220488/723e577a-91cb-4cdc-9135-819af3dd19b4)
![изображение](https://github.com/MegaMek/megamek/assets/38220488/ec229fd3-b4d9-4d3d-a73e-8c9acadb3359)

### Files
Attaching log files as per the message's suggestion.
[megamek.log](https://github.com/MegaMek/megamek/files/13802385/megamek.log)
[megameklab.log](https://github.com/MegaMek/megamek/files/13802386/megameklab.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/13802387/mekhq.log)

**Comment by HammerGS** [comment]
```
java.lang.NullPointerException
	at megameklab.ui.StartupGUI.selectAndLoadUnitFromCache(StartupGUI.java:254)
	at megameklab.ui.StartupGUI.lambda$initComponents$0(StartupGUI.java:102)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
```
