### ISSUE TITLE
Exceptions upon starting a new game 

### ISSUE THREAD

**Issue by SJuliez** [MegaMek/megamek#5113]
When starting the lobby, a bunch of exceptions show up pointing to Entity.getArmorWeight, l.10837. They seem to have no further effect, units load fine after that.
Edit: It's mostly Gun Emplacements; these can't be added in the lobby

**Comment by HammerGS** [comment]
![image](https://github.com/MegaMek/megamek/assets/13752452/cce9b735-3bc0-42f2-b82c-5f25dc3cbe34)

[megamek.log](https://github.com/MegaMek/megamek/files/14141813/megamek.log)

```
megamek.common.MechFileParser.<init>(MechFileParser.java:78) - 
java.lang.NullPointerException: Cannot invoke "megamek.common.equipment.ArmorType.getPointsPerTon(megamek.common.Entity)" because the return value of "megamek.common.equipment.ArmorType.forEntity(megamek.common.Entity, int)" is null
	at megamek.common.Entity.getArmorWeight(Entity.java:10838)
	at megamek.common.Entity.getArmorWeight(Entity.java:10853)
	at megamek.common.loaders.BLKAeroSpaceFighterFile.getEntity(BLKAeroSpaceFighterFile.java:181)
	at megamek.common.MechFileParser.parse(MechFileParser.java:157)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:73)
	at megamek.common.MechSummaryCache.loadMechsFromZipFile(MechSummaryCache.java:850)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:758)
	at megamek.common.MechSummaryCache.checkForChanges(MechSummaryCache.java:257)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:246)
	at megamek.common.MechSummaryCache.lambda$getInstance$0(MechSummaryCache.java:85)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
```
23:13:30,099 ERROR [megamek.common.MechFileParser] {Mech Cache Loader}
megamek.common.MechFileParser.<init>(MechFileParser.java:78) - 
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at megamek.common.Entity.getArmorTechLevel(Entity.java:10682)
	at megamek.common.equipment.ArmorType.forEntity(ArmorType.java:40)
	at megamek.common.equipment.ArmorType.forEntity(ArmorType.java:44)
	at megamek.common.Entity.getArmorWeight(Entity.java:10864)
	at megamek.common.loaders.BLKGunEmplacementFile.getEntity(BLKGunEmplacementFile.java:47)
	at megamek.common.MechFileParser.parse(MechFileParser.java:157)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:73)
	at megamek.common.MechSummaryCache.loadMechsFromZipFile(MechSummaryCache.java:850)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:758)
	at megamek.common.MechSummaryCache.checkForChanges(MechSummaryCache.java:257)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:246)
	at megamek.common.MechSummaryCache.lambda$getInstance$0(MechSummaryCache.java:85)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
