### ISSUE TITLE
[0.49.18] NPE (Cannot invoke "megamek.common.Game.getPhase()" because the return value of "megamek.common.Entity.getGame()" is null)  when using keyboard shortcuts to turn

### ISSUE THREAD

**Issue by vipersbrood** [MegaMek/megamek#5177]
0.49.18 dev
Windows 11
Java 17.0.8

NPE occurs when using default turn keyboard shortcuts (Shift + A / Shift + D)

[savegame.sav.gz](https://github.com/MegaMek/megamek/files/14321123/savegame.sav.gz)
[megamek.log](https://github.com/MegaMek/megamek/files/14321128/megamek.log)

![image](https://github.com/MegaMek/megamek/assets/64331766/0807e71e-5710-4093-adcd-c4faf993a062)

**Comment by HammerGS** [comment]
```
megamek.common.MULParser.parseTurretLock(MULParser.java:1969) - 
java.lang.NullPointerException: Cannot invoke "megamek.common.Game.getPhase()" because the return value of "megamek.common.Entity.getGame()" is null
	at megamek.common.Entity.setSecondaryFacing(Entity.java:2649)
	at megamek.common.Tank.setSecondaryFacing(Tank.java:423)
	at megamek.common.MULParser.parseTurretLock(MULParser.java:1966)
	at megamek.common.MULParser.parseEntity(MULParser.java:547)
	at megamek.common.MULParser.parse(MULParser.java:388)
	at megamek.common.MULParser.<init>(MULParser.java:355)
	at mekhq.utilities.MHQXMLUtility.parseSingleEntityMul(MHQXMLUtility.java:528)
	at mekhq.campaign.io.CampaignXmlParser.checkUnits(CampaignXmlParser.java:1114)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:187)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:83)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:336)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:192)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
