### ISSUE TITLE
NPE errors from Feb 17th Casual Joker Stream - megamek.client.Client.handlePacket(Client.java:1710) - Failed to parse Packet command ENTITY_ATTACK

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#5205]
Joker reported - These files are from a game where it locked up while reinforcing with a MUL when the round report popped up. sleet01 told me I could send them over to you.

[gamelog.zip](https://github.com/MegaMek/megamek/files/14395122/gamelog.zip)

From the log 33 of these.
```
23:00:06,403 ERROR [megamek.client.Client] {AWT-EventQueue-0}
megamek.client.Client.handlePacket(Client.java:1710) - Failed to parse Packet command ENTITY_ATTACK
java.lang.NullPointerException
	at megamek.common.actions.WeaponAttackAction.toDisplayableString(WeaponAttackAction.java:5352)
	at megamek.client.ui.swing.AccessibilityWindow$1.gameNewAction(AccessibilityWindow.java:140)
	at megamek.common.event.GameNewActionEvent.fireEvent(GameNewActionEvent.java:52)
	at megamek.common.Game.processGameEvent(Game.java:2998)
	at megamek.common.Game.addAction(Game.java:2196)
	at megamek.client.Client.receiveAttack(Client.java:1187)
	at megamek.client.Client.handlePacket(Client.java:1580)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:176)
```

**Comment by Sleet01** [comment]
Damn my eyes, I did say that... >_<

**Comment by HammerGS** [comment]
Also these. 1300 of them.

```
2:24:55,208 ERROR [megamek.common.pathfinder.LongestPathFinder.LongestPathRelaxer] {Princess-precognition (BAM Bot)}
megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:170) - Top Move Path uses more MPs than Move Path Candidate.
java.lang.IllegalStateException
	at megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:170)
	at megamek.common.pathfinder.LongestPathFinder$LongestPathRelaxer.doRelax(LongestPathFinder.java:125)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:266)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:295)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:245)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:364)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Sleet01** [comment]
> Joker reported - These files are from a game where it locked up while reinforcing with a MUL when the round report popped up. sleet01 told me I could send them over to you.
> 
> [gamelog.zip](https://github.com/MegaMek/megamek/files/14395122/gamelog.zip)
> 
> From the log 33 of these.
> 
> ```
> 23:00:06,403 ERROR [megamek.client.Client] {AWT-EventQueue-0}
> megamek.client.Client.handlePacket(Client.java:1710) - Failed to parse Packet command ENTITY_ATTACK
> java.lang.NullPointerException
> 	at megamek.common.actions.WeaponAttackAction.toDisplayableString(WeaponAttackAction.java:5352)
> 	at megamek.client.ui.swing.AccessibilityWindow$1.gameNewAction(AccessibilityWindow.java:140)
> 	at megamek.common.event.GameNewActionEvent.fireEvent(GameNewActionEvent.java:52)
> 	at megamek.common.Game.processGameEvent(Game.java:2998)
> 	at megamek.common.Game.addAction(Game.java:2196)
> 	at megamek.client.Client.receiveAttack(Client.java:1187)
> 	at megamek.client.Client.handlePacket(Client.java:1580)
> 	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:176)
> ```

I believe this occurs for _any_ update or pop-up while another dialog is open; in this case, it looks like it was an attack action being posted to the Chat box while the MUL loader was focused.  I can try reproducing this with a separate MM server while the IDE is running a client, but if somebody else is better versed in AWT or Swing, they should take this part over.
