### ISSUE TITLE
Broken Units with recent changes (java.lang.Exception: megamek.common.loaders.EntityLoadingException:)

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#5237]
I suspect it might be related to a recent PR.

### Environment
What version of MegaMek does your issue apply to?  0.49.19 from the Repo as off todays date.
What operating system are you using?  Windows and Java 17

### Description
<img width="581" alt="image" src="https://github.com/MegaMek/megamek/assets/13752452/6cfbd633-4a42-4c86-a05c-c0ca643c4856">

### Files
The units are correct and will no longer load.

**Comment by HammerGS** [comment]
```
10:29:44,111 ERROR [megamek.common.MechFileParser] {Thread-0}
megamek.common.MechFileParser.<init>(MechFileParser.java:48) - 
java.lang.Exception: megamek.common.loaders.EntityLoadingException: Improved C3 Computer (C3I) does not fit in CT on Cronus CNS-TD9 ID:-1
        free criticals in location: 1, criticals needed: 2
    at megamek.common.loaders.MtfFile.getEntity(MtfFile.java:495)
    at megamek.common.MechFileParser.parse(MechFileParser.java:157)
    at megamek.common.MechFileParser.<init>(MechFileParser.java:46)
    at mekhq.campaign.unit.UnitTechProgression.calcTechProgression(UnitTechProgression.java:122)
    at mekhq.campaign.unit.UnitTechProgression$BuildMapTask.call(UnitTechProgression.java:150)
    at mekhq.campaign.unit.UnitTechProgression$BuildMapTask.call(UnitTechProgression.java:138)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: megamek.common.loaders.EntityLoadingException: Improved C3 Computer (C3I) does not fit in CT on Cronus CNS-TD9 ID:-1
        free criticals in location: 1, criticals needed: 2
    at megamek.common.loaders.MtfFile.parseCrits(MtfFile.java:922)
    at megamek.common.loaders.MtfFile.getEntity(MtfFile.java:405)
    ... 7 more

10:29:44,377 ERROR [megamek.common.loaders.MtfFile] {Thread-0}
megamek.common.loaders.MtfFile.getEntity(MtfFile.java:494) - 
megamek.common.loaders.EntityLoadingException: MASC does not fit in LT on Tundra Wolf 2 ID:-1
        free criticals in location: 2, criticals needed: 3
    at megamek.common.loaders.MtfFile.parseCrits(MtfFile.java:922)
    at megamek.common.loaders.MtfFile.getEntity(MtfFile.java:405)
    at megamek.common.MechFileParser.parse(MechFileParser.java:157)
    at megamek.common.MechFileParser.<init>(MechFileParser.java:46)
    at mekhq.campaign.unit.UnitTechProgression.calcTechProgression(UnitTechProgression.java:122)
    at mekhq.campaign.unit.UnitTechProgression$BuildMapTask.call(UnitTechProgression.java:150)
    at mekhq.campaign.unit.UnitTechProgression$BuildMapTask.call(UnitTechProgression.java:138)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.lang.Thread.run(Thread.java:833)
```
