### ISSUE TITLE
NPE during initiation of Physical Attack Phase caused by NPE when target was destroyed by Ammo Explosion in the shooting phase.

### ISSUE THREAD

**Issue by agreen53** [MegaMek/megamek#5255]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
What version of MegaMek does your issue apply to?  MegaMek v0.49.7
What operating system are you using?  Windows
What java version are you using?  LibericaJDK-17

### Description
During movement phase I declared a DFA against an immobile prone target.  During Shooting phase another mech shot and cause the target to explode.  After the shooting phase was declared complete a Null Pointer appeared on the screen and the Physical Attack phase is unable to start and MegaMek appears to be halted while waiting for the Physical attack phase to begin.

### Files
Agreen53 no password
[BuggedGame.sav.zip](https://github.com/MegaMek/megamek/files/14624892/BuggedGame.sav.zip)

**Comment by HammerGS** [comment]
```
14:22:25,045 ERROR [megamek.server.Server] {Packet Pump}
megamek.server.Server.saveGame(Server.java:1173) - Unable to save file: savegames\autosave.sav
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.concurrent.CopyOnWriteArrayList
converter           : com.thoughtworks.xstream.converters.reflection.SerializableConverter
message[1]          : Unable to make private void java.util.concurrent.CopyOnWriteArrayList.readObject(java.io.ObjectInputStream) throws java.io.IOException,java.lang.ClassNotFoundException accessible: module java.base does not "opens java.util.concurrent" to unnamed module @442675e1
converter[1]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[2]          : Unable to make field private static final long java.util.concurrent.CopyOnWriteArrayList.serialVersionUID accessible: module java.base does not "opens java.util.concurrent" to unnamed module @442675e1
-------------------------------
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:478)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:48)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1250)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1239)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1212)
	at megamek.server.Server.saveGame(Server.java:1171)
	at megamek.server.Server.autoSave(Server.java:1099)
	at megamek.server.Server.prepareForPhase(Server.java:2333)
	at megamek.server.Server.changePhase(Server.java:2125)
	at megamek.server.Server.endCurrentPhase(Server.java:2648)
	at megamek.server.Server.changePhase(Server.java:2134)
	at megamek.server.Server.endCurrentPhase(Server.java:2855)
	at megamek.server.Server.checkReady(Server.java:1911)
	at megamek.server.Server.handle(Server.java:30993)
	at megamek.server.Server$PacketPump.run(Server.java:151)
	at java.base/java.lang.Thread.run(Thread.java:840)

```


```
14:23:06,706 ERROR [megamek.MegaMek] {Packet Pump}
megamek.MegaMek.lambda$main$0(MegaMek.java:59) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "megamek.common.Targetable.isConventionalInfantry()" because the return value of "megamek.common.actions.DfaAttackAction.getTarget(megamek.common.Game)" is null
	at megamek.server.Server.preTreatPhysicalAttack(Server.java:32897)
	at megamek.server.Server.resolvePhysicalAttacks(Server.java:14920)
	at megamek.server.Server.endCurrentPhase(Server.java:2732)
	at megamek.server.Server.changeToNextTurn(Server.java:3042)
	at megamek.server.Server.executePhase(Server.java:2475)
	at megamek.server.Server.changePhase(Server.java:2132)
	at megamek.server.Server.endCurrentPhase(Server.java:2728)
	at megamek.server.Server.checkReady(Server.java:1911)
	at megamek.server.Server.handle(Server.java:30993)
	at megamek.server.Server$PacketPump.run(Server.java:151)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by HammerGS** [comment]
This is likely fixed in later Dev versions as we've implemented lots of fixes around DFA's
