### ISSUE TITLE
[0.49.19-SNAPSHOT] Illegal Cast Exception when lowering elevation with a VTOL

### ISSUE THREAD

**Issue by HoneySkull** [MegaMek/megamek#5298]
### Environment
Build Date: 2024-03-29T10:27:39.922754800
	Today: 2024-03-30
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 11.0.20.1
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 2 GB

### Description
Load a simple map with a VTOL and hit the lower elevation button.  The following illegal cast exception appears and prevents the VTOL from lowering elevation.  The VTOL is able to raise elevation.

![image](https://github.com/MegaMek/megamek/assets/83041327/6585ecf3-7532-493a-8551-6de796995258)

### Files

[megamek.log](https://github.com/MegaMek/megamek/files/14813383/megamek.log)

**Comment by HoneySkull** [comment]
16:22:35,998 ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$0(MegaMek.java:63) - Uncaught Exception Detected
java.lang.ClassCastException: class megamek.common.VTOL cannot be cast to class megamek.common.IAero (megamek.common.VTOL and megamek.common.IAero are in unnamed module of loader 'app')
	at megamek.client.ui.swing.MovementDisplay.actionPerformed(MovementDisplay.java:5026)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
