### ISSUE TITLE
NPE starting fights with Aero

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#536]
SUCCESS: Client/Server Version (0.43.2-git) and Checksum (b87cdc67796bd93375d9eb65f17079a806456f869d186327c337beeef90e07f4) matched
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.common.Aero.updateWeaponGroups(Aero.java:3772)
	at megamek.common.Aero.applyBombs(Aero.java:3502)
	at megamek.server.Server.checkEntityExchange(Server.java:2769)
	at megamek.server.Server.executePhase(Server.java:2713)
	at megamek.server.Server.changePhase(Server.java:2336)
	at megamek.server.Server.endCurrentPhase(Server.java:2842)
	at megamek.server.Server.checkReady(Server.java:2108)
	at megamek.server.Server.handle(Server.java:29965)
	at megamek.server.Server$PacketPump.run(Server.java:355)
	at java.lang.Thread.run(Thread.java:745)

[GG-Aero-NPE.sav.gz](https://github.com/MegaMek/megamek/files/942922/GG-Aero-NPE.sav.gz)

This may be a a memory issue. Once I restarted MHQ and re-launched the the fight, it worked properly.

**Comment by mkerensky** [comment]
I think this has been fixed in 0.43.5.  Bombs and weapon groups were changed when LAMs were added in 0.43.4 and a couple of lingering bugs fixed after that.
