### ISSUE TITLE
NPEs during deployment phase

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/megamek#540]
Ejecting crew size: 1
Round 6 memory usage: 383,735 kB
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ui.swing.boardview.AttackSprite.addWeapon(AttackSprite.java:263)
	at megamek.client.ui.swing.boardview.AttackSprite.<init>(AttackSprite.java:105)
	at megamek.client.ui.swing.boardview.BoardView1.addAttack(BoardView1.java:4310)
	at megamek.client.ui.swing.boardview.BoardView1.refreshAttacks(BoardView1.java:4346)
	at megamek.client.ui.swing.boardview.BoardView1$14.gamePhaseChange(BoardView1.java:5123)
	at megamek.common.event.GamePhaseChangeEvent.fireEvent(GamePhaseChangeEvent.java:72)
	at megamek.common.Game.processGameEvent(Game.java:3112)
	at megamek.common.Game.setPhase(Game.java:818)
	at megamek.client.Client.changePhase(Client.java:458)
	at megamek.client.Client.handlePacket(Client.java:1301)
	at megamek.client.Client$1$2.run(Client.java:219)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at megamek.common.actions.WeaponAttackAction.toHitIsImpossible(WeaponAttackAction.java:2978)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:387)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:257)
	at megamek.client.bot.BotClient.getDeployDamage(BotClient.java:851)
	at megamek.client.bot.BotClient.getStartingCoordsArray(BotClient.java:613)
	at megamek.client.bot.princess.Princess.calculateDeployment(Princess.java:248)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:402)
	at megamek.client.bot.BotClient.access$000(BotClient.java:83)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:99)

[autosave.sav.gz](https://github.com/MegaMek/megamek/files/948097/autosave.sav.gz)

**Comment by arlith** [comment]
If you loaded this saved game, does the issue reoccur for you?

**Comment by arlith** [comment]
There's the reported issue of the NPE, which I'm not 100% certain of the cause for, however above that is the issue of why there are attack actions during the deployment phase.  When the phase changes, the board view always updates the actions, and it uses `Game.getActions` to get actions (despite the generic name, these are only actions related to firing/physicals/targeting).  It looks like `Game` clears that at the start of certain phases.  It does not clear them for deployment, but I think that's because previously that never made sense, as deployment only ever happened at the start of the game. I think this is an oversight that never caused an issue before.

**Comment by arlith** [comment]
I made it so combat actions are cleared from the game at the start of deployment.
