### ISSUE TITLE
cant edit bots in lobby with latest

### ISSUE THREAD

**Issue by kuronekochomusuke** [MegaMek/megamek#5413]
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.20-SNAPSHOT
	Build Date: N/A
	Today: 2024-04-24
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB

in lobby bots are not editable when starting a new game.
double click on bot and menu is grayed out.

![image](https://github.com/MegaMek/megamek/assets/116095479/96fe9067-5221-4da2-952a-c32db589cf3c)

[megamek.log](https://github.com/MegaMek/megamek/files/15101776/megamek.log)

**Comment by Sleet01** [comment]
@kuronekochomusuke Do you happen to have a log for this run?

**Comment by kuronekochomusuke** [comment]
attached it, but not seeing anything useful in it.

**Comment by Sleet01** [comment]
I think this is new / suboptimal, but I'd need to check against an older build:
```
19:05:39,809 ERROR [megamek.client.AbstractClient] {AWT-EventQueue-0}
megamek.client.AbstractClient.handlePacket(AbstractClient.java:383) - Failed to parse Packet command SERVER_GREETING
java.lang.NullPointerException
	at java.base/java.util.TreeMap.compare(TreeMap.java:1570)
	at java.base/java.util.TreeMap.addEntryToEmptyMap(TreeMap.java:776)
	at java.base/java.util.TreeMap.put(TreeMap.java:785)
	at java.base/java.util.TreeMap.put(TreeMap.java:534)
	at megamek.client.bot.BotClient.correctName(BotClient.java:1162)
	at megamek.client.AbstractClient.handleGameIndependentPacket(AbstractClient.java:413)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:376)
	at megamek.client.bot.princess.Princess.handlePacket(Princess.java:1915)
	at megamek.client.AbstractClient$1.lambda$packetReceived$0(AbstractClient.java:530)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

19:05:39,810 ERROR [megamek.client.bot.princess.Precognition] {AWT-EventQueue-0}
megamek.client.bot.princess.Precognition.handlePacket(Precognition.java:273) - Attempted to parse unknown PacketCommand of SERVER_GREETING

19:05:39,813 ERROR [megamek.client.bot.BotClient] {AWT-EventQueue-0}
megamek.client.bot.BotClient.correctName(BotClient.java:1158) - Name correction arrived at incorrect BotClient!
```

**Comment by kuronekochomusuke** [comment]
that could be from when it tried to add the bot

**Comment by Sleet01** [comment]
I'm seeing this in the latest code; I'll try bisecting to narrow down the offending change.

**Comment by Sleet01** [comment]
Bisect tracked down this check-in: eef2a3c4dd711fabceff392ee9b91a8d94eec9bb

PR: https://github.com/MegaMek/megamek/pull/5384

Commit: https://github.com/MegaMek/megamek/pull/5384/commits/eef2a3c4dd711fabceff392ee9b91a8d94eec9bb

**Comment by Sleet01** [comment]
I believe this doesn't break for saved games because the bot already has a name by the time it gets to this call, but for new bots, they don't yet have a name so the new code thinks the _wrong_ bot has been renamed (when in fact this is the way a new bot _gets_ a name).

**Comment by Sleet01** [comment]
@SJuliez I think the issue is the lack of a `break;` after line 411 in `AbstractClient.java`; that's new code from the offending commit and it looks like we're erroneously falling through from `case SERVER_GREETING` to `case SERVER_CORRECT_NAME`.
