### ISSUE TITLE
Megamek can't exit attack phase using fighter squadrons 0.43.1

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#542]
From this forum post

http://bg.battletech.com/forums/index.php?topic=57260.0

```
Exception in thread "Packet Pump" java.lang.IndexOutOfBoundsException: Index: 5, Size: 5
   at java.util.ArrayList.rangeCheck(Unknown Source)
   at java.util.ArrayList.get(Unknown Source)
   at megamek.server.Server.damageEntity(Server.java:21018)
   at megamek.common.weapons.WeaponHandler.handleEntityDamage(WeaponHandler.java:1077)
   at megamek.common.weapons.WeaponHandler.handle(WeaponHandler.java:623)
   at megamek.server.Server.handleAttacks(Server.java:34184)
   at megamek.server.Server.handleAttacks(Server.java:34113)
   at megamek.server.Server.endCurrentPhase(Server.java:2945)
   at megamek.server.Server.changeToNextTurn(Server.java:3267)
   at megamek.server.Server.endCurrentTurn(Server.java:2313)
   at megamek.server.Server.receiveAttack(Server.java:12788)
   at megamek.server.Server.handle(Server.java:29997)
   at megamek.server.Server$PacketPump.run(Server.java:355)
```

**Comment by sadlerbw** [comment]
Log file from v0.42.1 with an example of this error. Two fighters joined as a squadron on each side, with a live player, myself, against TestBot. Doesn't matter which bot is used, as I've tried princess as well. Also doesn't seem to matter what type of unit does damage to the squadron, it still throws the error. I've tried damage from single fighters, dropships, and warships: all of them produced the same error.

[megameklog.txt](https://github.com/MegaMek/megamek/files/950200/megameklog.txt)

**Comment by mchapman1970** [comment]
I have had problems with the Squadrons also if you remember we troubleshoot the issue on slack around March 31.  I had built my squadrons in the lobby and the game would crash during the transition from weapon fire phase to the next.

**Comment by sadlerbw** [comment]
Another bit of info. I tried this same thing in v0.41.11 and it did NOT throw an error. damage was taken by ships in the squadron, and the game kept on moving. I also tried it in v0.41.28 and it did throw the error. So, somewhere between 0.41.11 and 0.41.28, this bug was introduced.

**Comment by sadlerbw** [comment]
Decided to poke through the code a bit, and it looks like this is related to a change to the FighterSquadron API from September 2016 that was rolled out as part of the v0.41.24 release. The very first if() inside the damageEntity() function in Server.java at line 21016 was changed to use the new .getActiveSubEntities() function instead of doing a check with .getFighters().size(). My java is super-rusty, but I'm almost certain the NPE is happening on the line:

Entity fighter = fighters.get(hit.getLocation());

Haven't figured out if the problem is the hit location not expecting to get mapped to a fighter in a squadron, or if the .getSubEntities() function is returning null, but it is probably one or the other.

**Comment by mkerensky** [comment]
I've encountered this in the past week using 0.43.2.  The Exception line numbers have changed a bit since this was first reported, the current exception is this:
Exception in thread "Packet Pump" java.lang.IndexOutOfBoundsException: Index: 12, Size: 6
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at megamek.server.Server.damageEntity(Server.java:21024)
	at megamek.common.weapons.WeaponHandler.handleEntityDamage(WeaponHandler.java:1077)
	at megamek.common.weapons.WeaponHandler.handle(WeaponHandler.java:623)
	at megamek.server.Server.handleAttacks(Server.java:34208)
	at megamek.server.Server.handleAttacks(Server.java:34137)
	at megamek.server.Server.endCurrentPhase(Server.java:2947)
	at megamek.server.Server.changeToNextTurn(Server.java:3269)
	at megamek.server.Server.endCurrentTurn(Server.java:2314)
	at megamek.server.Server.receiveAttack(Server.java:12784)
	at megamek.server.Server.handle(Server.java:30021)
	at megamek.server.Server$PacketPump.run(Server.java:355)
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1153139/autosave.sav.gz)

The attached save is ready to reproduce the issue if it needs any further troubleshooting.  Start the game as "Test".  I ran the opponent "Target" with a second instance of MM when doing my own tests.
I have the "Allow large squadrons" option enabled, and tried attacking both the 1 and 2 target squadrons -   1 is a standard 6 fighter squadron, 2 is an 8.  You get an error no matter which one is targeted.  I have also tried turning 'single fighters not capital' on and off with no change in results. 
In another game, I confirmed that you can fire a squadron's weapons at dropships, jumpships, warships and single, non-capital fighters that have been unloaded from a squadron entity without any issue. This only happens when a squadron takes damage (from any of those sources).  The other ship types can also all fire at each other without issues.

**Comment by neoancient** [comment]
The fighter squadron is supposed to set the index of the fighter hit as the hit location, but it returns the entity id instead.
