### ISSUE TITLE
[49.19] MechWarrior ejection causes another Mech to end player's turns

### ISSUE THREAD

**Issue by Dark-Hobbit** [MegaMek/megamek#5463]
### Environment
Software used: Match started in MekHQ 0.49.19, continued in normal version of MegaMek from a savegame.
Java Vendor: Eclipse Adoptium
Java Version: 11.0.22.7
Platform: Win11 23H2

### Description
I have two Mechs that seem to cause problems in the attached savefile: a Wasp and a Grasshopper. If the Wasp's pilot ejects, the next Grasshopper's turn immediately ends the current phase for the player (Siberian Shamans) but not for the opfor. The turn order at the bottom of the screen still includes the player, but simply skips over the palyer's turns.

The order of events does not matter, as ejecting the Wasp pilot after moving the Grasshopper still ends the phase for the player. What's more, this behaviour in fact continues into the following phases - the firing phase also ends for the player the moment Grasshopper has acted. The only way to avoid this anomaly seems to be skipping turns for the Wasp.

In fact, I suspect the Wasp to be the culprit since I have earlier seen a bug where the pilot ejected from the Wasp while the Mech remained an active unit and not destroyed. Unfortunately, I have been unable to reproduce that bug since. However, I have no idea why skipping phases only gets triggered by the Grasshopper and not by any other player Mech.

### Files
Both the savegame and the logs for replicating this behaviour are attached, player name is "Siberian Shamans" (without quotation marks). 
[issue_5463.sav.gz](https://github.com/MegaMek/megamek/files/15283685/issue_5463.sav.gz)
[issue_5463_megamek.log](https://github.com/MegaMek/megamek/files/15283686/issue_5463_megamek.log)

Please let me know if any other help is needed.

**Comment by Dark-Hobbit** [comment]
Actually, on the topic of the Wasp not being destroyed when it should. I just played a few more rounds in this cursed save, and the Wasp is still an active unit despite losing its CT and being tagged as DESTROYED by the game. And right after it happened, the behaviour repeated itself (the pilot did not eject). So it seems the cause is not the ejection per se but rather it tagging that Mech as destroyed.

New save is attached for this situation.
[issue_5463_undead_mech.sav.gz](https://github.com/MegaMek/megamek/files/15283760/issue_5463_undead_mech.sav.gz)

**Comment by HammerGS** [comment]
Bunch of these in the log

```
19:27:43,196 ERROR [megamek.common.GameReports] {AWT-EventQueue-0}
megamek.common.GameReports.get(GameReports.java:60) - GameReports.get() was asked for reports of a round [10] which it does not posses.
java.lang.RuntimeException
	at megamek.common.GameReports.get(GameReports.java:60)
	at megamek.common.Game.getReports(Game.java:2586)
	at megamek.client.Client.handlePacket(Client.java:1554)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:177)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Sleet01** [comment]
> Bunch of these in the log
> 
> ```
> 19:27:43,196 ERROR [megamek.common.GameReports] {AWT-EventQueue-0}
> megamek.common.GameReports.get(GameReports.java:60) - GameReports.get() was asked for reports of a round [10] which it does not posses.
> java.lang.RuntimeException
> 	at megamek.common.GameReports.get(GameReports.java:60)
> 	at megamek.common.Game.getReports(Game.java:2586)
> 	at megamek.client.Client.handlePacket(Client.java:1554)
> 	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:177)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
> ```

I think we might see that if the user loads up one of the rotating saves, because it saves at the beginning of the round rather than at the end.  I don't think this is actually causing any issues, though, and was considering silencing this error.
