### ISSUE TITLE
NPE when clicking on a mech

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/megamek#5483]
### Environment
MegaMek 49.19.1
Windows 10
Java Version: 11.0.16

### Description
I was fighting a Stratcon battle sent from MekHQ.  I started it this morning.  I completed the movement phase I was partway through; when I clicked on one of my mechs (I think the Grasshopper) during the shooting phase I got a NPE.

From the log:

15:02:01,091 ERROR [megamek.client.Client] {AWT-EventQueue-0}
megamek.client.Client.handlePacket(Client.java:1712) - Failed to parse Packet command TURN
java.lang.NullPointerException
	at megamek.common.IdealHex.get(IdealHex.java:112)
	at megamek.common.Coords.radian(Coords.java:236)
	at megamek.common.Coords.degree(Coords.java:261)
	at megamek.common.Compute.isInArc(Compute.java:4054)
	at megamek.common.Compute.isInArc(Compute.java:4020)
	at megamek.common.actions.SearchlightAttackAction.isPossible(SearchlightAttackAction.java:68)
	at megamek.client.ui.swing.FiringDisplay.updateSearchlight(FiringDisplay.java:2344)
	at megamek.client.ui.swing.FiringDisplay.updateTarget(FiringDisplay.java:2011)
	at megamek.client.ui.swing.FiringDisplay.target(FiringDisplay.java:1904)
	at megamek.client.ui.swing.FiringDisplay.selectEntity(FiringDisplay.java:812)
	at megamek.client.ui.swing.FiringDisplay.beginMyTurn(FiringDisplay.java:870)
	at megamek.client.ui.swing.FiringDisplay.gameTurnChange(FiringDisplay.java:2216)
	at megamek.common.event.GameTurnChangeEvent.fireEvent(GameTurnChangeEvent.java:46)
	at megamek.common.Game.processGameEvent(Game.java:3001)
	at megamek.common.Game.setTurnIndex(Game.java:650)
	at megamek.client.Client.changeTurnIndex(Client.java:516)
	at megamek.client.Client.handlePacket(Client.java:1528)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:177)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Files
Logs:
[megamek.log](https://github.com/MegaMek/megamek/files/15358548/megamek.log)
[mekhq.log](https://github.com/MegaMek/megamek/files/15358549/mekhq.log)

Battle save:
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/15358555/autosave.sav.gz)

Unit files:
[Meks.zip](https://github.com/MegaMek/megamek/files/15358559/Meks.zip)

Campaign save:
[Bluethings30260529.cpnx.gz](https://github.com/MegaMek/megamek/files/15358581/Bluethings30260529.cpnx.gz)

I didn't upload portrait files or custom paint.  Let me know if those are needed.

**Comment by HammerGS** [comment]
```
15:02:01,091 ERROR [megamek.client.Client] {AWT-EventQueue-0}
megamek.client.Client.handlePacket(Client.java:1712) - Failed to parse Packet command TURN
java.lang.NullPointerException
at megamek.common.IdealHex.get(IdealHex.java:112)
at megamek.common.Coords.radian(Coords.java:236)
at megamek.common.Coords.degree(Coords.java:261)
at megamek.common.Compute.isInArc(Compute.java:4054)
at megamek.common.Compute.isInArc(Compute.java:4020)
at megamek.common.actions.SearchlightAttackAction.isPossible(SearchlightAttackAction.java:68)
at megamek.client.ui.swing.FiringDisplay.updateSearchlight(FiringDisplay.java:2344)
at megamek.client.ui.swing.FiringDisplay.updateTarget(FiringDisplay.java:2011)
at megamek.client.ui.swing.FiringDisplay.target(FiringDisplay.java:1904)
at megamek.client.ui.swing.FiringDisplay.selectEntity(FiringDisplay.java:812)
at megamek.client.ui.swing.FiringDisplay.beginMyTurn(FiringDisplay.java:870)
at megamek.client.ui.swing.FiringDisplay.gameTurnChange(FiringDisplay.java:2216)
at megamek.common.event.GameTurnChangeEvent.fireEvent(GameTurnChangeEvent.java:46)
at megamek.common.Game.processGameEvent(Game.java:3001)
at megamek.common.Game.setTurnIndex(Game.java:650)
at megamek.client.Client.changeTurnIndex(Client.java:516)
at megamek.client.Client.handlePacket(Client.java:1528)
at megamek.client.Client$1.lambda$packetReceived$0(Client.java:177)
```

**Comment by BlueThing00** [comment]
I just reproduced this by starting the battle from the saved game, moving units, and clicking on the Grasshopper in the shooting phase.

**Comment by Sleet01** [comment]
I"ll take it, just on the off-chance that the SearchlightAttackAction connection is not a coincidence...
