### ISSUE TITLE
Able to declare a melee attack while pilot is KO'd

### ISSUE THREAD

**Issue by jmeickle** [MegaMek/megamek#5653]
### Environment
MegaMek is via MekHQ.

```
Starting MegaMek v0.49.19.1
	Build Date: 2024-05-10T20:11:07.455725852
	Today: 2024-06-30
	Origin Project: MegaMek
	Java Vendor: Eclipse Adoptium
	Java Version: 21.0.1
	Platform: Windows 11 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 8 GB
```

### Description

One of my pilots fired a TSEMP cannon, which exploded and knocked them out during the firing phase. But in the melee phase, they were available for an attack declaration (both in the init order, and buttons not being greyed out). While the attack didn't resolve, this is still unexpected

![image](https://github.com/MegaMek/megamek/assets/536435/7961b841-88c7-427c-839d-c8d61809602c)

### Files

[megamek.log](https://github.com/user-attachments/files/16044641/megamek.log)
[melee_repro.sav.gz](https://github.com/user-attachments/files/16044632/melee_repro.sav.gz)

**Comment by HammerGS** [comment]
Spotted this in the log but likely unrelated.

```
08:16:40,138 ERROR [megamek.common.pathfinder.AbstractPathFinder] {Princess-precognition (Republic Senate Primary Opfor)}
megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:285) - 
java.lang.IllegalArgumentException: Entity invalid. ID 45
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:562)
	at megamek.common.MovePath.addStep(MovePath.java:371)
	at megamek.common.MovePath.addStep(MovePath.java:263)
	at megamek.common.MovePath.addStep(MovePath.java:175)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:309)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:233)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:270)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:295)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:245)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:366)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
