### ISSUE TITLE
Server stops responding when DropShip crashes at a map edge.

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/megamek#568]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:291)

To simulate, load megamek.common.actions.WeaponAttackAction.toHit-shootingending.gz, make the last shooting, press done at the shooting report, the game will freeze.

For earlier save, megamek.common.actions.WeaponAttackAction.toHit-shootingbegin.gz, the start of player's shooting. megamek.common.actions.WeaponAttackAction.toHit-roundstart.gz, the start of round 2.

[megamek.common.actions.WeaponAttackAction.toHit-log.txt](https://github.com/MegaMek/megamek/files/1132807/megamek.common.actions.WeaponAttackAction.toHit-log.txt)
[megamek.common.actions.WeaponAttackAction.toHit-shootingending.gz](https://github.com/MegaMek/megamek/files/1132808/megamek.common.actions.WeaponAttackAction.toHit-shootingending.gz)
[megamek.common.actions.WeaponAttackAction.toHit-shootingbegin.gz](https://github.com/MegaMek/megamek/files/1132809/megamek.common.actions.WeaponAttackAction.toHit-shootingbegin.gz)
[megamek.common.actions.WeaponAttackAction.toHit-roundstart.gz](https://github.com/MegaMek/megamek/files/1132810/megamek.common.actions.WeaponAttackAction.toHit-roundstart.gz)

**Comment by HammerGS** [comment]
NPE from the Log:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:291)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:278)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:265)
	at megamek.client.ui.swing.FiringDisplay.getNextTarget(FiringDisplay.java:1113)
	at megamek.client.ui.swing.FiringDisplay.jumpToTarget(FiringDisplay.java:1133)
	at megamek.client.ui.swing.FiringDisplay.actionPerformed(FiringDisplay.java:2215)

**Comment by neoancient** [comment]
I could not reproduce the NPE in `WeaponAttackAction` in multiple attempts, but I believe that the reason the server stopped responding is because it is trying to crater off-board hexes if one of the DropShips at the edge of the map crashes:

Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.server.Server.processCrash(Server.java:6139)
	at megamek.server.Server.resolveControl(Server.java:20572)
	at megamek.server.Server.resolveControlRolls(Server.java:20437)
	at megamek.server.Server.prepareForPhase(Server.java:2502)
	at megamek.server.Server.changePhase(Server.java:2329)
	at megamek.server.Server.endCurrentPhase(Server.java:2988)
	at megamek.server.Server.changePhase(Server.java:2338)
	at megamek.server.Server.endCurrentPhase(Server.java:2967)
	at megamek.server.Server.checkReady(Server.java:2108)
	at megamek.server.Server.handle(Server.java:29965)
	at megamek.server.Server$PacketPump.run(Server.java:355)

**Comment by SirMegaV** [comment]
Strange. I managed to repeat the error twice before posting. Maybe both
times the dropship crashed.  Further note, if I didn't shoot at all, it can
proceed as normal.
