### ISSUE TITLE
Plasmashell repeatedly crashing in Megamek Games

### ISSUE THREAD

**Issue by Algebro7** [MegaMek/megamek#5737]
### Environment
0.49.20
Linux (KDE Plasma DE)
OpenJDK Runtime Environment (build 17.0.11+9)

### Description
This issue only seems to occur in Megamek instances launched by MekHQ--I've not been able to replicate the problem when launching Megamek directly.

At random points during scenarios in Megamek, plasmashell will repeatedly crash and spam me with popups. I can click past them/ignore them and continue playing the game but it's unfortunately very annoying. Someone else in discord mentioned they have the same problem (plasma 6?).

It's somewhat random but appears to occur more often in certain workflows than others. For instance, opening the client settings and clicking around can cause it, along with other modals.

The crash reports from plasmashell aren't super helpful but here is one example excerpt:

```Thread 77 (Thread 0x75f2764006c0 (LWP 23650)):
#0  0x000075f2bc2a34e9 in ?? () from /usr/lib/libc.so.6
#1  0x000075f2bc2a5ed9 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x000075f2ad29d3ee in ?? () from /usr/lib/dri/radeonsi_dri.so
#3  0x000075f2ad27b19c in ?? () from /usr/lib/dri/radeonsi_dri.so
#4  0x000075f2ad29d31d in ?? () from /usr/lib/dri/radeonsi_dri.so
#5  0x000075f2bc2a6ded in ?? () from /usr/lib/libc.so.6
#6  0x000075f2bc32a0dc in ?? () from /usr/lib/libc.so.6
```

The latest video/mesa drivers are installed, in this case linux-firmware for the open source AMD drivers.

**Comment by HexagonalVortex** [comment]
(Other user from Discord here)

AMD based system 
Fedora 40 / KDE Plasma 6.1.2

My system reliably produces plasmashell crashes when MM generates confirmation pop-ups (turning on pavement, supercharger activation, save units on exit, etc.), and less reliably when target selection dialogs open up. When MM is launched directly from the command line via mm-startup, and the same conditions are generated, no plasmashell crashes occur.

**Comment by repligator** [comment]
50.00 (Developmental)
Java 17
Kubuntu Linux
KDE Plasma 5.24.7
Intel/NVIDIA (Driver 535)

I have _not_ encountered this issue in MM (launched from MHQ or otherwise).

**Comment by HexagonalVortex** [comment]
I also did not encounter this issue on Fedora 39/KDE Plasma 5.x on my same AMD based system, on any version of MM between 0.49.18 and 0.49.20. It is new since Plasma 6.x. 

Further testing indicates version 0.49.18 also experiences the same issue under Plasma 6.x, crashes when MM is launched from MHQ, but no crashes when launched directly. Java version seems to have no imact; openjdk11 from Fedora repos, as well as java 11, 17, and 21 from the Adoptium repos all show same behavior. 

The behavior may be Plasma 6.x induced, but it is odd that crashes happen when MM is launched via MHQ and not from the command line directly.

**Comment by HexagonalVortex** [comment]
Update: Downloaded recent 0.50.0 development release. Launched several MM games from MHQ without issue. Launched an older 0.50.0-SNAPSHOT version and the plasma shell crashes occurred. When re-launching the 0.50.0 development release, MM confirmation windows resulted in plasma shell crashes again.

**Comment by Algebro7** [comment]
I did some testing today to try and see if this stemmed from a Java Exception and unfortunately it does not--no Java exceptions were caught when the plasmashell crash occurred. I'm not really sure how to continue to track this down.

**Comment by HexagonalVortex** [comment]
Initial testing on Plasma 6.2 has not yet resulted in a plasmashell crash from popup windows. I have only tested 1 case (Aero over thrusting in atmosphere confirmation dialog), but that one case had previously reliably crashed plasmashell. I have closed and relaunched mekhq twice without issue, and powercycled the laptop and tried again. No crashes. @Algebro7, so far Plasma 6.2 has resolved this issue for me. Have you had a chance to test with Plasma 6.2?

**Comment by Algebro7** [comment]
I took several months off, distro hopped to a Fedora variant (still with KDE plasma) and I have not seen this issue. Obviously there are a lot of variables but I think we're probably good to close this.
