### ISSUE TITLE
49.19.1 Crash on Targeting AeroSpace or VTOL

### ISSUE THREAD

**Issue by strategoslevel3** [MegaMek/megamek#5781]
Playing MekHQ ATB. When it launched into MegaMek another player joined. When I tried to target AeroSpace or VTOL enemy units the game froze. The crash was repeatable, after reload.

[megamek.log](https://github.com/user-attachments/files/16355050/megamek.log)

**Comment by HammerGS** [comment]
A few things in here. 

```
megamek.common.MechFileParser.<init>(MechFileParser.java:48) - 
java.lang.NullPointerException
	at megamek.common.Mounted.<init>(Mounted.java:186)
	at megamek.common.InfantryWeaponMounted.<init>(InfantryWeaponMounted.java:46)
	at megamek.common.loaders.BLKInfantryFile.getEntity(BLKInfantryFile.java:103)
	at megamek.common.MechFileParser.parse(MechFileParser.java:157)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:46)
	at megamek.common.MechFileParser.<init>(MechFileParser.java:39)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:784)
	at megamek.common.MechSummaryCache.loadMechsFromDirectory(MechSummaryCache.java:769)
	at megamek.common.MechSummaryCache.checkForChanges(MechSummaryCache.java:257)
	at megamek.common.MechSummaryCache.loadMechData(MechSummaryCache.java:246)
	at megamek.common.MechSummaryCache.lambda$getInstance$0(MechSummaryCache.java:85)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
	

Lots of these.	
```
megamek.common.GameReports.get(GameReports.java:60) - GameReports.get() was asked for reports of a round [5] which it does not posses.
java.lang.RuntimeException
	at megamek.common.GameReports.get(GameReports.java:60)
	at megamek.common.Game.getReports(Game.java:2586)
	at megamek.client.Client.handlePacket(Client.java:1575)
	at megamek.client.Client$1.lambda$packetReceived$0(Client.java:177)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by IllianiCBT** [comment]
I *think* those have been addressed in 49.20. I don’t suppose you have a save with the issue isolated so we can try to reproduce it?

**Comment by strategoslevel3** [comment]
Seems to be a MP issue.  I was hosting.  Tried loading and playing with just me and I'm not getting any errors.  Maybe the scenario map was not transferring

**Comment by strategoslevel3** [comment]
[Round-5-autosave_2024-07-23_23-22-06.sav.gz](https://github.com/user-attachments/files/16355283/Round-5-autosave_2024-07-23_23-22-06.sav.gz)

**Comment by strategoslevel3** [comment]
And then the game crashed completely....
[Round-9-autosave_2024-07-24_00-41-25.sav.gz](https://github.com/user-attachments/files/16355289/Round-9-autosave_2024-07-24_00-41-25.sav.gz)
[megamek.log](https://github.com/user-attachments/files/16355291/megamek.log)

**Comment by repligator** [comment]
Using 49.19.1 I was able to load and play the turn 5 autosave. Also able to target enemy aero/VTOL without issue.
Same for turn 9. This is a very brutal fight though. Multiple large fuel air bombs in an urban environment, fast moving mechs, VTOLs, etc. If it's crashing in singleplayer, could it be a memory issue?
[megamek.log](https://github.com/user-attachments/files/16392816/megamek.log)

**Comment by strategoslevel3** [comment]
Me to. The issue occurred just in multiplayer

Sent from my iPhone

On 26 Jul 2024, at 15:08, Holovis ***@***.***> wrote:

﻿

Using 49.19.1 I was able to load and play the turn 5 autosave. Also able to target enemy aero/VTOL without issue.
Same for turn 9. This is a very brutal fight though. Multiple large fuel air bombs in an urban environment, fast moving mechs, VTOLs, etc. If it's crashing in singleplayer, could it be a memory issue?
megamek.log<https://github.com/user-attachments/files/16392816/megamek.log>
