### ISSUE TITLE
Various Issues from Nightly Build

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#5833]
megamek.MegaMek.initializeLogging(MegaMek.java:147) - Starting MegaMek v0.50.0-SNAPSHOT
    Build Date: 2024-07-30T23:11:48.374868020
    Today: 2024-07-31
    Origin Project: MegaMek
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_US
    Total memory available to MegaMek: 8 GB
    MM Code Revision: 8741736fcb6aeb2fb54e5b7107f24e9d8a2f2760
    MML Code Revision: 16d244e1b28388241d924fc85e77840dbf88e096
    MHQ Code Revision: ed65154d6e9c8c498a0c13754e847a0816c98d2f

[megamek.log](https://github.com/user-attachments/files/16443012/megamek.log)

```
02:00:28,881 ERROR [megamek.client.AbstractClient] {AWT-EventQueue-0}
megamek.client.AbstractClient.handlePacket(AbstractClient.java:346) - Failed to parse Packet command SENDING_ENTITIES
java.lang.NullPointerException: Cannot invoke "java.util.Map.values()" because "this.carriedObjects" is null
	at megamek.common.Entity.getDistinctCarriedObjects(Entity.java:2863)
	at megamek.client.ui.swing.tooltip.UnitToolTip.carriedCargo(UnitToolTip.java:1852)
	at megamek.client.ui.swing.tooltip.UnitToolTip.getEntityTipTable(UnitToolTip.java:169)
	at megamek.client.ui.swing.tooltip.UnitToolTip.lobbyTip(UnitToolTip.java:55)
	at megamek.client.ui.swing.lobby.MekTableModel.addCellData(MekTableModel.java:191)
	at megamek.client.ui.swing.lobby.MekTableModel.addUnit(MekTableModel.java:164)
	at megamek.client.ui.swing.lobby.ChatLounge.refreshMekTable(ChatLounge.java:1304)
	at megamek.client.ui.swing.lobby.ChatLounge.refreshEntities(ChatLounge.java:1251)
	at megamek.client.ui.swing.lobby.ChatLounge.gameEntityNew(ChatLounge.java:1678)
	at megamek.common.event.GameEntityNewEvent.fireEvent(GameEntityNewEvent.java:62)
	at megamek.common.AbstractGame.fireGameEvent(AbstractGame.java:174)
	at megamek.common.Game.processGameEvent(Game.java:744)
	at megamek.common.Game.setEntitiesVector(Game.java:808)
	at megamek.client.Client.receiveEntities(Client.java:472)
	at megamek.client.Client.handleGameSpecificPacket(Client.java:926)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:340)
	at megamek.client.AbstractClient$1.lambda$packetReceived$0(AbstractClient.java:495)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

```
02:00:29,205 ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$1(MegaMek.java:95) - Uncaught java.lang.IndexOutOfBoundsException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at megamek.client.ui.swing.lobby.MekTableModel.getValueAt(MekTableModel.java:120)
	at java.desktop/javax.swing.JTable.getValueAt(Unknown Source)
	at java.desktop/javax.swing.JTable.prepareRenderer(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at com.formdev.flatlaf.ui.FlatTableUI.paint(FlatTableUI.java:539)
```

Multiple ones of these
```
02:18:51,667 ERROR [megamek.common.GameReports] {AWT-EventQueue-0}
megamek.common.GameReports.get(GameReports.java:65) - GameReports.get() was asked for reports of round -1 which it does not have
java.lang.RuntimeException
	at megamek.common.GameReports.get(GameReports.java:66)
	at megamek.common.Game.getReports(Game.java:2501)
	at megamek.client.Client.handleGameSpecificPacket(Client.java:940)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:340)
	at megamek.client.AbstractClient$1.lambda$packetReceived$0(AbstractClient.java:495)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
```

02:19:00,325 ERROR [megamek.client.bot.princess.PathEnumerator] {Princess-precognition (West)}
```
megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:305) - 
java.lang.IllegalArgumentException: Entity invalid. ID 7
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:578)
	at megamek.common.MovePath.addStep(MovePath.java:375)
	at megamek.common.MovePath.addStep(MovePath.java:267)
	at megamek.common.MovePath.addStep(MovePath.java:175)
	at megamek.common.BulldozerMovePath.addStep(BulldozerMovePath.java:80)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.generateChildNodes(DestructionAwareDestinationPathfinder.java:171)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:106)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:46)
	at megamek.client.bot.princess.PathEnumerator.updateLongRangePaths(PathEnumerator.java:368)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:290)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:397)
	at java.base/java.lang.Thread.run(Unknown Source)
```
	
Mulitple	
```
02:19:03,624 ERROR [megamek.client.bot.princess.Princess] {East Turn 13 Calc Thread}
megamek.client.bot.princess.Princess.continueMovementFor(Princess.java:2153) - MP is now null!
java.lang.NullPointerException: Cannot invoke "megamek.common.MoveStep.toString()" because the return value of "java.util.Enumeration.nextElement()" is null
	at megamek.common.MovePath.toString(MovePath.java:150)
	at java.base/java.lang.String.valueOf(Unknown Source)
	at java.base/java.lang.StringBuilder.append(Unknown Source)
	at megamek.client.bot.princess.PathRanker.validatePaths(PathRanker.java:160)
	at megamek.client.bot.princess.PathRanker.rankPaths(PathRanker.java:72)
	at megamek.client.bot.princess.Princess.continueMovementFor(Princess.java:2127)
	at megamek.client.bot.princess.Princess.calculateMoveTurn(Princess.java:1898)
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:524)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:487)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:65)
	at java.base/java.lang.Thread.run(Unknown Source)
```
	
Multiple
```
02:19:03,624 ERROR [megamek.client.bot.BotClient] {East Turn 13 Calc Thread}
megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:562) - 
java.lang.NullPointerException: Cannot invoke "megamek.common.MovePath.getEntity()" because "mp" is null
	at megamek.client.bot.BotClient.calculateMyTurnWorker(BotClient.java:527)
	at megamek.client.bot.BotClient.calculateMyTurn(BotClient.java:487)
	at megamek.client.bot.BotClient$CalculateBotTurn.run(BotClient.java:65)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Lots of these
```
02:20:02,896 ERROR [megamek.client.bot.princess.Precognition] {AWT-EventQueue-0}
megamek.client.bot.princess.Precognition.handlePacket(Precognition.java:294) - Attempted to parse unknown PacketCommand: UPDATE_GROUND_OBJECTS
```

**Comment by SJuliez** [comment]
Marking this as Princess because the remaining issues are mostly Princess-related
