### ISSUE TITLE
50.00 Nightly - Hard Crash - MM just closed/disappeared when I was zooming out while bot v bot running.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/megamek#5869]
I was just zooming out with mouse wheel like I have done many times on battles with many more mapsheets and entities.  Game just disappeared.  No message, no freeze, no nothing.  Just poof - gone.  Bots were running bot v bot.

Base save, autosave, and log.  I will try to repeat later.  Primary player is "Test"

[Round-1-autosave_2024-08-06_21-52-51.sav.gz](https://github.com/user-attachments/files/16517671/Round-1-autosave_2024-08-06_21-52-51.sav.gz)
[Pathing3OpenDefault5.sav.gz](https://github.com/user-attachments/files/16517672/Pathing3OpenDefault5.sav.gz)
[logs.zip](https://github.com/user-attachments/files/16517678/logs.zip)

**Comment by Thom293** [comment]
Actually - this is from this artifact here.  Not the main nightly build.  https://github.com/MegaMek/megamek/actions/runs/10275183405

**Comment by Thom293** [comment]
And now I have these two files in my base folder, which I dont recall ever seeing before.  What are they?  
![image](https://github.com/user-attachments/assets/87fef3d7-dea2-4e8b-ae64-2a58c31a28b2)

**Comment by rjhancock** [comment]
Best guess, Sentry related.

**Comment by Thom293** [comment]
But I have it turned off...

**Comment by rjhancock** [comment]
Sentry reporting is turned off. Sentry will still collect data and just store it locally/discard it. Nothing is being sent and will be deleted when disabled.

**Comment by Thom293** [comment]
Me no likey...

**Comment by rjhancock** [comment]
Nothing is being sent. It all stays inside that folder and is discarded in the end.

**Comment by Thom293** [comment]
Me no likey...

**Comment by rjhancock** [comment]
There is nothing amiss going on. Those are temp files that Sentry uses when capturing errors. With Sentry disabled, it will discard them when done. Nothing is being transmitted with our your explicit consent. Nothing is being done illicitly. Seriously.

**Comment by Thom293** [comment]
Different build, same crash.  (Build from 8/8 instead of 8/6).  
https://github.com/MegaMek/megamek/actions/runs/10311560863

Game just disappears.  I wasnt even scrolling out this time.  Just a Hard Crash game disappears completely.  2 new files again created and saved in MM folder.

[Round-0-autosave_2024-08-08_23-02-49.sav.gz](https://github.com/user-attachments/files/16556008/Round-0-autosave_2024-08-08_23-02-49.sav.gz)
[Pathing3OpenDefault5EDGE.sav.gz](https://github.com/user-attachments/files/16556009/Pathing3OpenDefault5EDGE.sav.gz)
[logs.zip](https://github.com/user-attachments/files/16556011/logs.zip)

![image](https://github.com/user-attachments/assets/674dcf3e-68fe-4359-b033-ba52cad8bcbb)

**Comment by IllianiCBT** [comment]
From the logs:

Lots of this first one:
```
22:49:34,943 ERROR [megamek.client.ui.swing.boardview.BoardView] {AWT-EventQueue-0}
megamek.client.ui.swing.boardview.BoardView.draw(BoardView.java:842) - Error drawing background image. Raster Bounds: 0.00, 0.00, width:447.00, height:447.00, Attempted Draw Coordinates: -1, 143, width:448, height:304
```

A couple instances of this:
```
22:49:41,544 ERROR [megamek.client.bot.princess.PathEnumerator] {Princess-precognition (East)}
megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:305) - 
java.lang.IllegalArgumentException: Entity invalid. ID 8
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:572)
	at megamek.common.MovePath.addStep(MovePath.java:383)
	at megamek.common.MovePath.addStep(MovePath.java:275)
	at megamek.common.MovePath.addStep(MovePath.java:183)
	at megamek.common.BulldozerMovePath.addStep(BulldozerMovePath.java:80)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.generateChildNodes(DestructionAwareDestinationPathfinder.java:174)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:114)
	at megamek.common.pathfinder.DestructionAwareDestinationPathfinder.findPathToCoords(DestructionAwareDestinationPathfinder.java:51)
	at megamek.client.bot.princess.PathEnumerator.updateLongRangePaths(PathEnumerator.java:368)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesForWorker(PathEnumerator.java:290)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:127)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:400)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Thom293** [comment]
Next game, it just freezes.  No crash.  Says "Waiting to begin pre-movement" at bottom.  Tried to kick and replace bots, but that didnt work, also it appears "replace bot" option is now missing.  Not sure exactly what to push.  I tried both dropdown and button on right.  Did not work.  

I presume this is related to pathing.  No rush.  Just whenever its fixed let me know and Ill test again.  

Another Oddity.  The round report shows game froze n turn 5.  but in my save folder, I have autosaves from turn 16-18.  No idea.  Maybe log got too big and lagged everything out?

![image](https://github.com/user-attachments/assets/4707b700-b8ad-45af-9d92-e6288d8bd940)


I had changed log level to debug before game.  log so big it cannot be opened in notepad or Word, but here it is, just in case.  

[savegames.zip](https://github.com/user-attachments/files/16556280/savegames.zip)


[logs.zip](https://github.com/user-attachments/files/16556187/logs.zip)

**Comment by Thom293** [comment]
Wrong log posted.  Correct Log so big it cant even be uploaded.  52MB.  Here is just the gamelog instead.  I will turn off debug logging.
[gamelog.zip](https://github.com/user-attachments/files/16556311/gamelog.zip)

**Comment by Thom293** [comment]
Again.  But - Changed logging to info level.  So I have a log.  Another "Just disappeared" type.  Im assuming this is enough info. 

Also the new files have doubled, and I presume will increase in count each time there is a crash.... 

![image](https://github.com/user-attachments/assets/11b665aa-8063-4a32-a8f0-4965c409bc9f)


[savegames.zip](https://github.com/user-attachments/files/16556497/savegames.zip)

[logs.zip](https://github.com/user-attachments/files/16556465/logs.zip)

**Comment by rjhancock** [comment]
Please test again on 50.04 to see if this is still an issue.
