### ISSUE TITLE
Error Creating Custom SPAs

### ISSUE THREAD

**Issue by honestaly** [MegaMek/megamek#5993]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Following the directions to add a custom SPA I modified the configuration files and it causes MekHQ to crash on loading or creating a campaign.

### Steps to Reproduce

1. Add this to customspa.xml in the universe folder
`	<option name="alpha_strike_antogonizer">
		<group>&L3;</group>
		<type>&BOOLEAN;</type>
	</option>`
	
2. add this to the end of defaultspa.xml in the same folder
`	<ability>
        <lookupName>alpha_strike_antagonizer</lookupName>
		<displayName>Antagonizer (AlphaStrike)</displayName>
		<desc>Antagonize Opponents Pg 92 Alpha Strike Commanders Edition</desc>
        <xpCost>10</xpCost>
        <skillPrereq>
            <skill>Piloting/Mech::Regular</skill>
		</skillPrereq>
    </ability>`	

3. make sure both files have a blank line after the end xml tag.
4. launched MekHQ 50.0 and tried to create a new campaign or load a campaign and got this error.
    19:41:46,247 ERROR [mekhq.campaign.personnel.CustomOption] {SwingWorker-pool-2-thread-1}
mekhq.campaign.personnel.CustomOption.generateInstanceFromXML(CustomOption.java:172) - Error parsing custom ability alpha_strike_antogonizer
java.lang.NumberFormatException: For input string: ""
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
    at java.base/java.lang.Integer.parseInt(Integer.java:678)
    at java.base/java.lang.Integer.parseInt(Integer.java:786)
    at mekhq.campaign.personnel.CustomOption.generateInstanceFromXML(CustomOption.java:151)

### Operating System *

Windows 11

### Java Version *

17.0.11

### MegaMek Suite Version *

v0.50.0

### Attach Files

[customspa.zip](https://github.com/user-attachments/files/16987159/customspa.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by honestaly** [comment]
`	<option name="alpha_strike_antogonizer">
		<group>&L3;</group>
		<type>&BOOLEAN;</type>
	</option>`
