### ISSUE TITLE
[0.50.01 HEAD 2024-10-08] Wreckage drawing on top of active mechs

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/megamek#6081]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

The COM-2D appears to be under the wreckage in 0518.
![2024-10-09_102157](https://github.com/user-attachments/assets/61e7330a-5908-4f3b-908f-ee9f46aae88a)

### Steps to Reproduce

Unclear aside from killing something and standing on its corpse, but I've included the save where this happened.

### Operating System *

Linux

### Java Version *

17.0.12

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

0.50.01 HEAD 2024-10-08

### Attach Files

18:21:52,874 INFO  [megamek.MegaMek] {main}
megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.1-SNAPSHOT
    Build Date: 2024-10-08T18:17:18.371814431
    Today: 2024-10-08
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Linux 6.11.2-202.fsync.fc40.x86_64 (amd64)
    System Locale: en_US
    Total memory available to MegaMek: 8 GB
    MM Code Revision: e7d09b5391c560f7f47ff03222ef17c83ffdc038
    MML Code Revision: 446bd8d9c7e28bfdf49d35f312d838c44e16941a
    MHQ Code Revision: c38adf7426b55e066fb14cd1f836bb53f69984fa

[logs.zip](https://github.com/user-attachments/files/17315354/logs.zip)
[drawing-on-top-of.sav.gz](https://github.com/user-attachments/files/17315367/drawing-on-top-of.sav.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by WeaverThree** [comment]
Ugh, I tried loading this save file and I get an exception

```
[Fatal Error] :9176:48: XML document structures must start and end within the same entity.
08:29:03,976 ERROR [megamek.client.ui.swing.MegaMekGUI] {AWT-EventQueue-0}
megamek.client.ui.swing.MegaMekGUI.loadGame(MegaMekGUI.java:627) - Error: unable to load game file "/home/weaver/.local/MekHQ-0.50.01-SNAPSHOT-WVR-2024-10-08/savegames/drawing-on-top-of.sav.gz"
org.xml.sax.SAXParseException; lineNumber: 9176; columnNumber: 48; XML document structures must start and end within the same entity.
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	at megamek.client.ui.swing.MegaMekGUI.loadGame(MegaMekGUI.java:601)
	at megamek.client.ui.swing.MegaMekGUI.lambda$new$0(MegaMekGUI.java:1050)
```
