### ISSUE TITLE
Can't create an ImageOutputStream - From Casual Joker Stream Oct 12/2024

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/megamek#6099]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

During the MekHQ resolution phase lots of empty units. 

https://www.twitch.tv/videos/2274578361?t=04h21m11s

From the logs
Numerous ones of this
```
20:45:25,246 ERROR [megamek.client.ui.swing.tooltip.PilotToolTip] {AWT-EventQueue-0}
megamek.client.ui.swing.tooltip.PilotToolTip.crewPortraits(PilotToolTip.java:221) - 
javax.imageio.IIOException: Can't create an ImageOutputStream!
	at java.desktop/javax.imageio.ImageIO.write(Unknown Source)
	at megamek.client.ui.swing.tooltip.PilotToolTip.crewPortraits(PilotToolTip.java:212)
	at megamek.client.ui.swing.tooltip.PilotToolTip.getPilotTip(PilotToolTip.java:88)
	at megamek.client.ui.swing.tooltip.PilotToolTip.getPilotTipDetailed(PilotToolTip.java:61)
	at megamek.client.ui.swing.tooltip.PilotToolTip.lobbyTip(PilotToolTip.java:51)
	at megamek.client.ui.swing.lobby.MekTableModel.addCellData(MekTableModel.java:193)
	at megamek.client.ui.swing.lobby.MekTableModel.addUnit(MekTableModel.java:164)
	at megamek.client.ui.swing.lobby.ChatLounge.refreshMekTable(ChatLounge.java:1304)
	at megamek.client.ui.swing.lobby.ChatLounge.refreshEntities(ChatLounge.java:1251)
	at megamek.client.ui.swing.lobby.ChatLounge.gameEntityNew(ChatLounge.java:1678)
	at megamek.common.event.GameEntityNewEvent.fireEvent(GameEntityNewEvent.java:62)
	at megamek.common.AbstractGame.fireGameEvent(AbstractGame.java:179)
	at megamek.common.Game.processGameEvent(Game.java:739)
	at megamek.common.Game.addEntities(Game.java:1130)
	at megamek.common.Game.replaceUnits(Game.java:1253)
	at megamek.client.AbstractClient.receiveUnitReplace(AbstractClient.java:305)
	at megamek.client.AbstractClient.handleGameIndependentPacket(AbstractClient.java:420)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:340)
```

and this

```
20:45:25,255 ERROR [megamek.client.ui.swing.tooltip.PilotToolTip] {AWT-EventQueue-0}
megamek.client.ui.swing.tooltip.PilotToolTip.crewPortraits(PilotToolTip.java:221) - 
javax.imageio.IIOException: Can't create an ImageOutputStream!
	at java.desktop/javax.imageio.ImageIO.write(Unknown Source)
	at megamek.client.ui.swing.tooltip.PilotToolTip.crewPortraits(PilotToolTip.java:212)
	at megamek.client.ui.swing.tooltip.PilotToolTip.getPilotTip(PilotToolTip.java:88)
	at megamek.client.ui.swing.tooltip.PilotToolTip.getPilotTipDetailed(PilotToolTip.java:61)
	at megamek.client.ui.swing.tooltip.PilotToolTip.lobbyTip(PilotToolTip.java:51)
	at megamek.client.ui.swing.lobby.MekTableModel.addCellData(MekTableModel.java:193)
	at megamek.client.ui.swing.lobby.MekTableModel.addUnit(MekTableModel.java:164)
	at megamek.client.ui.swing.lobby.ChatLounge.refreshMekTable(ChatLounge.java:1304)
	at megamek.client.ui.swing.lobby.ChatLounge.refreshEntities(ChatLounge.java:1251)
	at megamek.client.ui.swing.lobby.ChatLounge.gameEntityNew(ChatLounge.java:1678)
	at megamek.common.event.GameEntityNewEvent.fireEvent(GameEntityNewEvent.java:62)
	at megamek.common.AbstractGame.fireGameEvent(AbstractGame.java:179)
	at megamek.common.Game.processGameEvent(Game.java:739)
	at megamek.common.Game.addEntities(Game.java:1130)
	at megamek.common.Game.replaceUnits(Game.java:1253)
	at megamek.client.AbstractClient.receiveUnitReplace(AbstractClient.java:305)
	at megamek.client.AbstractClient.handleGameIndependentPacket(AbstractClient.java:420)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:340)
	at megamek.client.AbstractClient$1.lambda$packetReceived$0(AbstractClient.java:496)
```

and finally 

```
21:03:24,337 ERROR [megamek.client.bot.BotClient] {Independent Primary Opfor Turn 6 Calc Thread}
megamek.client.bot.BotClient.getFirstValidCoords(BotClient.java:614) - Returning no deployment position; THIS IS BAD!
```

### Steps to Reproduce

Not Available

### Operating System *

Windows 11

### Java Version *

    Java Vendor: Eclipse Adoptium     Java Version: 17.0.12

### MegaMek Suite Version *

v0.50.0

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17356318/mekhq.log)

This MegaMek log is massive when unzipped
[megamek.zip](https://github.com/user-attachments/files/17356331/megamek.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by SJuliez** [comment]
@HammerGS I think there should be an end-of-game MUL file, right? Can we get that? The logs don't show anything why the resolution would be empty, I think.

**Comment by HammerGS** [comment]
> @HammerGS I think there should be an end-of-game MUL file, right? Can we get that? The logs don't show anything why the resolution would be empty, I think.

Yeah, but at this point I suspect's its not available but I'll ask.

**Comment by Scoppio** [comment]
Either this is fixed, or is outdated now.
