### ISSUE TITLE
Uncaught java.lang.NullPointException--no idea what caused it

### ISSUE THREAD

**Issue by nivenhuman** [MegaMek/megamek#6171]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

![image](https://github.com/user-attachments/assets/96ee98ee-a877-496a-b7e3-eebad7b89271)
I was playing against Princess when the game froze after ending physical combat phase and I got this popup. Here are the requested logs and game file. I was not using any custom units.
[Round-15-autosave_2024-11-02_18-12-34.sav.gz](https://github.com/user-attachments/files/17608873/Round-15-autosave_2024-11-02_18-12-34.sav.gz)

### Steps to Reproduce

Unclear what exactly triggered this.

### Operating System *

Windows 10

### Java Version *

17.0.12

### MegaMek Suite Version *

v0.49.19.1

### Attach Files

[logs.zip](https://github.com/user-attachments/files/17608893/logs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by kuronekochomusuke** [comment]
18:14:35,872 ERROR [megamek.MegaMek] {Packet Pump}
megamek.MegaMek.lambda$main$0(MegaMek.java:63) - Uncaught Exception Detected
java.lang.ClassCastException: class megamek.common.MiscType cannot be cast to class megamek.common.AmmoType (megamek.common.MiscType and megamek.common.AmmoType are in unnamed module of loader 'app')
	at megamek.common.weapons.WeaponHandler.<init>(WeaponHandler.java:1759)
	at megamek.common.weapons.infantry.InfantryWeaponHandler.<init>(InfantryWeaponHandler.java:40)
	at megamek.common.weapons.infantry.InfantryWeapon.getCorrectHandler(InfantryWeapon.java:266)
	at megamek.common.weapons.Weapon.fire(Weapon.java:93)
	at megamek.server.GameManager.resolveOnlyWeaponAttacks(GameManager.java:14235)
	at megamek.server.GameManager.endCurrentPhase(GameManager.java:2423)
	at megamek.server.GameManager.changeToNextTurn(GameManager.java:2740)
	at megamek.server.GameManager.endCurrentTurn(GameManager.java:1587)
	at megamek.server.GameManager.receiveAttack(GameManager.java:13238)
	at megamek.server.GameManager.handlePacket(GameManager.java:771)
	at megamek.server.Server.handle(Server.java:1277)
	at megamek.server.Server$PacketPump.run(Server.java:113)
	at java.base/java.lang.Thread.run(Unknown Source)

18:14:39,904 ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$0(MegaMek.java:63) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "megamek.common.Entity.getAlreadyTwisted()" because the return value of "megamek.client.ui.swing.FiringDisplay.ce()" is null
	at megamek.client.ui.swing.FiringDisplay.hexMoused(FiringDisplay.java:2129)
	at megamek.client.ui.swing.boardview.BoardView.processBoardViewEvent(BoardView.java:976)
	at megamek.client.ui.swing.boardview.BoardView.mouseAction(BoardView.java:4923)
	at megamek.client.ui.swing.boardview.BoardView.mouseAction(BoardView.java:4946)
	at megamek.client.ui.swing.boardview.BoardView.mousePressed(BoardView.java:4637)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by kuronekochomusuke** [comment]
fixed by #5573
