### ISSUE TITLE
Error on load of save

### ISSUE THREAD

**Issue by kuronekochomusuke** [MegaMek/megamek#6235]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Meduim.

### Brief Description *

Error on load of save

10:28:19,543 ERROR [megamek.client.ui.swing.lobby.ChatLounge] {AWT-EventQueue-0}
megamek.client.ui.swing.lobby.ChatLounge$ImageLoader.add(ChatLounge.java:3295) - 
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lockInterruptibly(ReentrantLock.java:159)
	at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:372)
	at java.base/java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:332)
	at megamek.client.ui.swing.lobby.ChatLounge$ImageLoader.add(ChatLounge.java:3293)
	at megamek.client.ui.swing.lobby.ChatLounge$BoardNameRenderer.getListCellRendererComponent(ChatLounge.java:3424)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1444)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:653)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1725)
	at java.desktop/javax.swing.JList.getPreferredScrollableViewportSize(JList.java:2461)
	at java.desktop/javax.swing.ViewportLayout.preferredLayoutSize(ViewportLayout.java:100)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1727)
	at java.desktop/javax.swing.ScrollPaneLayout.preferredLayoutSize(ScrollPaneLayout.java:500)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1727)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:476)
	at java.desktop/javax.swing.BoxLayout.minimumLayoutSize(BoxLayout.java:318)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1807)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.minimumLayoutSize(BasicSplitPaneUI.java:1548)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI.getMinimumSize(BasicSplitPaneUI.java:1173)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1805)
	at java.desktop/java.awt.GridLayout.minimumLayoutSize(GridLayout.java:390)
	at java.desktop/java.awt.Container.minimumSize(Container.java:1878)
	at java.desktop/java.awt.Container.getMinimumSize(Container.java:1862)
	at java.desktop/javax.swing.JComponent.getMinimumSize(JComponent.java:1807)
	at java.desktop/javax.swing.BoxLayout.checkRequests(BoxLayout.java:475)
	at java.desktop/javax.swing.BoxLayout.preferredLayoutSize(BoxLayout.java:293)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1727)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateSize(BasicTabbedPaneUI.java:2706)
	at com.formdev.flatlaf.ui.FlatTabbedPaneUI$FlatTabbedPaneLayout.calculateSize(FlatTabbedPaneUI.java:3257)
	at java.desktop/javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.preferredLayoutSize(BasicTabbedPaneUI.java:2675)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1727)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1727)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.getPreferredSizeOfComponent(BasicSplitPaneUI.java:1734)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.getPreferredSizes(BasicSplitPaneUI.java:1987)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.resetToPreferredSizes(BasicSplitPaneUI.java:2023)
	at java.desktop/javax.swing.plaf.basic.BasicSplitPaneUI$BasicHorizontalLayoutManager.layoutContainer(BasicSplitPaneUI.java:1424)
	at java.desktop/java.awt.Container.layout(Container.java:1541)
	at java.desktop/java.awt.Container.doLayout(Container.java:1530)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validate(Container.java:1660)
	at java.desktop/java.awt.CardLayout.show(CardLayout.java:556)
	at megamek.client.ui.swing.ClientGUI.switchPanel(ClientGUI.java:1197)
	at megamek.client.ui.swing.ClientGUI$1.gamePhaseChange(ClientGUI.java:2309)
	at megamek.common.event.GamePhaseChangeEvent.fireEvent(GamePhaseChangeEvent.java:68)
	at megamek.common.AbstractGame.fireGameEvent(AbstractGame.java:196)
	at megamek.common.Game.processGameEvent(Game.java:751)
	at megamek.common.Game.setPhase(Game.java:747)
	at megamek.common.IGame.receivePhase(IGame.java:128)
	at megamek.client.AbstractClient.changePhase(AbstractClient.java:511)
	at megamek.client.Client.changePhase(Client.java:188)
	at megamek.client.AbstractClient.handleGameIndependentPacket(AbstractClient.java:480)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:389)
	at megamek.client.AbstractClient$1.lambda$packetReceived$0(AbstractClient.java:562)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Steps to Reproduce

start new game
add units
add units for princess
save game, while in lobby
load game
load game again, error occurs

### Operating System *

Windows 11

### Java Version *

Java Vendor: Eclipse Adoptium     Java Version: 17.0.11

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

nightly

### Attach Files

[megamek.log](https://github.com/user-attachments/files/17965922/megamek.log)
[load.sav.gz](https://github.com/user-attachments/files/17965924/load.sav.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Scoppio** [comment]
This does not happen anymore and I can atest to that bc this is one of my main ways to work 🤣
