### ISSUE TITLE
12/13 logistics artifact/0.50.02 snapshot - Ejecting immobilized vehicle caused megamek to process the rest of the movement round as a fire phase, but unable to move or fire

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/megamek#6274]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

![image](https://github.com/user-attachments/assets/cec55e2f-f317-41b7-b1b2-ab3f824019c8)
Immediately after ejecting the SRM carrier that had been immobilized, I was unable to move my meks and it read firing phase at the bottom. No unit is able to fire either, firing arcs do not appear and I cannot target the overhead fighter.

### Steps to Reproduce

1. Proceed from round where SRM carrier is disabled
2. Eject next round
3. Meks unable to move, requested/processed as firing phase, including menu, but unable to shoot either - no arcs appear/target never in arc

### Operating System *

Windows 10

### Java Version *

17

### MegaMek Suite Version *

None

### Custom MegaMek Version

12/13 Logistics Overhaul '0.50.02-SNAPSHOT'

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18141151/logs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by HammerGS** [comment]
From the log

```
07:48:40,029 ERROR [megamek.client.ui.swing.lobby.ChatLounge] {AWT-EventQueue-0}
megamek.client.ui.swing.lobby.ChatLounge$ImageLoader.add(ChatLounge.java:3295) - 
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lockInterruptibly(Unknown Source)
	at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(Unknown Source)
	at java.base/java.util.concurrent.LinkedBlockingQueue.put(Unknown Source)
	at megamek.client.ui.swing.lobby.ChatLounge$ImageLoader.add(ChatLounge.java:3293)
	at megamek.client.ui.swing.lobby.ChatLounge$BoardNameRenderer.getListCellRendererComponent(ChatLounge.java:3424)
```

also

```
07:44:49,113 WARN  [megamek.common.MULParser] {SwingWorker-pool-2-thread-1}
megamek.common.MULParser.parse(MULParser.java:413) - XML file lists LRM 5 equipment at location 0.  XML parser expected ammo.
XML file lists LRM 5 equipment at location 0.  XML parser expected ammo.
XML file lists LRM 10 equipment at location 0.  XML parser expected ammo.
XML file lists LRM 10 equipment at location 0.  XML parser expected ammo.
XML file lists Machine Gun equipment at location 0.  XML parser expected ammo.
XML file lists Machine Gun equipment at location 0.  XML parser expected ammo.
XML file lists Searchlight equipment at location 0.  XML parser expected ammo.
```

**Comment by psikomonkie** [comment]
I'm unable to replicate this bug. Ejecting the SRM Carrier in the save allows the movement phase to continue as expected. Attempting to replicate this on a new save didn't have the bug.

**Comment by Scoppio** [comment]
I am closing this issue, as we were sble to vontinue that specific save and it appears to not being reproducible since then
