### ISSUE TITLE
Latest - NPE when trying to get player settings after loading game

### ISSUE THREAD

**Issue by psikomonkie** [MegaMek/megamek#6313]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

NPE when trying to get to Player Settings in a game that was loaded.

Encountered while investigating #6277

### Steps to Reproduce

1. Start a MegaMek game
2. Once in game, save and quit.
3. Load save.
4. Game->Player Settings - NPE

### Operating System *

Windows 11

### Java Version *

17.0.13

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

Latest

### Attach Files

[4.sav.gz](https://github.com/user-attachments/files/18241377/4.sav.gz)

[megamek.log](https://github.com/user-attachments/files/18241381/megamek.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by psikomonkie** [comment]
Reach out to me if you're gonna look into this, I've been looking into this under the suspicion it relates to #6277

**Comment by HammerGS** [comment]
From the  log

```
java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "name" is null
	at megamek.server.ServerBoardHelper.getPossibleGameBoard(ServerBoardHelper.java:112)
	at megamek.client.ui.swing.lobby.PlayerSettingsDialog.setupStartGrid(PlayerSettingsDialog.java:736)
	at megamek.client.ui.swing.lobby.PlayerSettingsDialog.startSection(PlayerSettingsDialog.java:528)
	at megamek.client.ui.swing.lobby.PlayerSettingsDialog.createCenterPane(PlayerSettingsDialog.java:318)
	at megamek.client.ui.baseComponents.AbstractButtonDialog.initialize(AbstractButtonDialog.java:131)
	at megamek.client.ui.swing.lobby.PlayerSettingsDialog.<init>(PlayerSettingsDialog.java:137)
	at megamek.client.ui.swing.ClientGUI.customizePlayer(ClientGUI.java:697)
	at megamek.client.ui.swing.ClientGUI.actionPerformed(ClientGUI.java:865)
	at megamek.client.ui.swing.CommonMenuBar.lambda$actionPerformed$0(CommonMenuBar.java:446)
```
