### ISSUE TITLE
[0.50.2-SNAPSHOT] Spheroid DropShip air to ground attack causes NPE

### ISSUE THREAD

**Issue by stonewall072** [MegaMek/megamek#6324]
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

An NPE is generated with Spheroid DropShips on the ground map when attempting a strike attack against a target along its flight path. Spheroid small craft seem to be unaffected.

### Steps to Reproduce

1. Enable relevant game rules
2. Choose and deploy a DropShip on a ground map
3. Overfly a valid target unit
4. Observe NPE when target unit is selected as target for ground to air attack

### Operating System *

Windows 11

### Java Version *

 17.0.11

### MegaMek Suite Version *

Free Text (type manually)

### Custom MegaMek Version

Latest Nightly

### Attach Files

[megamek.log](https://github.com/user-attachments/files/18270355/megamek.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by stonewall072** [comment]
[BeginningOfFireDropShip.sav.gz](https://github.com/user-attachments/files/18270460/BeginningOfFireDropShip.sav.gz)

Bot name is just Princess

**Comment by kuronekochomusuke** [comment]
multiple error is log

```
12:09:34,526 ERROR [megamek.server.GameManagerSaveHelper] {Packet Pump}
megamek.server.GameManagerSaveHelper.saveGame(GameManagerSaveHelper.java:80) - Unable to save file: savegames\Round-0-autosave_2024-12-29_12-09-34.sav
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.Map$Entry.getValue()" is null
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:96)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:478)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:49)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:80)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:83)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1303)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1292)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1265)
	at megamek.server.GameManagerSaveHelper.saveGame(GameManagerSaveHelper.java:77)
	at megamek.server.AbstractGameManager.saveGame(AbstractGameManager.java:218)
	at megamek.server.AutosaveService.performRollingAutosave(AutosaveService.java:55)
	at megamek.server.totalwarfare.TWPhasePreparationManager.managePhase(TWPhasePreparationManager.java:86)
	at megamek.server.totalwarfare.TWGameManager.prepareForCurrentPhase(TWGameManager.java:1851)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:109)
	at megamek.server.totalwarfare.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:54)
	at megamek.server.totalwarfare.TWGameManager.endCurrentPhase(TWGameManager.java:2007)
	at megamek.server.totalwarfare.TWGameManager.changeToNextTurn(TWGameManager.java:2149)
	at megamek.server.totalwarfare.TWGameManager.executeCurrentPhase(TWGameManager.java:1889)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:116)
	at megamek.server.totalwarfare.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:45)
	at megamek.server.totalwarfare.TWGameManager.endCurrentPhase(TWGameManager.java:2007)
	at megamek.server.totalwarfare.TWGameManager.checkReady(TWGameManager.java:1387)
	at megamek.server.AbstractGameManager.handlePacket(AbstractGameManager.java:63)
	at megamek.server.totalwarfare.TWGameManager.handlePacket(TWGameManager.java:670)
	at megamek.server.Server.handle(Server.java:1378)
	at megamek.server.Server$PacketPump.run(Server.java:138)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

```
2:09:34,624 ERROR [megamek.server.GameManagerSaveHelper] {Packet Pump}
megamek.server.GameManagerSaveHelper.saveGame(GameManagerSaveHelper.java:80) - Unable to save file: savegames\autosave_2024-12-29_12-09-34.sav
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.EnumMap
converter           : com.thoughtworks.xstream.converters.enums.EnumMapConverter
message[1]          : Could not initialize class com.thoughtworks.xstream.converters.enums.EnumMapConverter$Reflections
converter[1]        : com.thoughtworks.xstream.converters.reflection.SerializableConverter
message[2]          : Unable to make private void java.util.EnumMap.readObject(java.io.ObjectInputStream) throws java.io.IOException,java.lang.ClassNotFoundException accessible: module java.base does not "opens java.util" to unnamed module @b9afc07
converter[2]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[3]          : Unable to make field transient java.util.Set java.util.AbstractMap.keySet accessible: module java.base does not "opens java.util" to unnamed module @b9afc07
-------------------------------
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:478)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:49)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:87)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeBareItem(AbstractCollectionConverter.java:94)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:66)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeCompleteItem(AbstractCollectionConverter.java:81)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:80)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:83)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1303)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1292)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1265)
	at megamek.server.GameManagerSaveHelper.saveGame(GameManagerSaveHelper.java:77)
	at megamek.server.AbstractGameManager.saveGame(AbstractGameManager.java:218)
	at megamek.server.AbstractGameManager.autoSave(AbstractGameManager.java:213)
	at megamek.server.totalwarfare.TWPhasePreparationManager.managePhase(TWPhasePreparationManager.java:224)
	at megamek.server.totalwarfare.TWGameManager.prepareForCurrentPhase(TWGameManager.java:1851)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:109)
	at megamek.server.totalwarfare.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:73)
	at megamek.server.totalwarfare.TWGameManager.endCurrentPhase(TWGameManager.java:2007)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:112)
	at megamek.server.totalwarfare.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:54)
	at megamek.server.totalwarfare.TWGameManager.endCurrentPhase(TWGameManager.java:2007)
	at megamek.server.totalwarfare.TWGameManager.changeToNextTurn(TWGameManager.java:2149)
	at megamek.server.totalwarfare.TWGameManager.executeCurrentPhase(TWGameManager.java:1889)
	at megamek.server.AbstractGameManager.changePhase(AbstractGameManager.java:116)
	at megamek.server.totalwarfare.TWPhaseEndManager.managePhase(TWPhaseEndManager.java:45)
	at megamek.server.totalwarfare.TWGameManager.endCurrentPhase(TWGameManager.java:2007)
	at megamek.server.totalwarfare.TWGameManager.checkReady(TWGameManager.java:1387)
	at megamek.server.AbstractGameManager.handlePacket(AbstractGameManager.java:63)
	at megamek.server.totalwarfare.TWGameManager.handlePacket(TWGameManager.java:670)
	at megamek.server.Server.handle(Server.java:1378)
	at megamek.server.Server$PacketPump.run(Server.java:138)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

```
12:10:24,905 ERROR [megamek.client.AbstractClient] {AWT-EventQueue-0}
megamek.client.AbstractClient.handlePacket(AbstractClient.java:398) - Failed to parse Packet command of TURN
java.lang.NullPointerException: Cannot enter synchronized block because "this.modes" is null
	at megamek.common.weapons.lasers.LaserWeapon.getModesCount(LaserWeapon.java:75)
	at megamek.common.Mounted.getModesCount(Mounted.java:232)
	at megamek.common.Mounted.curMode(Mounted.java:258)
	at megamek.common.equipment.WeaponMounted.getCurrentShots(WeaponMounted.java:152)
	at megamek.common.equipment.WeaponMounted.getCurrentHeat(WeaponMounted.java:108)
	at megamek.common.Entity.getHeatInArc(Entity.java:11643)
	at megamek.client.ui.swing.unitDisplay.WeaponPanel.displaySelected(WeaponPanel.java:1577)
	at megamek.client.ui.swing.unitDisplay.WeaponPanel.valueChanged(WeaponPanel.java:2589)
	at java.desktop/javax.swing.JList.fireSelectionValueChanged(JList.java:1831)
	at java.desktop/javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1845)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2232)
	at megamek.client.ui.swing.unitDisplay.WeaponPanel.selectFirstWeapon(WeaponPanel.java:1405)
	at megamek.client.ui.swing.FiringDisplay.refreshAll(FiringDisplay.java:1482)
	at megamek.client.ui.swing.FiringDisplay.selectEntity(FiringDisplay.java:439)
	at megamek.client.ui.swing.FiringDisplay.beginMyTurn(FiringDisplay.java:485)
	at megamek.client.ui.swing.FiringDisplay.gameTurnChange(FiringDisplay.java:1843)
	at megamek.common.event.GameTurnChangeEvent.fireEvent(GameTurnChangeEvent.java:46)
	at megamek.common.AbstractGame.fireGameEvent(AbstractGame.java:196)
	at megamek.common.Game.processGameEvent(Game.java:759)
	at megamek.common.Game.setTurnIndex(Game.java:700)
	at megamek.client.Client.changeTurnIndex(Client.java:1288)
	at megamek.client.Client.handleGameSpecificPacket(Client.java:996)
	at megamek.client.AbstractClient.handlePacket(AbstractClient.java:390)
	at megamek.client.AbstractClient$1.lambda$packetReceived$0(AbstractClient.java:562)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

```
12:10:26,491 ERROR [megamek.MegaMek] {AWT-EventQueue-0}
megamek.MegaMek.lambda$main$1(MegaMek.java:95) - Uncaught java.lang.NullPointerException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.lang.NullPointerException: Cannot enter synchronized block because "this.modes" is null
	at megamek.common.weapons.lasers.LaserWeapon.getModesCount(LaserWeapon.java:75)
	at megamek.common.Mounted.getModesCount(Mounted.java:232)
	at megamek.common.Mounted.curMode(Mounted.java:258)
	at megamek.common.equipment.WeaponMounted.getCurrentShots(WeaponMounted.java:152)
	at megamek.common.equipment.WeaponMounted.getCurrentHeat(WeaponMounted.java:108)
	at megamek.common.Entity.getHeatInArc(Entity.java:11643)
	at megamek.common.actions.WeaponAttackAction.toHitIsImpossible(WeaponAttackAction.java:1560)
	at megamek.common.actions.WeaponAttackAction.toHitCalc(WeaponAttackAction.java:686)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:311)
	at megamek.common.actions.WeaponAttackAction.toHit(WeaponAttackAction.java:302)
	at megamek.client.ui.swing.FiringDisplay.updateTarget(FiringDisplay.java:1597)
	at megamek.client.ui.swing.FiringDisplay.target(FiringDisplay.java:1540)
	at megamek.client.ui.swing.FiringDisplay.hexSelected(FiringDisplay.java:1813)
	at megamek.client.ui.swing.boardview.AbstractBoardView.processBoardViewEvent(AbstractBoardView.java:55)
	at megamek.client.ui.swing.boardview.BoardView.select(BoardView.java:4095)
	at megamek.client.ui.swing.FiringDisplay.hexMoused(FiringDisplay.java:1762)
	at megamek.client.ui.swing.boardview.AbstractBoardView.processBoardViewEvent(AbstractBoardView.java:46)
	at megamek.client.ui.swing.boardview.BoardView.mouseAction(BoardView.java:4211)
	at megamek.client.ui.swing.boardview.BoardView.mouseAction(BoardView.java:4243)
	at megamek.client.ui.swing.boardview.BoardView.mouseReleased(BoardView.java:3972)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
