### ISSUE TITLE
Princess continues to stop at one point.

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/megamek#645]
I've tried multiple times, every time princess crashes at one point (after I move the Hellbringer B - II). I've tried replacing Princess in the game (-c:ESCAPE) I've tried connecting as a bot both at the start of the turn and at the point where she stops. (Update: latest she crashed at the beginning of the turn.)
[Bug.zip](https://github.com/MegaMek/megamek/files/1293532/Bug.zip)

**Comment by pjfarland** [comment]
Another Update, I tried taking over control of the bot's side, it wouldn't let me take over the unit or whatever caused the problem (which at this point started earlier). I had to issue a skip command.

**Comment by HammerGS** [comment]
Relevant NPE

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at megamek.client.ui.swing.MovementDisplay.updateConvertModeButton(MovementDisplay.java:2516)
	at megamek.client.ui.swing.MovementDisplay.hexMoused(MovementDisplay.java:1907)
	at megamek.client.ui.swing.boardview.BoardView1.processBoardViewEvent(BoardView1.java:1114)
	at megamek.client.ui.swing.boardview.BoardView1.mouseAction(BoardView1.java:4946)
	at megamek.client.ui.swing.boardview.BoardView1.mouseAction(BoardView1.java:4972)
	at megamek.client.ui.swing.boardview.BoardView1.mouseReleased(BoardView1.java:4711)
