### ISSUE TITLE
NPE Starting a Game with Certain Bombs Loaded on a Fighter

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/megamek#675]
Tag, AS, LAA are the only (implemented) bombs affected.  I'll fix this one.

**Comment by mkerensky** [comment]
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.common.Mounted.<init>(Mounted.java:197)
	at megamek.common.Entity.addBomb(Entity.java:3332)
	at megamek.common.IBomber.applyBombs(IBomber.java:120)

**Comment by mkerensky** [comment]
The IBomber line 120 seems to be the important part here. The EquipmentType.get statement there returns null for the 3 affected bomb types, but not the others.  I'm getting lost with the references where equipmentType looks at BombType and WeaponType and they all try to match names and weapons to the types.

**Comment by mkerensky** [comment]
Nevermind. Fixed.  Thanks @neoancient
