### ISSUE TITLE
NPE when completing mine deployment

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#846]
Relevant log file and save game located here: https://www.megamek.org/bb/thread-2490.html

Relevant-looking exception: 
Exception in thread "Packet Pump" java.lang.NullPointerException
	at megamek.server.Server.endCurrentTurn(Server.java:2457)
	at megamek.server.Server.receiveDeployMinefields(Server.java:13582)
	at megamek.server.Server.handle(Server.java:31825)
	at megamek.server.Server$PacketPump.run(Server.java:368)

**Comment by NickAragua** [comment]
Looks like PR #847 fixes this issue
