### ISSUE TITLE
43.7 RC1 Game Stop

### ISSUE THREAD

**Issue by SnyderPhilip** [MegaMek/megamek#885]
So, this is an odd one.  ATB, with a DropShip flying support.  The DropShip gets shot down and crash lands.  Everything behaves normally until the turn the Bot swarms to the downed DropShip.  The Fire Phase proceeds normally until I click done with my last unit.  And then nothing.  The game simply ceases, it acts as though I never clicked done, but it wont let me continue.  There is nothing in the error log, there is nothing to indicate that anything is amiss, except the game will not continue.  I assume that the result of the Fire Phase would be the destruction of the DropShip, and that might be causing the problem.
[autosave.sav.zip](https://github.com/MegaMek/megamek/files/1662513/autosave.sav.zip)

**Comment by BLOODWOLF333** [comment]
Post the logfile please along with the player name so we can load your saved game.

**Comment by SnyderPhilip** [comment]
1st Kentwood Cavaliers
[megameklog.txt](https://github.com/MegaMek/megamek/files/1662526/megameklog.txt)

**Comment by BLOODWOLF333** [comment]
Line 9,456
`11:32:46,811 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Word of Blake)} 
Entity invalid. ID 75
java.lang.IllegalArgumentException: Entity invalid. ID 75
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:455)
	at megamek.common.MovePath.addStep(MovePath.java:474)
	at megamek.common.MovePath.addStep(MovePath.java:255)
	at megamek.common.MovePath.addStep(MovePath.java:167)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:339)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:276)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)`

Line 10,137:
`11:48:05,961 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Word of Blake)} 
Entity invalid. ID 76
java.lang.IllegalArgumentException: Entity invalid. ID 76
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:455)
	at megamek.common.MovePath.addStep(MovePath.java:474)
	at megamek.common.MovePath.addStep(MovePath.java:255)
	at megamek.common.MovePath.addStep(MovePath.java:167)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:370)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:276)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)`

LIne 12,522
`java.lang.IllegalArgumentException: Entity invalid. ID 85
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:455)
	at megamek.common.MovePath.addStep(MovePath.java:474)
	at megamek.common.MovePath.addStep(MovePath.java:255)
	at megamek.common.MovePath.addStep(MovePath.java:167)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:370)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:290)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)`

Line 13,146
`02:07:25,454 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Word of Blake)} 
Entity invalid. ID 91
java.lang.IllegalArgumentException: Entity invalid. ID 91
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:455)
	at megamek.common.MovePath.addStep(MovePath.java:474)
	at megamek.common.MovePath.addStep(MovePath.java:255)
	at megamek.common.MovePath.addStep(MovePath.java:167)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:336)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:276)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)`

Line 18,653
`01:11:14,383 ERROR [megamek.common.pathfinder.LongestPathFinder] {Princess-precognition (Word of Blake Force #2)} 
Entity invalid. ID 98
java.lang.IllegalArgumentException: Entity invalid. ID 98
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:455)
	at megamek.common.MovePath.addStep(MovePath.java:474)
	at megamek.common.MovePath.addStep(MovePath.java:255)
	at megamek.common.MovePath.addStep(MovePath.java:167)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:363)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:276)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)`

Line 22,644 & 22,654
`java.lang.NullPointerException
	at megamek.common.pathfinder.AeroGroundPathFinder.ForwardToTheEnd(AeroGroundPathFinder.java:413)
	at megamek.common.pathfinder.AeroGroundPathFinder.GenerateAllPaths(AeroGroundPathFinder.java:343)
	at megamek.common.pathfinder.AeroGroundPathFinder.run(AeroGroundPathFinder.java:71)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:203)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)`

**Comment by HammerGS** [comment]
Attached log is from when I log the save into MM RC2.  NPE in Log.

```
Exception in thread "Packet Pump" java.lang.ClassCastException: megamek.common.weapons.GRHandler cannot be cast to megamek.common.actions.WeaponAttackAction
	at megamek.common.weapons.WeaponHandler.getLargeCraftHeat(WeaponHandler.java:154)
	at megamek.common.weapons.WeaponHandler.calcCounterAV(WeaponHandler.java:214)
	at megamek.common.weapons.MissileWeaponHandler.calcAttackValue(MissileWeaponHandler.java:394)
	at megamek.common.weapons.MissileWeaponHandler.handle(MissileWeaponHandler.java:781)
	at megamek.server.Server.handleAttacks(Server.java:36168)
	at megamek.server.Server.handleAttacks(Server.java:36097)
	at megamek.server.Server.endCurrentPhase(Server.java:3105)
	at megamek.server.Server.changeToNextTurn(Server.java:3430)
	at megamek.server.Server.endCurrentTurn(Server.java:2457)
	at megamek.server.Server.receiveAttack(Server.java:13731)
	at megamek.server.Server.handle(Server.java:31891)
	at megamek.server.Server$PacketPump.run(Server.java:368)
	at java.lang.Thread.run(Unknown Source)

```



[megameklog.txt](https://github.com/MegaMek/megamek/files/1662538/megameklog.txt)

**Comment by NickAragua** [comment]
Looks like there was an issue processing the firing phase with the "dropships use individual weapons" setting turned on.l
