### ISSUE TITLE
Flying units AI locks up game

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/megamek#900]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.

megamek 43.7 via mekhq.  

### Description
While I have had many battles which have included vtols and air without issue, This time around that was not the case.  While either existed on the map java would max out its resource demand and slow to such a craw as to take multiple hours to complete one turn.  Once all the air units were removed (via destruction) the game returned to running normally, until reinforcements reintroduced some onto the map, at which point the slowdown was reintroduced.  log with errors is attached.

### Files
[megameklog.txt](https://github.com/MegaMek/megamek/files/1714092/megameklog.txt)

**Comment by HammerGS** [comment]
We really need a save game as well.

From the logs
Entity Invalid a bunch of different time. 
```
java.lang.IllegalArgumentException: Entity invalid. ID 137
	at megamek.common.Compute.isPilotingSkillNeeded(Compute.java:455)
	at megamek.common.MovePath.addStep(MovePath.java:474)
	at megamek.common.MovePath.addStep(MovePath.java:255)
	at megamek.common.MovePath.addStep(MovePath.java:167)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:370)
	at megamek.common.pathfinder.MovePathFinder$NextStepsAdjacencyMap.getAdjacent(MovePathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:304)
	at megamek.common.pathfinder.AbstractPathFinder.run(AbstractPathFinder.java:331)
	at megamek.client.bot.princess.PathEnumerator.recalculateMovesFor(PathEnumerator.java:290)
	at megamek.client.bot.princess.Precognition.run(Precognition.java:438)
	at java.lang.Thread.run(Unknown Source)
```

Later in the log seeing references to
Not enough memory to analyse all options. Try setting time limit to lower value, or increase java memory limit.
java.lang.OutOfMemoryError: GC overhead limit exceeded

**Comment by bczretribution** [comment]
I'll see if I can get an autosave, though it might be a little late in the game.  

I set the memory for megamek to 4gb, however, it seems when its launched through mekhq it stays limited to 1gb. not sure what i did wrong there.

**Comment by Dylan-M** [comment]
When launched from MHQ it is actually a sub-process of MHQ, so obey's MHQs memory limit. To have enough memory for both, try setting MHQ's RAM higher. I have mine set to 6GB.

**Comment by bczretribution** [comment]
Here is all the files related to the mission in question.  Unfortunately, I didn't have an earlier save so I'm not sure how much good that will do.  My player is named "the calvalry"

dylan, thanks for the info, ill do that.

[glitch.zip](https://github.com/MegaMek/megamek/files/1718353/glitch.zip)

**Comment by NickAragua** [comment]
I'll take a look at it tonight or tomorrow, depending on when I get some time.

**Comment by NickAragua** [comment]
Surprisingly enough, I think I got this with PR #2109
