### ISSUE TITLE
0.43.9-RC3 Princess crashes

### ISSUE THREAD

**Issue by mhjacks** [MegaMek/megamek#936]
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MegaMek does your issue apply to?  Note whether it is the stand alone MegaMek or HQ's MegaMek.
mekhq's megamek from 0.43.9-RC3
What operating system are you using?  Windows, Mac, or Linux? Linux (Fedora 27)
What java version are you using?  If unsure it will state your java version at the top of the megameklog.txt file. 1.8.0_161

### Description
Describe the issue and provide screenshots ingame if able.
Game becomes unresponsive after last fire declared for a turn.  NPE reported in logfile.

Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the saved game if applicable.
Played two different games with different forces that included artillery, tag and c3
[autosave.sav.gz](https://github.com/MegaMek/megamek/files/1813777/autosave.sav.gz)
[megameklog.txt](https://github.com/MegaMek/megamek/files/1813778/megameklog.txt)

### Files
Provide a saved game of when the issue was found.  If possible try to save the game during the phase before the issue occurs so the 
developers can step through the code and find exactly what it is that is breaking in the code.
Provide the megameklog.txt file for any NPE's or errors that MegaMek might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual megameklog.txt file
And provide your playername so that they can load the saved game.

**Comment by HammerGS** [comment]
Various NPE's from the Logs.
First Up. (Almost too Numerous to count)
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:664)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
Next
```
Report.addNewline failed, array index out of bounds
Exception in thread "Packet Pump" java.lang.ClassCastException: megamek.common.weapons.ArtilleryWeaponIndirectFireHandler cannot be cast to megamek.common.weapons.ArtilleryWeaponIndirectHomingHandler
	at megamek.server.Server.assignAMS(Server.java:14017)
	at megamek.server.Server.endCurrentPhase(Server.java:3113)
	at megamek.server.Server.changeToNextTurn(Server.java:3439)
	at megamek.server.Server.endCurrentTurn(Server.java:2462)
	at megamek.server.Server.receiveAttack(Server.java:13722)
	at megamek.server.Server.handle(Server.java:31884)
	at megamek.server.Server$PacketPump.run(Server.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Dylan-M** [comment]
I've fixed the artillery issue in the linked PR above.

However... the tooltip issue is going to be difficult to replicate without knowing where the player tried to get a tooltip from (to know what could possibly be null). Though, arguably, this is a problem with the core code in Oracle Java 8's implementation, since it doesn't properly handle something that can be null.

At any rate, hopefully nothing should crash now, since from the log it seemed it was the bad class casting that was causing the client to disconnect. Going to unassign myself from this. Hopefully at some point we can go through all the tooltip related code, and prevent any NULL values from being set.

**Comment by Dylan-M** [comment]
While we've fixed both issues from the log, these may not the cause of the actual freeze of princess. I'll be linking this report from a commit comment shortly, that we feel is related.
