### ISSUE TITLE
[43.9 RC3] Setting "tooltip dismiss delay" in client settings mostly freezes client

### ISSUE THREAD

**Issue by NickAragua** [MegaMek/megamek#943]
When leaving the lobby after having set the "tooltip dismiss delay" field in client settings -> main tab to -1, it's impossible to click on any buttons or menu items. This is probably somewhat important to fix before stable.

The log shows numerous NPEs of this nature:

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Invalid initial delay: -1
	at javax.swing.Timer.setInitialDelay(Timer.java:433)
	at javax.swing.ToolTipManager.setDismissDelay(ToolTipManager.java:178)
	at megamek.client.ui.swing.boardview.BoardView1.mouseExited(BoardView1.java:4762)
	at java.awt.AWTEventMulticaster.mouseExited(AWTEventMulticaster.java:310)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4668)
	at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4654)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4505)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by SJuliez** [comment]
My bad. Must look at it.

**Comment by Dylan-M** [comment]
Also, these aren't NPEs.. they're IAEs.
